### ISSUE TITLE
Options for standardizing on vocabularies for interoperability when publishing a Web API

### ISSUE THREAD

**Issue by rjcorwin** [farmOS/farmOS#1]
It looks like the UN has done some work on creating an ontology for Agriculture, it's an ontology called [Agrovoc (read their about page)](http://aims.fao.org/standards/agrovoc/about). The UN has also sponsored some work in Drupal to get Agrovoc into Drupal.   It's not entirely clear if that vocab is a clear fit for Drupal Farm, it will take some more digging. Here's what I've found so far.
- AgriDrupal installation profile 
  - doesn't look like this was ever finished, [not in the Installation Profiles list on Drupal.org](https://www.drupal.org/project/project_distribution?f[0]=&f[1]=&f[2]=&f[3]=sm_field_project_type%3Afull&text=AgriDupal&solrsort=iss_project_release_usage+desc&op=Search)
  - [about page on the UN ag site](http://aims.fao.org/tools/agridrupal)
  - [AgriDrupal demo site](http://www.agridrupal.org/Agridrupal7.x.7.9/agridrupaltest/agridrupal-current-readme-file)
  - [An announcement from 2013 that AgriDrupal is released but the download link is broken](http://aims.fao.org/community/agridrupal/blogs/agridrupal-based-drupal-7-has-been-released)
  - [An announcement that a new website is using AgriDrupal from 2014](http://aims.fao.org/community/blogs/rural-horizons-digital-library-uses-agridrupal)
- [UN sponsored Agrovoc module which has some commits from June 2014](https://www.drupal.org/project/agrovoc)
- [UN sponsored Agrovocfield module](https://www.drupal.org/project/agrovocfield)

**Comment by mstenta** [comment]
This is great! Thanks RJ.

I hadn't seen AgriDrupal. I took a quick look, but I'm still not quite sure what it's purpose is. It doesn't seem to deal with record keeping. Log into the demo site and take a look at the "node/add" page (http://www.agridrupal.org/Agridrupal7.x.7.9/node/add), and it has a big list of nodetypes, but most seem to deal with management of contacts, conferences, publications, etc. Pretty cool stuff, but not much overlap with the Farm distro, it seems. I need to look closer.

Agrovoc is cool, too. I'm not sure if it's exactly what we need, but we may be able to integrate it with certain parts of the system (like a vocabulary of agricultural threats, or crops, etc). It seems to be a dictionary of agriculture terms, for the most part. I'm curious what they are using it for, or if it's still just an idea at this point. Here is the list of their hierarchies (vocabularies): http://aims.fao.org/standards/agrovoc/functionalities/hierarchy.

The Farm modules are creating the following vocabularies currently, but they are not pre-populated with anything (leaving it up to the farmer to enter terms specific to their operation):

Crops (in farm_crop module) - This has potential for pre-population - but may also be overwhelmingly large if we try to put every possible crop in there... most farms have a certain set of things they grow, and the flexibility of the system right now also allows them to add varieties of crops. For example, "Tomatoes" might be a parent term, and "Sungold Cherry Tomatoes" could be a child variety. This kind of flexibility is nice from a farmer's perspective, but it may make it difficult to merge and aggregate data in a standardized way. At first glance, it doesn't look like Agrovoc has a taxonomy of crops.

Areas (farm_area) - This would always be farm specific.  And it might not even make sense for this to be a vocabulary in the long term. The primary reason I started it as one is to make "tagging" records with certain areas as easy as possible.

Priority (farm_log) - This is used in the "Issue" log type for giving the issue a priority. It probably makes sense to just pre-populate this with a few terms like "Low", "Medium", "High", and "Urgent". It probably won't change that much and doesn't really need to be shared outside of the individual farm.

Quantity Units (farm_log) - This might be the best one to pre-populate, with terms like "square feet", "rows", "lbs", etc - primarily to encourage standardization of measurements.  But ultimately, farmers need the ability to define their own measurements too, because everyone does things a little differently.  One thought I had with this is to add a field of some kind to these terms that helps relate it to a more specific measurement - by entering a conversion formula or something. This would help with standardization when data is aggregated from many farms.

Threats (farm_log) - This is provided with the "Issue" log type, allowing a farmer to enter a term to describe any threats associated with the issue. We may be able to pre-populate this to some extent, but it's hard to predict all the various threats out there, so leaving it open to new terms is going to be necessary I think.

Season (farm_taxonomy) - This is just a simple vocabulary that farmers can use to name their seasons (ie: "Main Season 2014", or "Winter 2015"). The Farm Taxonomy module (which provides this vocabulary) was originally used to provide some of the other vocabularies, as well, but I decided to move those to modules that used them, and leave this module for vocabularies that are shared by modules.

Generally speaking, the goals of FAO's AIMS is very exciting: "AIMS is a space for accessing and discussing agricultural information management standards, tools and methodologies, connecting information workers worldwide to build a global community of practice." -http://aims.fao.org/

We should try to get in touch with them and see where there's overlap in what we're doing.

**Comment by rjcorwin** [comment]
I definitely agree, it's hard to figure out the purpose of these things
which is too bad. The lowest hanging fruit would seem to me to be
standardizing on a crop vocabulary. When working with these datasets later
it would be a pain if some farmers entered tomatoes as "Tomato",
"Tomatoes", "tom", "tometoes", "red tomatoes", and on and on. Good find on
the term explorer btw, unfortunately I'm finding it really hard to
navigate. Look at how few terms I find under "Vegetables"
http://aims.fao.org/en/agrovoc-term-info?mytermcode=8174&mylang_interface=en&myLanguage=EN.
As you mentioned, getting int touch someone who is familiar with this
ontology could help us navigate this giant vocab, chances are it seems I'm
looking in the wrong place for Vegetables.

\ RJ

**Comment by mstenta** [comment]
Yea interesting... it could be that a lot of these vocabularies are just a start, too, and maybe they are expecting people to submit more terms. You're absolutely right about the variations in terms... it's a tricky thing to manage. Especially when you consider the mutability of species... ie: if a farmer breeds their own varieties of tomatoes and gives them a new name. I think the system NEEDS to be able to handle that... the trick is how do we bridge the gap between individual implementations and global aggregations of that data.

**Comment by mstenta** [comment]
I'm going to close this. It's still a good discussion, but doesn't need to be an open issue anymore.

**Comment by djodjoni** [comment]
funny I find this now :) (or I probably forgot it)

@mstenta  did you manage to get in contact with somebody regarding this.

The links here are quite old and not functioning. However you can play around with sparql for example for vegetables you can query: http://202.45.139.84:10035/catalogs/fao/repositories/agrovoc#query/d/prefix%20skos:%20%3Chttp://www.w3.org/2004/02/skos/core%23%3E%20select%20?x%20?l%20where%20%7B?x%20skos:prefLabel%20?l%20.%20%20%20%20%20FILTER%20regex(?l,%20%22Vegetables%22,%20%22i%22)%20%20%20%20%20%20FILTER%20(lang(?l)%20=%20%27en%27)%7D%0A

As regards to linking/extending this vocabulary is quite easy you just need to reference it from your custom one. The thing is that in the world there cannot be just one thing explaining all and thus the need for many variations is inevitable, but custom concepts can be used and referenced to the other ones existing.

I restarted my work from 1 year ago and I am in the process of generating and simplifying subsets of agrovoc and other ontologies to fit things related to food, production, delivery and all actors involved in the process. 
I will gladly help you to introduce this in the REST api you are going to provide.

**Comment by mstenta** [comment]
@djodjoni Yes in fact I was just speaking with someone recently! I need to take some time to explore it further, and brainstorm how it might integrate with farmOS. I'd love to hear any ideas you have - it's interesting to think about extending the existing vocabularies. I'd like to better understand those possibilities. Looking forward to working together!

**Comment by djodjoni** [comment]
Great! I am currently cleaning up those 'ideas' and writing them down so to be better understood by the community and then easily discussed over. Probably end of this week I will post it to food dashboard so we can all collaborate there. As regards to vocabulary extensibility there are many options and this is the beauty of linked data :) We can schedule a call next week and see what is practical for your case. Speaking of that will it be possible for you to send me a dump of your taxonomy + example user data on my mail: k@djodjo.org. This will help me a lot :)

By saying:
>  just speaking with someone recently

Do you mean someone from Agrovoc ? Did you discover/agree on something?

**Comment by djodjoni** [comment]
@mstenta did you make any progress with "someone from Agrovoc" ?

**Comment by mstenta** [comment]
@djodjoni Sorry this thread slipped my mind! I haven't made much more progress with the person who contacted me from Cornell. Just some intro talk, mostly. I'd like to do some more followup when I have a chance.

**Comment by djodjoni** [comment]
I can help you with that in in the coming weeks. I am finalizing some WP and Spree integration then is Drupal in my agenda :)

btw I have found a nice single module wich may come in handy: https://www.drupal.org/project/agrovocfield

interesting thing is that it has a local and remote option, however the remote is AIX soap service which I plan to update with the REST(json-ld) module of skosmos used by aims, for example:

http://aims.fao.org/skosmos/rest/v1/search?query=meat&lang=en

anyway lots of work but I hope to have a chance to free up some time for that the second part of April :)

**Comment by mstenta** [comment]
@djodjoni Cool! Yea I'm curious to see what the possibilities might be...
