### ISSUE TITLE
logs summary in map view

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#104]
i noticed that a summary of logs shows up for some areas in the map view but not others. harvests do not show up. activities do.

**Comment by mstenta** [comment]
Good catch!

I fixed this for Harvests specifically with the following commits:

https://github.com/farmOS/farmOS/commit/10321b1de9ffd2b05659c40b993dcd671fe93bbb
https://github.com/farmOS/farmOS/commit/a0928554f46425868df0d1ba431c87e75e1fdf3d

I didn't check all the other log types to see if there were others that need it, so let me know if you come across any. If I remember correctly, Harvest logs did not originally have an Area reference field, which is why they didn't get listed in the area details popup from the start. The area reference field was added later, but I forgot to add the other supporting code to show the link in the popup.
