### ISSUE TITLE
map view disabled by default for older computers

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#107]
i have several old machines that would make it more likely for me to enter data out in dirty dusty areas, but they are so slow that the site becomes almost unusable but I think that is mostly due to the map being loaded for almost every view. once we are using farmOS regularly logging activities and such, it is almost never necessary to have the map view load. is there a way to turn the map off on a per-session basis, or even better, have it only load by request?

**Comment by mstenta** [comment]
I like this idea.  There is currently a setting for disabling the maps, but it is a site-wide option (not user or session specific).  Extending that option to include user/session specific configuration would probably be the best approach.

**Comment by mstenta** [comment]
Cleaning up old issues. I'm going to close this because it's now possible to "collapse map" in farmOS ever since we converted to using the [farmOS-map](github.com/farmOS/farmOS-map) library. I think that should prevent it from loading all the map tiles (until you expand the map). And this state is stored in localstorage, so it will be on a client-by-client basis.
