### ISSUE TITLE
GPLv2 only or any later version

### ISSUE THREAD

**Issue by donaldr3** [farmOS/farmOS#113]
It wasn't immediately clear from the repo here whether farmOS was GPLv2 only or any later version. It looks like you added it to the Free Software Directory (<https://directory.fsf.org>) as GPLv2 or later, but I didn't see a notice indicating that in the project itself. You can learn about using license notices here <https://www.gnu.org/licenses/gpl-howto.en.html>. Thank you.

**Comment by mstenta** [comment]
Thanks for bringing this up @donaldr3.

I added a COPYRIGHT.txt file which states "either version 2 of the License, or (at
your option) any later version."  This was copied and modified directly from Drupal's COPYRIGHT.txt file, so that it would follow the same pattern. farmOS is a Drupal distribution, and is packaged on drupal.org, which means it must share the same license as Drupal itself (GPL v2 or later).

https://github.com/farmOS/farmOS/commit/cfdbb6a85f87330f387f9cebff9964b1d7c8a8cd
