### ISSUE TITLE
ESP8266 sensor example

### ISSUE THREAD

**Issue by markwbrown** [farmOS/farmOS#115]
I just put up an arduino sketch for an ESP8266 to post as a sensor and wanted to share with the community: [esp8266 farmOS](https://github.com/markwbrown/farmOS-ESP8266)

**Comment by markwbrown** [comment]
Runs on a nodemcu esp8266 12E I think I bought off eBay. Probably would need to be converted to lua for an old esp8266, but likely not worth the effort unless you’re going absurdly small with your sensor footprint.

**Comment by mstenta** [comment]
Thanks @markwbrown - this is great!

There were some earlier attempts to get an ESP8266 to post to farmOS, but they ran into issues getting it to work with SSL (I don't remember exactly why), so it's awesome to hear you were able to do it! How did you accomplish it? Is it by including the SSL fingerprint in the code?

I haven't played with ESP8266 myself, but I'll let others know so they can take a look too. Thanks again!

**Comment by mstenta** [comment]
I just had a thought: when an SSL certificate renews, will the fingerprint change?

Is it possible to get the fingerprint automatically, so that it doesn't need to be hard-coded (and so it won't need to be updated manually)?

(I wonder if this is the issue that was encountered in the previous attempts.)

**Comment by markwbrown** [comment]
As long as the certificate is signed with the same private key, the fingerprint won’t change. As far as automatically grabbing the certificate fingerprint, yes that’s totally possible by storing the result of an api call to the Grc site, but to do that the right & secure way would mean storing grc’s Fingerprint in code. If they change the private key their cert is signed with, lookup would fail (which is what you would want). From a security standpoint, I see no advantage to having a dynamic lookup of the fingerprint. There are better uses of the limited memory available on an esp8266. As far as how I accomplished this, I used nginx to log body and headers of post requests to access.log then ran the python sensor script floating around. And reverse engineered what worked (nothing out of the ordinary) I thought I had failed somewhere along the line because I hadn’t configured nginx to log and pass through the post request. Removing the logging of the post request made everything work again.

**Comment by mstenta** [comment]
Thanks for the info @markwbrown!

I'm giving some thought to collecting various examples like this together into an official resources page on farmOS.org. @chrowe and @dwblair did some work in the FIoT group (farm internet of things) on GitLab (with some general scripts, and some specific to farmOS): https://gitlab.com/fiot

@chrowe reminded me about this thread on the GOAT forum: http://forum.goatech.org/t/trouble-posting-sensor-data-to-farmos-from-arduino-esp8266/307/4 (where someone else ran into the HTTPS issue).

There's some other good information in there (and the forum in general) if you're interested! On the same note, we have chat rooms for farmOS and FIoT:

https://riot.im/app/#/room/#farmOS:matrix.org
https://riot.im/app/#/room/#fiot:matrix.org

> As long as the certificate is signed with the same private key, the fingerprint won’t change.
> From a security standpoint, I see no advantage to having a dynamic lookup of the fingerprint.

From a hosting and server-side perspective (where the private key resides), it's best to assume that you will need to change it - whether that's due to your own internal security policies, or in the case of a breach. So ideally you wouldn't need to worry about breaking all sensors that connect to that server. Ultimately, it's the responsibility of the sensor device owner to ensure that it is resilient against that.

We've been doing a lot of talking/thinking about various levels of resiliency in the farmOS and FIoT discussions - gracefully rebooting after power failures, caching data internally when data connection drops, etc.  So this is where my mind goes, and just something I'd like to share to prevent headaches on your end too (and anyone else who uses this example). :-)

**Comment by markwbrown** [comment]
Resiliency could be achieved by storing sensor data in eprom or on an external sd card, provided there are enough pins (the ESP8266 12-E should be able to do this via I2C, and accommodate many other sensors. Stored data could be cleared upon successful post of a batch (eprom would be limited in this respect both for storage and number of writes before failure) It would be nice to have an API endpoint within farmOS to get the SSL fingerprint. That way, certificate rotation could be accounted for more easily. If the device queries the host for it's SSL fingerprint, that's one less external variable to deal with.

**Comment by mstenta** [comment]
Archiving old/inactive issues to clean up the queue a bit...

**Comment by mstenta** [comment]
Actually @markwbrown I'd love to include more examples like this on farmOS.org - would you have any interest in adding some content to https://farmOS.org/guide/assets/sensors?

The code is here: https://github.com/farmOS/farmOS.org/blob/7.x-1.x/docs/guide/assets/sensors.md
