### ISSUE TITLE
Docker Installation Very Slow Pageloads

### ISSUE THREAD

**Issue by tgrosinger** [farmOS/farmOS#116]
I have a freshly installed FarmOS using the Docker image farmos/farmos:7.x-1.x
The installation was successful, and the site seems to be fully operational, however page loads are very slow.

Here are a couple logs to help show the problem. In this example, I am going from the compost assets page to the plantings asset page.

```
172.17.0.2 - - [21/Oct/2018:14:28:54 +0000] "GET /?q=farm/assets/plantings HTTP/1.1" 200 9450 "http://mydomain.com/?q=farm/assets/compost" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
172.17.0.2 - - [21/Oct/2018:14:28:59 +0000] "GET /?q=farm/assets/plantings HTTP/1.1" 200 9450 "http://mydomain.com/?q=farm/assets/compost" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
```

The request times displayed are when I actually clicked the link, however the page displayed to me did not actually change for a full 45 seconds.

The server this is running on is an Ubuntu 18.04 with Docker 18.06.1-ce. The server has a lot of cpu and ram, and isn't doing much else, so I don't think it is related to that.

Is there more information I can provide you to help solve this problem?
Thank you.

**Comment by mstenta** [comment]
Hi @tgrosinger - is this happening consistently (every time you try to load a page)? Or is it only happening on the first page load (after having not accessed the site for a few hours)?

The "first page load" slowness is caused by Drupal's built-in cron.  See my comment here: https://github.com/farmOS/farmOS.org/issues/36#issuecomment-428266587

If it's happening on every page load, then something else is up.

In the past, I had an issue with page load time that I traced to the filesystem that the volumes were saved on. In my case, I had the farmOS repository checked out inside a TrueCrypt volume, so Docker was mounting that into the container, and that was slowing things down a lot.  Simply moving my repository to a non-Truecrypt directory made a huge difference.  I wonder if something similar is happening to you?  Do you have Ubuntu's home directory encryption enabled?  Is the farmOS repo checked out inside that home directory?

Another question I have is: are you running Ubuntu inside a VM?

**Comment by tgrosinger** [comment]
@mstenta, thanks for the fast response!

This is happening on every page load when I am logged in. I just noticed that the Unauthorized and the login pages load very quickly.

I am not running Ubuntu in a VM, that is the host OS. The volume mounted is just a ZFS partition striped over 4 hard drives. It has been more than fast enough for media streaming and other intensive uses which were also performed in Docker containers.

Can you point me towards how you tested that? Maybe I can get some more concrete evidence for or against that theory.

**Comment by tgrosinger** [comment]
I moved both the mysql and the drupal installation files into my home directory and changed the docker volumes to mount there. My home directory is an unencrypted LVM partition.

Unfortunately the problem persisted.

I did notice the following log messages right when the container started:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.17. Set the 'ServerName' directive globally
 to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.17. Set the 'ServerName' directive globally
 to suppress this message
[Sun Oct 21 15:44:26.273442 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/5.6.38 configured -- resuming normal operations
[Sun Oct 21 15:44:26.273752 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Could that be a potential problem that is causing Apache trouble serving requests? Do you know how to set the ServerName in the container?

**Comment by mstenta** [comment]
Nope - those Apache messages are harmless. More info here: https://stackoverflow.com/questions/46266527/could-not-reliably-determine-the-servers-fully-qualified-domain-name-how-to

Are you using Docker Compose with the `docker-compose.yml` that is included with farmOS?

**Comment by tgrosinger** [comment]
I am not using the docker-compose. I have created the containers manually, but heavily inspired by the compose file. Here's what I used to start them:

```
docker create \
    --name="farmos_db" \
    -e MYSQL_ROOT_PASSWORD=farmos \
    -e MYSQL_DATABASE=farmos \
    -e MYSQL_USER=farmos \
    -e MYSQL_PASSWORD=farmos \
    -v /storage/farmos/mysql:/var/lib/mysql \
    --restart always \
    mysql:5.7.23

docker create \
    --name="farmos" \
    --link="farmos_db" \
    -v /storage/farmos/html:/var/www/html \
    --restart always \
    farmos/farmos:7.x-1.x

docker start farmos_db
docker start farmos
```

**Comment by tgrosinger** [comment]
Disabling cron did not have any effect.

A fresh installation (now using 7.60) configured to use sqlite still has the same trouble.

I also tried removing Traefik from between my browser and the docker container, however that had no effect.

Here's a more clear picture of what is happening, from the perspective of Chrome. Notice how the request sits in "Pending" for 50 seconds, then everything floods in very quickly.

![selection_001](https://user-images.githubusercontent.com/597386/47299615-7c96bc00-d5cf-11e8-84a1-329954f4a647.png)

![selection_003](https://user-images.githubusercontent.com/597386/47299618-802a4300-d5cf-11e8-94bf-fb63e4ff6bdf.png)

**Comment by mstenta** [comment]
Hmm yea that is strange.

Ok how about this... we can isolate whether it is a problem with Drupal installations in general and farmOS specifically. Are you running any other Drupal sites on your server currently?

If not, try this (copied and modified from your comment above):

```
docker create \
    --name="drupal_test_db" \
    -e MYSQL_ROOT_PASSWORD=drupal_test \
    -e MYSQL_DATABASE=drupal_test \
    -e MYSQL_USER=drupal_test \
    -e MYSQL_PASSWORD=drupal_test \
    -v /storage/drupal_test/mysql:/var/lib/mysql \
    --restart always \
    mysql:5.7.23

docker create \
    --name="drupal_test" \
    --link="drupal_test_db" \
    --restart always \
    drupal:7

docker start drupal_test_db
docker start drupal_test
```

It is identical to what you posted above, except:

- Changed the www image from `farmos/farmos:7.x-1.x` to `drupal:7`.
- Replaced all occurrences of "farmos" with "drupal_test" in the container names.
- Removed the `/var/www/html` volume mount because the `drupal:7` image comes with a webroot already and that would overwrite/empty it (we do some special stuff in farmOS's `docker-entrypoint.sh` to build our own webroot after the volume has been mounted).

This might tell us if it's a farmOS issue on your server, or a Drupal one more broadly.

**Comment by tgrosinger** [comment]
That's a great test. Not sure if this is good news or bad news, but the resulting Drupal installation is perfectly responsive. Somehow either adding the FarmOS add-ons, or something about the FarmOS container must be causing the slowdown.

**Comment by mstenta** [comment]
Ah ok - that is a good clue!

So before we conclude that it's farmOS (and not just Drupal), there is one other difference: we didn't mount the `/var/www/html` volume in the Drupal-only test. Can you try the same thing with the farmOS and see if that makes any difference?

**Comment by tgrosinger** [comment]
Hey @mstenta,
I did a bit more testing

* Started FarmOS with no volumes and using sqlite
* Started with docker-compose using a configuration that worked for a friend
* Tried disabling some modules

The friend whos is working is running Docker 17.03.2-ce (I have 18.06.1-ce).

Unfortunately none of those were successful. It still remains very strange that requests when not logged in are fast, but then become slow after login.

Do you know of a way to make requests with curl that are authenticated? I am trying to test requesting the site directly from the server it is running on, but having trouble getting it to recognize my auth cookie.

**Comment by anstosa** [comment]
👋 hello, friend here! Also happy to try things on my end to help isolate the issue.

**Comment by tgrosinger** [comment]
@mstenta,
On a whim I decided to try out what would happen if I created another user that was not the drupal admin and log in as that user.

When I log in with this user all pages load normally except for `/farm` and `/farm/areas`!

This is a huge improvement. I wonder why this makes a difference though. I am not familiar with Drupal, so I don't have much of a guess.

**Comment by mstenta** [comment]
Great tests @tgrosinger - those are good clues. And thanks @anstosa for helping! Let's see what we can figure out...

> It still remains very strange that requests when not logged in are fast, but then become slow after login.

Yea, this really does suggest that it's a farmOS issue.

> On a whim I decided to try out what would happen if I created another user that was not the drupal admin and log in as that user.
> 
> When I log in with this user all pages load normally except for /farm and /farm/areas!

Very interesting!

Are you noticing any difference in the "Network" tab of Chrome/Firefox's Developer Tools between the two different users?

Another thing we can do is install the Devel module (https://drupal.org/project/devel) and turn on query logging - this will print a summary of all the queries being run on the page, sorted by the amount of time they take.  This is sort of a broad shot in the dark approach, but might be a good thing to try next...

**Comment by mstenta** [comment]
> When I log in with this user all pages load normally except for /farm and /farm/areas!

What about /admin/structure/taxonomy/farm_areas/add ? That page also has a map on it. Wondering if the map has something to do with it...

**Comment by mstenta** [comment]
@tgrosinger and @anstosa - what version/commit of farmOS are you each running?

To find this out, go into [www volume mount]/profiles/farm and run git log - copy and paste the commit sha.

(Note that the repo you originally checked out may be at a different commit than the repo that is checked out within the volume - but the volume is the one that is running in the container - so that's the one that matters.)

**Comment by anstosa** [comment]
I'm on dceaa52

**Comment by tgrosinger** [comment]
@mstenta Mine is not a git repository, but here is the end of farm.info

```
; Information added by Drupal.org packaging script on 2018-05-18
version = "7.x-1.0-beta18"
core = "7.x"
project = "farm"
datestamp = "1526654589"
```

`/admin/structure/taxonomy/farm_areas/add` is loading slowly as well.

**Comment by mstenta** [comment]
@tgrosinger Ah ok - gotcha. Thanks. I forgot that the docker-compose.yml will automatically use Git to checkout the latest dev version, while using the farmOS image directly will download the latest packaged release.

**Comment by mstenta** [comment]
Talking with @tgrosinger in chat... some more clues:

He created a planting, and /farm/assets/plantings was slow to load. But when he deleted that planting, /farm/assets/plantings loaded quickly (all as non-admin user).

**Comment by mstenta** [comment]
@tgrosinger and I dug into this together via chat, and figured out what is causing it. It actually boils down to two issues - one that is specific to his host, and one that is specific to farmOS. I opened a new issue for the farmOS one with more details here: https://www.drupal.org/project/farm/issues/3009628

**Comment by mstenta** [comment]
@tgrosinger FYI I fixed the issue internally with farmOS causing so many requests to the CDN. I decided to just start packaging Openlayers with farmOS, instead of loading via CDN. The next release of farmOS will include it.

If you want help getting set up with that right now, ping me in Riot. I can walk you through it.
