### ISSUE TITLE
Automatically create harvest task

### ISSUE THREAD

**Issue by tgrosinger** [farmOS/farmOS#119]
If I create a planting and input the seed variety and seeding date, and that variety has a days to maturity, it would be great if a task were automatically created to harvest them. This could then of course be adjusted manually based on actual results, but it would be a nice guide/reminder.

Similarly, if I have stored the days to transplant, a transplant task could be created.

This feature should probably be optional though, as I would imaging some may not want it.

**Comment by mstenta** [comment]
Yes! So this is actually something I had in the back of my mind for the "Crop Planning Wizard" eventually. However, I've got some sponsorship to work on an intermediate step towards that: a quick form for entering a planting. Part of this would be letting you put in a date for the expected first harvest (and maybe even multiple harvests, if it's a "cut and come again" type crop). I need to open an official feature request for that quick form so that I can start collecting all the various ideas together.

Currently, there is a little shortcut "Plan" fieldset available when you first create a new Planting, which lets you create a Seeding and Transplanting log - but I'm thinking about moving that into the quick form as well, for consolidation/simplification.

The next step from there is to be able to auto-populate/estimate when those dates should be, based on stored "days to transplant" and "days to maturity" attributes of crops, like you described. It wouldn't be hard to add fields for those things to crops - but what would be really cool would be to maintain a database of common crops that you can choose from, which has that information already filled in.

There's a chance that @sudokita and I will be putting some real thought into that in the near future - as a separate utility service that farmOS can pull data from.

**Comment by mstenta** [comment]
I'd love to brainstorm more with you @tgrosinger - about all this stuff. Lots of things to think about, and lots of potential to build!

**Comment by mstenta** [comment]
Here is a stub feature request for the planting quick form if you want to follow along (it's on drupal.org, so you'll need an account on there to subscribe): https://www.drupal.org/project/farm/issues/3010520

I'll link back to this issue too, for reference.

**Comment by mstenta** [comment]
I'm going to close this in favor of that quick form feature. I think that will really pull a lot of this stuff together as a good next step.
