### ISSUE TITLE
Collapsable menus on the permissions page

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#122]
With lots of modules the permissions page gets pretty long. Due to the nature of it they are pretty repetitive, too. Would be nice if each _permission_ was a collapsable menu, just to shorten up the page and make getting to the 'save permissions' button easier

**Comment by mstenta** [comment]
There are some existing Drupal modules that might help:

Drupal 7: https://www.drupal.org/project/fpa

Drupal 8: https://www.drupal.org/project/permissions_filter

This one says it's for D7 and D8: https://www.drupal.org/project/filter_perms

If you set up and host farmOS yourself you're free to add any Drupal modules you want to it - just pop them into `[webroot]/sites/all/modules` and enable them at `/admin/modules`.

I don't think we'll add any of these modules to farmOS by default, however. I like to keep dependencies minimal so that we have less to worry about with upgrades. And especially with the coming Drupal 8 upgrade - I've been trying to avoid adding more modules until that's done.
