### ISSUE TITLE
Using RESTws Basic Auth for development

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#124]
The default authentication required for RESTws is a little complicated. For development, seems like the Basic Authentication sub-module may be a good work around.

The Basic authentication login module is included in farmOS but is disabled by default. Simply enabling the module is all you need. **By default the module only tries to authenticate usernames prefixed with 'restws'.** This can be changed by modifying the regex used against usernames - see the module documentation [here](https://cgit.drupalcode.org/restws/tree/restws_basic_auth/README.txt)

Using Basic Authentication makes it much easier to test the API with development tools such as Postman or Restlet. It simplifies the curl commands as well.

For Postman/Restlet configuration is just adding Basic Authentication to the request header. The request returns a cookie, which seems to be saved by the application. This means subsequent requests don't need the authentication header, as long as the cookie is saved.

For curl, requests just require the -u option.
`curl -u [USER]:[PASS] [URL]/log.json`

This makes things easier for development, but there must be reason for this being turned off by default?

**Comment by paul121** [comment]
Should we add this to development API docs? [Here](https://github.com/farmOS/farmOS.org/blob/7.x-1.x/docs/development/api.md)

Perhaps a quick section after Authentication? The rest of the document explains the API well, the authentication procedure is the only difference

**Comment by mstenta** [comment]
Thanks for documenting this @paul121 ! Yea it would be great to add a blurb to the API doc page. A sub-section of the Authentication info would be a good place for it.

I recall giving thought to enabling the restws_basic_auth module in farmOS by default, but ultimately deferred the decision. Ultimately, I think something like OAuth is the better approach, since it wouldn't require passing/storing credentials at all. So maybe just describing the options (and future plans) in the API docs, and then letting the site admin decide how to implement, is a simple approach in the meantime.

**Comment by mstenta** [comment]
Closing this because it was added as documentation: https://github.com/farmOS/farmOS.org/pull/42

Thanks again @paul121!
