### ISSUE TITLE
Install on Base Drupal

### ISSUE THREAD

**Issue by boilermanc** [farmOS/farmOS#125]
Hi, not real familiar with Drupal. But I have a base install of Drupal installed at my host. Can I install FarmOS on that base install or is the only way to install it with the full package?

Thanks!

**Comment by mstenta** [comment]
Hi @boilermanc - you should install the full package as a separate Drupal installation. There is an installation guide here: https://farmos.org/hosting/installing/

A bit of history, since you asked: Way back in the beginning, farmOS was actually a bunch of separate `farm_*` modules that could be installed separately in any Drupal instance. It became clear that a central organizing repository was necessary to provide a cohesive experience and pull them all together in an intentional way, so the farm distribution/installation profile was created. Eventually, the decision was made to merge all the separate modules into the central repository, because there was zero interest from the community to keep them separate, and it made ongoing development and maintenance more difficult. So the benefits didn't outweigh the costs.

It would still be theoretically possible to separate the modules out of the distribution and install them directly in a Drupal site, but it would require some deep knowledge of Drupal to do it successfully I think. It would probably be more trouble than it's worth.

My current opinion is that it's better to have a farmOS instance that is separate from other Drupal sites, and if they need to communicate then you can do so via API requests. This simplifies ongoing maintenance of both systems by keeping them decoupled - so if a new version comes out you can upgrade without being blocked by dependencies in the other system.

So that's what I would recommend. :-)

**Comment by boilermanc** [comment]
Thanks Michael, that helps. I am  trying to build this out at my hosting provider so hopefully they can help me install the whole package. 

Thanks!
