### ISSUE TITLE
Malformed endpoints in REST API?

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#126]
I'm not sure if this is a bug or not, but I realized that responses from the REST API give for the `next`, `first`, `last` properties, etc. don't include the `.json` extension, so when I go to those addresses, I get 404.

So when I go to:
https://test.farmos.net/log.json

It says that the next page is:
https://test.farmos.net/log?page=1

But that gives me a 404 (just testing in my browser). Is this the right behavior?

**Comment by mstenta** [comment]
@jgaehring Good catch! I didn't notice that.

It looks like there's an open bug report for it in the restws module's issue queue: https://www.drupal.org/project/restws/issues/2253947

The issue includes a patch, but hasn't been updated in a while... reading through it now to try to understand what the story is...

**Comment by mstenta** [comment]
@jgaehring It seems like that issue isn't moving forward - most likely just because the restws module was absorbed into Drupal 8, and so the old D7 contrib module we're using it's actively developed anymore.

From what I can gather, the plain `/log?page=1` endpoint works if you add an HTTP header "Accept: application/json" to the request... but ONLY if Drupal's page caching is not enabled, because that short-circuits the header. And it should be assumed that page caching will be enabled (and it is for all Farmier-hosted farmOS instances).

So we have a choice here: we can test out the patch, or work around the limitation in whatever code is using the API.

The patch looks OK to me.  The changes aren't very complicated.  I'll test it locally real quick to see if it works...

**Comment by mstenta** [comment]
Hmm. The patch from comment 31 in that issue fixes the next/prev links, but it breaks all other links in the actual log objects. For example, a log created by user ID 1 will link to "/user.json/1" instead of "/user/1.json".

The last patch (in comment 34) is meant to fix that, but it is not a complete solution - and makes the entire format parameter optional... so by itself it does not fix the next/prev links. :-(

**Comment by mstenta** [comment]
@jgaehring For what it's worth, the way I handled paging in the [farm_sync](https://github.com/mstenta/farm_sync) module is to just grab the `last` URL and parse out the `page` parameter of it, so I knew how many pages there were in total. Then a simple `for` loop works to request each page.

It's not as elegant as chaining the requests and using the `next` value, but it works as a workaround.

Here is the code that does that in farm_sync: https://github.com/mstenta/farm_sync/blob/8.x-1.x/src/farmOS.php#L178

**Comment by jgaehring** [comment]
> For what it's worth, the way I handled paging in the farm_sync module is to just grab the last URL and parse out the page parameter of it, so I knew how many pages there were in total. Then a simple for loop works to request each page.

Yea, I'm working out something similar. This is not an issue that's too hard to deal with, and frankly I feel like that's part of what the farm_sync modules are there for, to abstract away some of those thorny implementation issues. My big problem now is, how far to abstract that?

**Comment by mstenta** [comment]
I'm going to close this as "won't fix" since we're focusing efforts on farmOS 2.x now, which no longer uses the old `restws` module.
