### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#130]
Thinking about ways to support on-farm research projects. Because farmOS has great capability to track and collect data about assets (animals or plantings) through logs, it would be nice to organize these assets and logs as part of a research project. This could allow for other reporting/analysis features..

Some potential features:
- mark assets as part of a research project
- assign assets or groups of assets as a "treatment group" or a "replicate" (is the general for all research?)
- provide quick forms to facilitate data collection specific to a project
- generate reports/analysis relevant to research
- similar to reports, more options to export all data
- ....

Potential implementations:
- Create a new Drupal entity
- Use the Plan entity, create "Research Plans"
- ...

**Comment by MorgsBrew** [comment]
Could you set up a dynamic notebook with sections for basic data analysis and visualization? RMarkdown and Jupyter Notebooks. Templates can be set up by users and adapted over time

```{r}
```

**Comment by mstenta** [comment]
@MorgsJohn Yes! I've heard great things about Jupyter. We are starting to make a farmOS API library in Python too, which would allow you to pull data from a farmOS site into a Python application - so that could be a good pairing!  https://github.com/farmOS/farmOS.py

**Comment by ntropy-esa** [comment]
Hello,
Instead of creating a new issue; I would like to add to this one.

I am doing research with farmers, basically environmental assessments of their production techniques. I thought of farmOS as a nice open-source tool for collecting data; then exporting to some python libraries we use; and run the environmental assessments.

But before having my project partners install farmOS, I need to kind of check the idea works. Thus, two questions:
- is there some "sample data" that could be shared for a sample farm; e.g. 1 year of farm management, in SQL format or even better JSON?
- a python API to retrieve from a site the data sounds great; looking forward to it, how advanced is the work, what need for contributions? [I missed the Hangout call last week, a pity]

**Comment by mstenta** [comment]
Hi @ntropy-esa - Unfortunately there isn't a sample data set like you describe. It would be great to have one, I agree. Maybe someone using farmOS would agree to let their data be shared for this purpose. This is something we want to create more features around: abilities to share.

@paul121 has been making great strides in the Python library over in https://github.com/farmOS/farmOS.py

**Comment by mstenta** [comment]
I'm cleaning up old discussion issues in the Github queue and encouraging folks to move over to the new farmOS forum: https://farmos.discourse.group

This would be a great topic to start over there, if any of you are interested in kicking it off! If you do, please cross-link with this issue so others are able to find them!
