### ISSUE TITLE
This is unecessary in docker entrypoint

### ISSUE THREAD

**Issue by sokoow** [farmOS/farmOS#136]
This is actually an antipattern:

https://github.com/farmOS/farmOS/blob/ffef8543de8ae9e6b670be2e1cd277f94400992b/docker-entrypoint.sh#L104-L116

you can't be reinstalling the whole product and modules every time the pod/container starts :) It takes too much time, overwrites whole volume on /var/www/html and so on. Make this a part of Dockerfile build please.

**Comment by mstenta** [comment]
Thanks for making an issue for this, @sokoow - it's actually something I've been giving a lot of thought to myself recently.

I am planning on changing the way this works in the 2.x version of farmOS. I was thinking I would leave it as-is for the 1.x branch, just so we don't disrupt anyone currently using it - but we can consider it if it needs to be done in 1.x too. I would just want to think through how it might affect existing deployments first.

For historical context, there is some reasoning behind the decision to build the farmOS codebase in `docker-entrypoint.sh` rather than in the `Dockerfile` itself.

The simplified reason is that the farmOS Dockerfile was originally designed for local development purposes, and in order to use standard development tooling (eg: PHPStorm IDE) you need to have the whole `/var/www/html` available in the local filesystem (mounted as a volume into the container). As you know, mounting a volume into a Docker container REPLACES that directory inside the container - so if we build farmOS in `/var/www/html` via the Dockerfile, and then mount `/var/www/html` as a volume in the container, that directory is then empty when the container starts. So I decided to move the build process to the `docker-entrypoint.sh` script as a compromise.

I admit that when I did this I was still learning Docker best practices - and in hindsight I think it's a bad solution for a number of reasons. So I am eager to change this.

This issue might also provide some good thoughts and context for you (and others): https://github.com/farmOS/farmOS/issues/36

I've been giving thought to redesigning this in 2.x - and perhaps having two different approaches to farmOS+Docker: one for production hosting (which builds the codebase in the image), and one for development (which uses the same image, but mounts over the directory and has a second step to build farmOS's codebase in the volume).

I have some ideas already, but they aren't documented anywhere. Maybe we can use this issue to sketch them out, and then decide if it makes sense to apply them to the 1.x branch as well - or just leave that alone so it doesn't risk breaking anyone's active deployments.

**Comment by sokoow** [comment]
Yeah, i'm with you, but the way you run containers, especially on kubernetes is that you should have a pod coming up fairly fast. Second thing is that it should be persistent through node/pod reboots, so no install processes or config wiping is allowed here also. Third thing is that you usually overlay a single config file or tow in a volume max - not a whole source tree like you do currently. I'll try to rebuild your container the way I think it should be done to show you the contrast.

**Comment by mstenta** [comment]
> the way you run containers, especially on kubernetes is that you should have a pod coming up fairly fast

Yea that makes sense - and another reason to make this a priority.

> I'll try to rebuild your container the way I think it should be done to show you the contrast.

Thanks! But don't knock yourself out if it's a lot of work - I understand what it needs to look like - the trick is just getting there from where we are currently (with any community baggage that exists). And also making sure to account for and document the other use-cases needed for development purposes, etc.

The other big question will be: in a world without the entirety of `/var/www/html` mounted as a volume, that means more things will need to be installed directly inside the container... like Drush, Drupal Console, PHP Composer, etc (the last two in version 2.x only).

And to reiterate what I said in https://github.com/farmOS/farmOS/issues/132:

> In general, I think a lot of the considerations are going to be underlying Drupal considerations, not specific to farmOS - but it would be great to have them documented here so we can think them through in our context as well.

**Comment by mstenta** [comment]
Also worth noting, with regards to:

> the way you run containers, especially on kubernetes is that you should have a pod coming up fairly fast.

Once the contents of the `/var/www/html` directory are built, that folder can be mounted into any container - thus making all future containers start up instantly without the need for building it. So this is really only an issue on the VERY FIRST deployment, even as things stand right now.

Now, if sharing a folder like that across multiple Kubernetes servers is a problem (it very well may be), then that's a Drupal+Kubernetes issue that is not necessarily specific to farmOS - although it would be good to see if there are any known solutions/best practices around that in the larger Drupal community.

**Comment by sokoow** [comment]
> The other big question will be: in a world without the entirety of `/var/www/html` mounted as a volume, that means more things will need to be installed directly inside the container... like Drush, Drupal Console, PHP Composer, etc (the last two in version 2.x only).

Yes exactly, the only thing that is swappable in running container should be config files and env vars. Rest is prebuilt in the image. It's soo much faster and portable this way.  

> Thanks! But don't knock yourself out if it's a lot of work

I'll do it anyway - got couple of farmers in Europe interested in this project. When I sit down with them you'll get some feedback.

**Comment by mstenta** [comment]
> I'll do it anyway - got couple of farmers in Europe interested in this project. When I sit down with them you'll get some feedback.

Awesome! Thanks! Looking forward to learning from your experience...

**Comment by mstenta** [comment]
One key piece of info that might be useful to understand: there are basically two things that Drupal needs for persistence:

1. Database
2. Sites directory

The database is easy - that can exist on a separate server, which all the containers can point to.

The sites directory is trickier - that is where all site-specific config and user-uploaded files go to. The `settings.php` file is contained there too, which points to the database w/ credentials.

Something like AWS S3 would make the user-uploaded files a bit easier, because they would be stored on a separate server and could be linked to from multiple containers. But by default, Drupal expects to be able to upload files directly to the machine the codebase is hosted on. This would be one of the most important things to figure out in the Kubernetes context, I think...

**Comment by sokoow** [comment]
I just created you a pull on how it more or less should look like: https://github.com/farmOS/farmOS/pull/137

Still need to understand why I'm seeing lots of modules being installed when first run/setup is done - does this have something to do with the fact a brand new db is setup ?

**Comment by mstenta** [comment]
Thanks @sokoow ! Very helpful!

> Still need to understand why I'm seeing lots of modules being installed when first run/setup is done - does this have something to do with the fact a brand new db is setup ?

Are you seeing this in the Docker logs? Can you paste the beginning of the output so I can see what you're referring to and help understand it?

There are two stages to installing a Drupal site - there is the codebase build process (which you moved into Dockerfile+build.sh), and then there is the site installation (which is when it creates the necessary database tables, installs modules, etc).

If you are persisting `sites/default/settings.php` in a volume and the database in another container, then you shouldn't see modules being built/installed every time the container starts.

**Comment by mstenta** [comment]
@sokoow I outlined the main considerations for these changes in the pull request: https://github.com/farmOS/farmOS/pull/137#issuecomment-463200748

**Comment by mstenta** [comment]
This is resolved in 7.x-1.x.
