### ISSUE TITLE
bug: area (bed) generator creates 2 half-beds ?!

### ISSUE THREAD

**Issue by berteh** [farmOS/farmOS#140]
Hello.

Just tested the area generator to create 17 beds in my 22,5m wide field with an orientation of 177.
I was expecting to get 17 bed of the same width (around 1,4m), but instead got 2 half-width beets on south and north opposites, and 15 beds of full width.

Please fix it so all beds are indeed same width.

**Comment by mstenta** [comment]
Unfortunately this is just a limitation of the way the geometry math works, and ultimately it is due to having an imperfect rectangle to start with (the parent area).

Here is the code that does it: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_area/farm_area_generate/farm_area_generate.module#L374

If anyone can think of a better way to do it, let me know! I'm not a geo expert. :-)

**Comment by mstenta** [comment]
This related feature request may be the better way of solving your particular issue: https://github.com/farmOS/farmOS/issues/66

**Comment by mstenta** [comment]
I'm going to close this since it's not really a bug as much as just "how it currently works". And I think #66 will offer the "correct" solution to this. Please feel free to reopen if you think I misinterpreted...
