### ISSUE TITLE
Enabling Rules Module

### ISSUE THREAD

**Issue by CFWHISPERER** [farmOS/farmOS#148]
You shared either a link or instructions on adding the Rules module to farmOS but I cannot locate it at present; can you point me to that again please?

**Comment by mstenta** [comment]
I forget where we discussed this in the past. Rules is mentioned in this issue a few time, so maybe there's so info in there: https://github.com/farmOS/farmOS/issues/117

In general we are not going to add the Rules module to farmOS in Drupal 7 because it is not stable for Drupal 8 yet, and we can't add any more dependencies that will hold up that upgrade path. So if you do add Rules and start depending on it, just know that it may make things harder for you when it comes to to move to Drupal 8. Also note: Drupal 7 is "end of life" in 2021, so that's the hard cutoff we're looking at: https://www.drupal.org/psa-2019-02-25
