### ISSUE TITLE
Security Update?

### ISSUE THREAD

**Issue by CFWHISPERER** [farmOS/farmOS#152]
I followed your recent warning on a security update but I am still seeing this...

There is a security update available for your version of Drupal. To ensure the security of your server, you should update immediately! See the available updates page for more information and to install your missing updates.
There are security updates available for one or more of your modules or themes. To ensure the security of your server, you should update immediately! See the available updates page for more information and to install your missing updates.

What is the best way to deal with this?

**Comment by mstenta** [comment]
Hi @CFWHISPERER - yes! In fact a new version of farmOS is available - version 1.0!

https://www.drupal.org/project/farm/releases/7.x-1.0

It includes the security updates to Drupal core and modules.

Instructions for updating are here (I think you've done it before): https://farmos.org/hosting/updating/

Moving forward, I will try to have a new version of farmOS available whenever there is a security release of Drupal core or other modules (unless the particular security issue doesn't affect farmOS, in which case I might wait). So when you see security alerts in your farmOS, check https://drupal.org/project/farm for an update.

**Comment by CFWHISPERER** [comment]
Thanks Mike and congratulations regarding farmOS 1.0 of course.  In case you or anyone else is interested you can see what we are doing with farmOS as Eugene Permaledger here https://perma-ledger.com/ un guest pw 123456789

**Comment by mstenta** [comment]
Thanks @CFWHISPERER !

**Comment by CFWHISPERER** [comment]
Mike, I have another comment here, if those working on the mobile "addage" to farmOS need alpha-beta testers we are more than willing to help.

**Comment by mstenta** [comment]
Great!

Here is the Android beta: https://play.google.com/store/apps/details?id=org.farmos.app

iOS beta is happening in Apple's TestFlight system. We can add email addresses to be beta testers for that. Send me a private message on Riot.im (@mstenta:matrix.org) and I can add you.

**Comment by CFWHISPERER** [comment]
One more question I have, is farmOS version farm 7.x-1.0 Docker only?

**Comment by mstenta** [comment]
Nope! It's the same as previous releases: you can download the packaged tarball at https://drupal.org/project/farm and replace your old codebase with it (except the sites folder, of course). More info: https://farmos.org/hosting/updating/

**Comment by CFWHISPERER** [comment]
I had download the wrong tarball and corrected that and updated to 1.0 all looks OK thanks

**Comment by and712** [comment]
@mstenta i will just replay to that old ticket, because its the same question i have. 
Since the last farmOS stable release there are two hot fixes of the drupal core released. 



> Moving forward, I will try to have a new version of farmOS available whenever there is a security release of Drupal core or other modules (unless the particular security issue doesn't affect farmOS, in which case I might wait). So when you see security alerts in your farmOS, check https://drupal.org/project/farm for an update.

Is there a way of knowing if the release of the core module affects the secutiry of farmOS and maybe if it would be better to run farmOS without an internet access till the update is available?

**Comment by mstenta** [comment]
Hi @and712 - @calbasi asked the same question over here: https://www.drupal.org/project/farm/issues/3153519

In summary, if a Drupal core or contrib module security release is serious enough and/or directly affects farmOS I try to package a new farmOS release ASAP. But often they are for vulnerabilities that don't really apply to farmOS. We are a somewhat unique case in that all farmOS functionality requires a login - which greatly reduces our attack surface. Still, I try to get updates out as quickly as I can. :+1: 

And... I always commit the update to farmOS 7.x-1.x dev branch immediately. As you can see I updated Drupal core to 7.72 the day that it was released: https://github.com/farmOS/farmOS/commit/322cff29c5aefb6fbdd500065dd76beab38df265

This means that you can already download an updated version, because Drupal.org automatically packages a `7.x-1.x-dev` release based off of the latest `7.x-1.x` commit: https://www.drupal.org/project/farm/releases/7.x-1.x-dev (last updated yesterday)

You can update to the `7.x-1.x-dev` release in the same way as a normal release.

Hope that helps! And I hope to have time to release 7.x-1.5 very soon either way!

**Comment by and712** [comment]
@mstenta  Thank you for the answer!
Should we add this to the documentation? (i could try to do it )
Till now i would have never downloaded the dev branch to my production enviroment, because i thought its a real dev branch ;)

**Comment by mstenta** [comment]
Sure! If you'd like to take a pass at adding some docs for this, please do! My hope is that this is not something people need very often, though... so I'm not sure where to put it. Maybe it could just start in the FAQ?

https://github.com/farmOS/farmOS.org/blob/7.x-1.x/docs/faq.md

(The FAQ needs to be updated/reorganized in general... but this could be a good placeholder for that. And maybe we actually make a dedicated "Hosting FAQ" in the future, in the Hosting section itself... but that can be a future decision, doesn't need to hold this up.)

I'm thinking something like:

> Q: I see a security update warning. What should I do?

And then explain basically what I said above.

What do you think?

**Comment by and712** [comment]
@mstenta i created a pull request for this. https://github.com/farmOS/farmOS.org/pull/95

in this pull request there is also a change for the translation guide (i totally forgot that i did that long ago)
