### ISSUE TITLE
Possibility to use other Mapping Services, other than Google Maps?

### ISSUE THREAD

**Issue by DennisSuitters** [farmOS/farmOS#157]
Are there future plans to allow other Mapping Services rather than Google Maps?

**Comment by DennisSuitters** [comment]
I was primarily interested in not using Google Maps at all, but rather Open Street Maps or other service. In my installation locally, and I think it's because Google has changed their services, I get something about not being able to use the map resource correctly. I've since uninstalled the local install off of my laptop and need to install it on my desktop as using the map features is clumsy (but not impossible) using the trackpad on the Laptop.

I'm actually quite glad to find the FarmOS project, as everything else uses either a time limited preview or paid subscription, and I was about to start writing my own from scratch.

Thanks for moving the issue to the correct repo, I hadn't realised I'd posted in the wrong repo, sorry about that.

**Comment by mstenta** [comment]
> I was primarily interested in not using Google Maps at all, but rather Open Street Maps or other service.

You can do that!

When you are installing farmOS, it will ask for a Google Maps API key (because Google requires that now).  If you leave that blank, and continue with the installation, then OpenStreetMap will be used as the default layer instead of Google.

> Thanks for moving the issue to the correct repo, I hadn't realised I'd posted in the wrong repo, sorry about that.

No worries!  All part of managing the issue queue. :-)

We actually talked on last month's call about using the github.com/farmOS/farmOS issue queue as a sort of general forum/q&a. Specific technical items and roadmaps generally happen in drupal.org/project/farm instead anyway (or other github repos for specific pieces).
