### ISSUE TITLE
Feature Request: live distance/area display while drawing polygons

### ISSUE THREAD

**Issue by gpsavio** [farmOS/farmOS#176]
It would be really helpful if, while drawing daily paddocks (all irregularly-sized and -shaped), the length of the component lines/the total area could be displayed live. Another option that would provide basically the same function for me would be to input an area size and have the polygon shape be modifiable but constrained to be that size - if I'm understanding it correctly, this has been proposed [here](https://github.com/farmOS/farmOS/issues/118).

Thank you!

**Comment by mstenta** [comment]
Thanks for creating this feature request @gpsavio ! I would love to see live measurements while you are drawing in the map. I believe the Openlayers Javascript library supports this: https://openlayers.org/en/latest/examples/measure.html

So it would require extending the existing "draw" component we are using in OpenLayers to include measurements while drawing. It would also need to be aware of which system of measurement the farmOS system is configured to use (metric or us/imperial) and change the units based on that.

The example appears to be an either/or between length (for lines) and area (for polygons). So if we wanted to show both at the same time (length of individual lines AND the total polygon area) then we would need to customize it further.

Another consideration we need to think through: currently the "estimated area" of polygons is calculated in PHP on the server side. The Openlayers measurements would be calculated in Javascript on the client side. These calculations may not be exactly the same, so we could end up in a situation where you draw something in the client-side map and see one area measurement, and then when you save it, you see a different measurement.  One way of solving this is to save the calculated area, rather than calculate it on the fly in PHP. This related feature request would accomplish that: https://www.drupal.org/project/farm/issues/3051971

**Comment by mstenta** [comment]
Oh! This is done with the new farmOS-map library now! So we can close this. :-)
