### ISSUE TITLE
Various math errors without BCMath installed

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#179]
A number of issues that flagged up in my installation of FarmOS related to the dependency on BCMath. 
My 'patch' #178 dealt with the two issues that immediately flagged up on my system without the BCMath dependency installed, but there may well be more.

**Comment by mstenta** [comment]
Thanks for reporting this @Skipper-is - I always try to have conditional logic in farmOS wherever BCMath is used, to ensure that it is used when available, but still works without it. That said, I generally always have BCMath installed, so some of the fallback code may not be fully tested.

It should be pretty easy to fix this issue, and to search for other similar issues, since BCMath code should always be wrapped in a condition like: `if (function_exists('bcdiv') {`

I'll take a look at your pull request and see if I can find other similar bugs.

**Comment by mstenta** [comment]
I merged fixes for the issues you described in https://github.com/farmOS/farmOS/pull/178

I also skimmed for other potential issues by searching for `if (function_exists('bc` and examining the code in each instance. I didn't see anything that looked like it would cause the same issue. So I think we can close this.

Thanks again @Skipper-is !
