### ISSUE TITLE
API nor sensor endpoints not working

### ISSUE THREAD

**Issue by tangix** [farmOS/farmOS#181]
This must be a mistake on my side, but since I'm not a Drupal expert I need som assistance here. Running latest release of farmOS on a Debian 9 install. PHP 7.2.18 and apache. Using cert from Let's Encrypt and running the installation at the URL (obfuscated) `https://myfarm.xxx.yyy`.

My problem is now that none of the documented API:s or sensor examples works as specified in the documentation. They *do* work but with two major problems:

* Sensors: using the `curl` developer example from the sensor configuration page, I cannot get that to work. Being a PHP developer myself (albeit using CodeIgniter and Zend frameworks, not Drupal) I know too little about Drupal's internal routing to understand where it goes wrong, but clearly the `private_key` URI argument is not parsed in the sensor endpoint.
* API: same problem here, the arguments are not parsed. For example trying `/log.json?type=farm_observation` I get ALL log entries, not only observations. Furthermore, I cannot advance to the next page (the passed arguments are not there it looks like from my basic debugging).

My guess is that there is a problem running the system using `https://myfarm.xxx.yyy`. I have tried to adjust `.htaccess` (setting `RewriteBase /`) and `sites/default/settings.php`, setting `$base_url = 'https://myfarm.xxx.yyy';` but still no go.

Any help greatly appreciated.

**Comment by mstenta** [comment]
Hi @tangix. Hmm - I wonder if "clean URLS" are not enabled on your Drupal installation, perhaps?

If this were the case, then when you use farmOS in your browser, your URLs would look like: `https://myfarm.xxx.yyy/?q=farm/logs`, instead of `https://myfarm.xxx.yyy/farm/logs` (notice the `?q=...` part).  Drupal will automatically rewrite/remove the `?q=...` portion if clean URLs are enabled.

More information: https://www.drupal.org/docs/7/configuring-clean-urls/enable-clean-urls

That is just a hunch... but something to check, and sometimes a common problem when you're first getting started hosting Drupal.

**Comment by tangix** [comment]
@mstenta 
You hit the head on the nail there! I needed to enable `mod_rewrite` in my Apache installation and then enable clean URLS in Drupal.
I have updated the farmOS.org docs and created https://github.com/farmOS/farmOS.org/pull/53

**Comment by mstenta** [comment]
Great! Thanks for the pull request @tangix ! Case closed!
