### ISSUE TITLE
jQuery not loading when running in Docker with SSL

### ISSUE THREAD

**Issue by viktorsmari** [farmOS/farmOS#186]
I ran the container with Docker on a https subdomain with LetsEncrypt.

I have done this many times before with other containers with the help of [Https-Portal](https://github.com/SteveLTN/https-portal)

When I run it with farmOS I get the following errors in the console:

![2019-06-19_15-49-42](https://user-images.githubusercontent.com/1689020/59772112-731f3a00-92ab-11e9-94c7-384e5b113f90.png)

Which of course breaks the functionality of the site:
![2019-06-19_16-03-14](https://user-images.githubusercontent.com/1689020/59772299-cdb89600-92ab-11e9-9a89-5ccc46f46bf8.png)

**Comment by mstenta** [comment]
Hi @viktorsmari 

I'm not sure exactly how https-portal works, but I think this is similar to the issue described here: https://stackoverflow.com/questions/36222254/drupal-mixed-content-error-when-using-ssl-certificate

I believe what you need to do is explicitly define the `$base_url` in your Drupal `settings.php` file (usually located in `[webroot]/sites/default/settings.php`), so that it includes `https://`.  This should trigger Drupal to use `https://` for all the links it creates internally, including the link to jQuery.

For example:

`$base_url = 'https://myfarmosdomain.com';`

(Reopen if this doesn't solve the problem for you.)

**Comment by viktorsmari** [comment]
@mstenta Amazing thank you, it solved it!

Is this something that would be nice to have as a possible ENV var?

So the user could provide it as a `FARMOS_BASE_URL` in the `docker-compose.yml` and it would override the `$base_url` in `settings.php` if provided?

**Comment by mstenta** [comment]
@viktorsmari That's not a bad idea! However, I'm hesitant to add something that might interfere or conflict with someone's deployment. Currently, `settings.php` is not managed at all by us - it is created during the normal Drupal installation process.

So, just like Drupal itself (and the Drupal docker image, which we build on for farmOS) I think we should leave this to the end-user.

**Comment by mstenta** [comment]
It would be a great thing to document though! Perhaps we need a new page specifically for SSL configuration on https://farmOS.org/hosting/ssl ?

This isn't a Docker-specific issue - it would apply to anyone hosting farmOS with SSL (which we do recommend!)

**Comment by mstenta** [comment]
Then again... this is already thoroughly documented for Drupal here: https://www.drupal.org/https-information

Maybe we could just add a link to that on this page (where we mention SSL): https://farmos.org/hosting/installing/

**Comment by viktorsmari** [comment]
Yes that would be nice. Future searchers might also find this issue or issue #185
(Not everyone knows or cares this is using Drupal :nerd_face: )
