### ISSUE TITLE
Medicine Asset

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#200]
Could we please have a medicine asset? So we can have a record of medicines in storage, and be able to remove from the inventory of that medicine. eg, 200ml of Pen & Strep, used 50ml, update it to 150ml in storage.

**Comment by mstenta** [comment]
Yes! But there is more to do first. See this similar post to the forum recently: https://farmos.discourse.group/t/farmos-to-record-fertilizer-use/83/7

I think I'm leaning towards creating a more general "Materials" asset type, rather than a bunch of different ones (eg: Medicine, Fertilizer, Seed, etc etc etc), unless we find that there are distinctions that justify maintaining different types.  So with that in mind, I'm going to close this under the assumption that it will be possible once the other stuff described in that forum post are done.
