### ISSUE TITLE
Add new field value in Area type

### ISSUE THREAD

**Issue by WhiteTigerTR** [farmOS/farmOS#201]
Farm Areas. I could not add a new Area type in this form.

farm_areas/fields
![resim](https://user-images.githubusercontent.com/42409238/64964703-3cee5800-d8a4-11e9-8671-4f06f3fa60aa.png)

Thanks for your help

**Comment by mstenta** [comment]
Hi @WhiteTigerTR - area types are defined by modules by implementing `hook_farm_area_type_info()` hook, defined here: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_area/farm_area.api.php#L25

For example: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_area/farm_area_types/farm_area_types.farm_area.inc#L11

There has been some discussion around rethinking the way this works. Here is the relevant discussion:

https://www.drupal.org/project/farm/issues/2931505

Welcome your thoughts over there!

**Comment by WhiteTigerTR** [comment]
Hello @mstenta ,

First of all, thank you for your reply.
At the same time due to other projects
I could not go on this problem.

I have read your answer and tried to implement it, but
I could not expand existing layers.
    Building
    Field
    Landmark
    Water
    Property
    Greenhouse
    Bed
    Paddock

Could you share a sample code for one if possible?

**Comment by mstenta** [comment]
Hi @WhiteTigerTR, sure... take a look at the "Farm Crop Area Types" module included in farmOS:

https://github.com/farmOS/farmOS/tree/7.x-1.x/modules/farm/farm_crop/farm_crop_area_types

If you want to provide your own area type(s), that is a very simple example module you can copy and modify.  Just remember to put your custom modules in `sites/all/modules` and not in `profiles/farm/modules`, so that you don't lose them during a farmOS upgrade.

And worth noting: we are starting to plan out a major farmOS 2.x upgrade, which may change the way that area types are defined. We will provide upgrade paths for the types that come with farmOS, but not for custom types that you create. That will be up to you to maintain/upgrade when the time comes.

With that in mind, it might be better to use the existing types, or take part in the discussion around new types so that you can be sure you don't end up with upgrade issues in the future.
