### ISSUE TITLE
Group movements apply to individuals

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#202]
Would be really handy if movements of groups would follow through to the movement of the individual. For example, I have a group of nanny goats - I move them into Pond Field as a group. If I click on an individual goat, they're still located in the goat shed, where that individual last was as an individual.

**Comment by edwardont** [comment]
Confirm this issue affects animals in a group
moving group does not move grouped animal
![groupmovefail](https://user-images.githubusercontent.com/49967953/66270938-09766c00-e859-11e9-83cf-b15712409b2d.png)

**Comment by mstenta** [comment]
Yea this is how it works right now - for better or worse. Individuals can have different locations from the group they are in, which can cause ambiguity over their actual location.

I generally recommend that you track location on EITHER the group or the animal, but not both, because of this.

It's a "soft bug" that was introduced when we added the "Group" asset type.  Been aware of it for a while, but I'm glad you created this issue so we can discuss and figure out a good solution.

Here are some older threads that might provide some context:

- https://www.drupal.org/project/farm/issues/2469109
- https://www.drupal.org/project/farm/issues/2905112
- https://www.drupal.org/project/farm/issues/2915217

I can think of a few ways to resolve it, but there are costs/benefits... I planned on tackling this with the Drupal 8 upgrade, since it will probably require some refactoring/rethinking of how Group assets work in general (https://www.drupal.org/project/farm/issues/2361735).

Perhaps a good first step here would be to gather some feedback on how it *should* work, from an intuitive user perspective. And then consider if there are edge cases where that wouldn't make sense.

Originally, my thought was that "Group" would be the same thing as "Location" - so you would say that the animal is located in the group, and the group is located in an area.  However, some folks wanted to use Groups for more than just location (eg: grouping of equipment into categories of things).  Another thing that came up was: it may still be desirable for an animal to be in a group, but still be located in a different place.  For example: a cow may be part of "The Cow Herd" group, but maybe she is sick and was moved to the barn for quarantine temporarily - so her location is NOT the same as the group's location.

Welcome any/all thoughts/considerations on this.... it's a bit tricky to represent in a simple way. And the approach we took when we added "Groups" was very "simple".

**Comment by Skipper-is** [comment]
So I guess a way of resolving that would be that the location is from the latest log for either group or individual, if the individual is moved to the barn, then that would be the latest. I guess if you then moved the group to a new field, then that'd be a bit more interesting...
I think it'd be easier to just create/amend the record for that one cow, than it would be to do an individual movement for the other 50 cows that have gone in a new field though, so I'd be in favour of location just being from the latest log affecting that animal **or** group
If it is going to be a long term quarantine, I'd probably just move the cow out of the group.. Because from a management perspective, that is what I would be doing...

**Comment by mstenta** [comment]
> so I'd be in favour of location just being from the latest log affecting that animal or group

That is sort of where I'm leaning on this, too.

And for groups that are used for categorization (not location), then the recommendation would be to simply never "Move" the group.

**Comment by Skipper-is** [comment]
Yea, though even then, if you're going on the latest log, shouldn't make a difference. I've got a machinery group, all my machines were in the machinery compound at first, and they've since been moved all over the place

**Comment by mstenta** [comment]
At this point, we will probably need to refactor the way that location is stored/queried before we can do anything, however.

Currently, it is figured out on-the-fly via a somewhat complicated SQL query. Adding the group location consideration to it would be hard - maybe impossible.

The way to solve it would be to calculate the location of assets only when they change, and save that as a cached value in the database, which can then be queried with a simple `SELECT`. So I think that refactor may be a prerequisite for this.

**Comment by edwardont** [comment]
Whats the most confusing from UI perspective is the option to move the group exists.
If move group wasn't an option, I'd click into the group, use select all, then move, at that time I could de-select any animals etc I didnt want to move
Does Group even need a location if contained elements also have a location?
Cant it just be a tag?
Wouldn't that be a simpler solution, maybe a stopgap?

**Comment by Skipper-is** [comment]
I think if move group option stopped existing, I'd probably not bother with animal movements.... It is too much of a faff to go through and select all the stock from the group.. especially if you're doing it in the field app...

**Comment by mstenta** [comment]
> Cant it just be a tag?

Actually, "animal groups" *were* a tag (taxonomy term) before they became a full-fledged asset type.

The main reason we created the asset type was so that logs could be recorded against the group as a whole, instead of referencing all the animals individually within a group.  In some cases, that would mean referencing hundreds (or even thousands - there's no upper limit) of assets.

And because they are full-fledged assets themselves, they have all the same features of other assets: they can be archived, moved, shown on the map, have their own logs, etc.

The specific project that supported this was development of the Grazing module: https://github.com/farmOS/farm_grazing

In that module, you select the "Herds" (aka Groups) of animals that you want to manage, and you manage them as a whole.

Group membership can also change over time, just like location, and we keep track of that membership history via logs too.

**Comment by mstenta** [comment]
Ah ha! We can close this and I'm pleased to say that this works much better in farmOS 2.x! The new asset location logic will look at BOTH the individual's logs AND the group logs to determine the asset's current location. :-D
