### ISSUE TITLE
Display where data is created from (data source field)

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#205]
As we start thinking about building out integrations with other platforms (via the API and other mechanisms) it would be great to be able to capture _where_ data is being created from.

I envision this as a small bubble that appears alongside logs when viewing a list of logs. The bubble could display a small "OurSci" logo, say "farmOS API" or any other third party custom info. When viewing a single log, the interface could display a larger context describing where the data was created, and provide links to view that data in that platform, in addition to learning more about the third party platform. (Not logs are just an example, this could be any asset, area or log)

Similarly, a concept of "Data Providers" came to me. This could be an additional Drupal Entity that stores the info about a third party - name, description, logo, links - which could be referenced when tagging logs/assets with a "Data Provider". This could be integrated into the API Libraries as simple as `farm.log.send(payload, provider)` where `payload` is the `log` to create, and `provider` describes the "Data Provider" contributing the data. This could reference a Data Provider ID, and provided additional links to reference the same data on the third party site (`myfarmos.com/log/281` could include a link to `oursci.com/survey/8120491` which shows the same data, in another context)

**Comment by mstenta** [comment]
I like this idea a lot. We took a small step towards this with recent work for Our Sci, by adding an arbitrary `data` field to logs and assets. This allows systems that create logs/assets via the API to tag it with some custom information. It's not specifically for attribution, but it could be.

We could, perhaps, add an additional "Attribution" field that could be used for that specifically.

I'd like to give some more thought as to how it would all work, from the users perspective, and from farmOS's.  I don't think we should necessarily try to create a concept of "Data Providers" in farmOS itself, because technically anyone with credentials can push data - and that would add additional overhead.  Might be better to just allow it to be provided with the log/asset data like the existing `data` field.  Not sure....

**Comment by mstenta** [comment]
Related to this: when data is imported via CSV, we could fill in the same field with some stock info about when it was imported, and by whom. I believe that information is already being tracked behind the scenes by the Feeds module, but it isn't being displayed anywhere. Copying it into a new attribution field would be easy enough I think.

**Comment by mstenta** [comment]
This idea came up in a OpenTEAM technical working stream call again recently and I couldn't find this issue. Renaming this to include "data source" in the issue title, because that's what we were referring to it as.

**Comment by mstenta** [comment]
I'm going through and closing old/stale issues and discussions. Moving forward we are encouraging general discussions take place on the [farmOS community forum](https://farmOS.discourse.group). GitHub will be reserved for bug reports and pull requests.

@paul121 it probably makes sense to open a new issue on drupal.org for this one, if/when we decide to implement it - or just open a PR. It seems pretty straightforward, but if there's room for discussion on it we can open a new forum topic too.
