### ISSUE TITLE
Change Assets & Logs name?

### ISSUE THREAD

**Issue by CFWHISPERER** [farmOS/farmOS#218]
I do have another question, in the Assets section there is a option to choose "Plantings" and in the Logs an option called "Seedings".  As most of our work starts as seeds the "Plantings" is sometimes misleading to our users, is there a way to change either of these names?

**Comment by paul121** [comment]
Hi @CFWHISPERER ! This can be a bit confusing at first. I think its just a matter of teaching the farmOS "vocabulary" to your users 😃 

Once you have a `Planting` asset in farmOS, you can describe the asset with `logs`

From https://farmos.org/guide/assets/plantings/ :
> In addition to the standard log types that all farmOS assets share (activities, observations, inputs, and harvests), there are two log types that are specific to plantings: seedings and transplantings.

The `seeding log` defines the date, quantity, location, etc of the seeding for a `planting asset`. Later, you can optionally add `transplanting`, `activity` (weeding, fertilizing, irrigation, etc),`observation` and ultimately `harvest` logs that _describe the same `planting asset`_

You might be interested in the Planting Quick Form, too:
> A quick form is provided for quickly creating a planting along with associated seeding and/or transplanting logs. This is the fastest way to create all of those records in a single step.

@mstenta designed this because, as you say, most work starts with the seeds! Hope that helps!

**Comment by mstenta** [comment]
Thanks for chiming in @paul121 - that describes the reasoning for the names really well.

> is there a way to change either of these names?

This has come up a number of times, though, so it's something I still think a lot about. I definitely don't want to change anything in the current branch of farmOS (1.x) because people are used to how it works, and changes to the underlying entity bundle names is more tricky than it's worth, IMO.

But... with the migration to Drupal 8 coming soon we may have some opportunity to rethink how some things are named in farmOS. This might be a good discussion to start in the forum. I will kick that off and link to it here so we can solicit feedback from the community.

>  As most of our work starts as seeds

So... somewhat related, I wonder if this would be useful to you @CFWHISPERER : https://www.drupal.org/project/farm/issues/2976851

To summarize: currently you can't create a Seeding log unless you have a Planting asset to link it to. This was a decision I made early on, because I wanted to encourage people to think about their seedings as just an event that is part of the larger Planting asset. However, I've talked with some users who have very valid use-cases that DON'T require tracking the planting asset, and JUST want to record seedings. For example: pasture seeding, in which you are managing the pasture (the area), and adding seed to it.

So by making the "Planting" reference field optional (not required, as it is now) on Seeding logs, it would allow you to record Seedings that are not connected to a Planting.

That issue needs some more thought, though... and may end up being something that doesn't get done until the Drupal 8 migration anyway.

@CFWHISPERER In the meantime, if you haven't checked out the Planting quick form, I would highly recommend you do. It will create the Planting asset and Seeding logs at the same time. Which means your users will then be able to look at EITHER the "Assets > Plantings" menu OR the "Logs > Seedings" menu, and get to the same data from both directions. From what limited understanding I have of your use-case, I do still think tracking Planting assets would make sense.

**Comment by paul121** [comment]
Just now seeing this @mstenta - that's a good example for making the seeding log separate from Plantings.

> That issue needs some more thought, though... and may end up being something that doesn't get done until the Drupal 8 migration anyway.

I'm curious what makes this more complicated? I imagine there is more to it than just making the `Planting` field optional? Also curious what other things you think could be renamed in a migration to Drupal 8?

**Comment by mstenta** [comment]
> I'm curious what makes this more complicated?

See first comment on that issue here: https://www.drupal.org/project/farm/issues/2976851#comment-13380188

**Comment by mstenta** [comment]
> Also curious what other things you think could be renamed in a migration to Drupal 8?

Plantings / Seedings / Crops was the big one. There's also been some folks who don't like "Logs", but that one's not going to change in D8.

I've been leaning towards either "Crops" or "Plants" instead of "Plantings". And maybe just rename "Crops/varieties" to "Crop types/variaties" or "Plant types/varieties".

**Comment by mstenta** [comment]
Cleaning up old issues... I'm going to close this.

See also related forum topic: https://farmos.discourse.group/t/difference-between-plantings-and-seedings/267
