### ISSUE TITLE
Feature Request: FarmOs Capabilities

### ISSUE THREAD

**Issue by generalredneck** [farmOS/farmOS#222]
I was thinking we should probably add a "capabilities" section where modules can define that the site has a feature installed.. This will allow for the field kit (or any other application consuming the api) to know what it can support. You do a lot of  this right now with checking resources, farm asset, and log for the particulars on the farm.json resource... but it would be handy for the "optional" bits like farm_livestock, to explicitly validate it's available, or document the process to go about doing so. 

if you added a capabilities section, it could be as simple as a hook that alllows a module to implement and display settings that the user has configured. 

I think that's the idea you had around `hook_farm_info() but it seems pretty far reaching, allows you to muck wiht everything, and doesn't provide a good example on how to use it for :point_up:

**Comment by generalredneck** [comment]
A really good usecase may be in the farm_eggs module. I'm considering of making my own interface because fieldkit is very verbose. What I need is something that is simple to use as my users are intimidated by the immense amount of information that needs to be entered and I need something more like the "quick forms" but for mobile. So in the case of farm_eggs if field kit knew it was installed, it could provide a "quick form" for egg harvesting as an option. Same is true of other log entries that do not require all the fields.

Additionally, if you wanted to allow asset creation to keep up with it, you could then add the "produces eggs" checkbox on the animal creation screen.

**Comment by mstenta** [comment]
Interesting ideas!

I agree that `/farm.json` is getting a bit bloated. @jgaehring and I have also discussed what might be possible in D8 with the JSON:API Schema module (https://www.drupal.org/project/jsonapi_schema), for providing metadata back to Field Kit about available entity types.

I'd love to give this whole "capabilities" idea more thought in D8 as we start to leverage more of the API features available to us in that world.  Field Kit will definitely need more and more info, beyond just the available record types, so figuring out where to provide that will be necessary.

With regard to the egg form specifically, we are planning on making that Quick Form available as a Field Module in Field Kit in the future.  So that will also be an opportunity to think this through again.  The "produces eggs" checkbox is exactly one of those things that needs to be given more thought. :-)

**Comment by jgaehring** [comment]
> A really good usecase may be in the farm_eggs module. I'm considering of making my own interface because fieldkit is very verbose.

This is exactly the problem that Field Modules are intended to solve (farmOS/farmOS-client#217). And the farm_eggs quick form was actually one of the two farmOS modules we considered prototyping as our first Field Module, only narrowly losing out to [farm_weather](https://github.com/jgaehring/farm_weather). If you're interested in creating your own interface and have some ideas about what you'd like that to look like, perhaps I could show you how to do that as a Field Module.

**Comment by mstenta** [comment]
I think a lot of these ideas are covered in farmOS 2.x, so I'm going to close this.

@generalredneck One piece in particular that still needs to be figured out in 2.x is the Egg quick form module's "asset property" for designating that certain assets "lay eggs". I've been thinking more about this and I'm curious if we can avoid the need for that in 2.x. Instead, I wonder if we can add a simple "asset autocomplete" field for finding your layers the first time, but then cache that (somehow) and show it as a checkbox on future requests. That way it becomes 100% client-side logic, which can live in a Field Module, or in the Quick Form code (depending on which direction we go). Maybe not perfect... but I'm trying to think how we can avoid the additional database storage and API stuff required for the "asset properties" concept...
