### ISSUE TITLE
Timestamp widget hard to use

### ISSUE THREAD

**Issue by generalredneck** [farmOS/farmOS#223]
The dropdown selection method of selecting a time and date is just hard to use. I rarely do modify a task down to the second, and doing so via a dropdown seems really hard. Several pieces of software use a very standard calendar date picker and time selection widget for this type of scenario.

Some good examples are like https://eonasdan.github.io/bootstrap-datetimepicker/
or https://github.com/xdan/datetimepicker

There are a ton of them for D8. Having a hard time finding it for D7. Depending, you might be better off creating your own field widget here.

**Comment by paul121** [comment]
This is related to #209 where you cannot enter a year beyond what the predefined picker allows. I remember the D7 limitation when I was working on the quick form. Something to remember for D8!

**Comment by mstenta** [comment]
I agree the current timestamp widget isn't great. I didn't want to add any dependencies in the D7 branch, so the choice was between dropdown and popup, and I think I found an issue with the popup on mobile devices (although recently I think it was working well, so maybe that's outdated).

> you might be better off creating your own field widget here.

This was something I thought about too. Especially with this in mind:

> I rarely do modify a task down to the second, and doing so via a dropdown seems really hard.

One idea I had was to keep the dropdowns, but hide the time by default, with a button to expose it if you wanted to. Otherwise, it would just save the timestamp for midnight of that day. So it would default to just the date, but allow more granular time if needed.

But in D8, I'm a lot more open to adding contrib module dependencies if there is a good one and it's well supported.

**Comment by mstenta** [comment]
Added a link back to this from the farmOS 2.x UI/UX roadmap comments: https://www.drupal.org/project/farm/issues/3151246#comment-13752048

Closing this GH issue (along with another similar one that came in recently: https://github.com/farmOS/farmOS/issues/324), but rest assured it will be done! :-)
