### ISSUE TITLE
Add field for abbreviation to units

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#224]
I think it could be helpful to Field Kit if it were possible to add abbreviations to each unit so they could be displayed more compactly in the UI.

To illustrate, this is an example of a UI component I'm considering using for quantities:

![image](https://user-images.githubusercontent.com/5556545/71560194-9124de80-2a34-11ea-9d7d-2785a4b73a9c.png)

Here, if we were using "centimeters" instead of "in" or "cm", it might break the layout. I realize I'll still probably have to account for longer strings in the unit field, but I think it would make the overall UI cleaner for common units, which generally have a well established abbreviation we could use instead of the full name.

**Comment by mstenta** [comment]
This would be a great thing to consider if we rethink how units work in farmOS 2.x. I linked to this from the "Unit Conversions" thread on the farmOS drupal.org issue queue: https://www.drupal.org/project/farm/issues/2361915#comment-13417160

This would be difficult to do right now in 7.x-1.x because units are just simple taxonomy terms, and are created by the user in each farmOS instance as they are used/needed. We could easily add an "abbreviation" field to those taxonomy terms, but expecting users to go through and fill them in is probably not realistic.

The alternative would be to adopt a more structured unit representation in farmOS 2.x, and pre-populate sets of standard units which include abbreviations by default.

But in either case, you'll need to deal with the potential for longer strings in Field Kit, so it's almost a moot point anyway. Maybe you could just truncate them when they are shown in the quantity row like you have above, but show the full-length strings when you click on it and see the list of other options.

**Comment by jgaehring** [comment]
> The alternative would be to adopt a more structured unit representation in farmOS 2.x, and pre-populate sets of standard units which include abbreviations by default.

Yea, that would be nice in the future. Shame it doesn't sound like there's a quick fix though.

> But in either case, you'll need to deal with the potential for longer strings in Field Kit, so it's almost a moot point anyway.

Yea, agreed. Oh well.

**Comment by lucasbrendel** [comment]
One thing I have started looking at and I realize I am edge case, is I have been using the full names for units, because I just see it easier for me to keep track of the unit names. My plan is to take FarmOS.py and use a unit conversion lib that can get me better data manipulation and insights.

I do like the abbreviation idea though as an addition. I think there can be a lot of power in taxonomy terms having more fields than just name and description.

**Comment by mstenta** [comment]
@lucasbrendel that's not unusual - farmOS leaves it up to you to decide how you want to enter your units. I'm starting to give some thought to making this more structured in the future... love to hear any thoughts or lessons you learn from your experiments!

**Comment by and712** [comment]
i had the fun implementing units, categories and conversions in another project not long ago.. 
It was one of the biggest updates the product had ever seen (even if for the user it was no big change)

Our main challenges were: 
1. what happens  if a user deletes a used conversion? 
2. what happens if a user deletes a unit or even a complete category with units? 
3. when will the conversion be applied? 
4. what happens to already converted entries if the conversion rate changes? 

Yeah there are short answers to these questions. 
1. dont allow it 
2. dont allow it
3. dependes: directly or on every call 
4. dependes: if you want that the user can change old entries to the new conversions or not (both ways have pros and cons)

Longer version: 
1+2 Because of some Stakeholders we needed to allow deleting used conversions and units. (I would never ever go with this decision again)

3. This is also not so easy as it seems in the beginning. If you apply the conversion directly and forget about you lose much functionality combined with challenge 4. 
e.g. "money conversion rates", "value of the corn in your tanks depending on the current market price"

And thats just the tip of the ice berg ;)

**Comment by mstenta** [comment]
I'm going through and closing old/stale issues and discussions. Moving forward we are encouraging general discussions take place on the [farmOS community forum](https://farmOS.discourse.group). GitHub will be reserved for bug reports and pull requests.

The future of "units" in farmOS could be a great forum topic to start, if anyone wants to get that ball rolling! Feel free to link back to this issue if you do.
