### ISSUE TITLE
OAuth Scopes for 7.x-1.x

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#228]
Let's use this issue to discuss some considerations for implementing OAuth in 7.x-1.x.

In D7 we are somewhat limited by what we can do with the `oauth2_server`, specifically regarding scopes and user permissions. Because we are limited in D7 we don't want to worry about adding complete functionality until D8 (see #229). For now, the `drupal_user_access` and `farm_info` scopes cover our current use cases. **Here is what we can do:**

- **Create a `drupal_user_access` scope that logs a user in** and gives full access to the user account as they normally would. Right now, this is the only scope that would allow a 3rd party the ability to access farmOS records  (logs, areas, assets, etc) as you would via the farmOS client libraries. This is required for:
  - farmOS Field Kit
  - farmOS Aggregator - oursci use case
- We also have the ability to create other scopes that provide data in a more "custom" way separate from the `restws` API. **An example of this is the `farm.json` endpoint.**
  - This endpoint can be restricted to a normal user login OR require the `farm_info` scope
  - Drupal modules that provide info via `hook_farm_info` will have a method of checking for additional authorized scopes to limit what information is provided. In this way the `farm.json` endpoint will contain more or less data depending on the authorized scopes in the request. For example, the farm location may only be granted with the `farm_location` scope.
  - An important consideration for this endpoint is if we want to make it public. There are use cases where a 200 response from `farm.json` (even if it is empty) would be useful in detecting if a URL is a correct farmOS server. The `farm_name` or `api_version` could potentially be returned too.

**Some questions regarding scope naming** (There is no real standard for this, see the examples listed [here](https://oauth.net/2/scope/))

- ~Is `drupal_user_access` a good name for this scope? Perhaps `user_access`?~ This has been set to `user_access`
- ~Is `farm_info` a good name? Should we start this farm info scope "hierarchy" with `farm_info` and build up from there with? I like the idea of `farm_info` as a "catch all", with more specifics on top: `farm_location`, `farm_user`, `farm_resources` etc.~ `farm_info` will be the scope for basic farm information, but not a "catch all". Modules can require other scopes to provide other data.
- A similar approach to `farm_info` can be taken with `farm_metrics` - thoughts?

**Comment by jgaehring** [comment]
Looks great! My first thought goes back to something we discussed in Denver, namely...

Have we given any more consideration to garnering farmer feedback as to the nature and composition of the various scopes? Those scopes will ultimately correlate to a farm's personal data, so they need to address any privacy concerns farmers may have, like how we group certain pieces of data with other related pieces of data, etc.

I know we're still super early in this process, and working from a much lower level just to get the basic functionality, but perhaps we could start sketching out a review process we can employ in the future to make sure the low level scopes map to higher level expectations of privacy, eg, what farmers want to share and what they don't, in various user scenarios. That way we don't paint ourselves into a corner, where it becomes hard to meet those expectations based on technical decisions we made early on. Would it make sense to loop in some of the Human-Centered Design folks (cc @julietnpn, @sudokita) at this point or in the near future? Perhaps we could task someone else with designing that review process so we can still move quickly in development while knowing those concerns have been considered and will be a part of the QA process.

Hope that's not too tangential, perhaps this needs to be a separate issue, but I feel what we do here with OAuth could strongly influence the future potential of our efforts to make farmOS truly interoperable, from a UX standpoint, since the OAuth experience will also be the first point of contact for users, when connecting their farmOS account to other services in the OpenTEAM ecosystem.

**Comment by mstenta** [comment]
These were some of the "basic scopes" we talked about in chat:

- Access basic farm information (farm name, city/state/country/zip)
- Access centroid GPS coordinate (this would be more indentifying than site/state/country/zip, so could be a separate add-on scope)
- Access farm metrics (this would include things like total field area, asset counts, etc)

These would be especially useful in the community aggregator (https://github.com/farmOS/farmOS/issues/206), which IMO should not be asking for full permission to records, and instead should just ask for some high-level info. We want to encourage sharing on that, and I think the best way to do that is to keep the barrier low by allowing relatively non-identifying information (like exact location) to be shared.

**Comment by mstenta** [comment]
> Have we given any more consideration to garnering farmer feedback as to the nature and composition of the various scopes?

I agree I think this needs to be the process we go through in deciding which scopes to provide. Both farmers and the third-party integrations that we're talking about.

> hose scopes will ultimately correlate to a farm's personal data, so they need to address any privacy concerns farmers may have, like how we group certain pieces of data with other related pieces of data, etc.

Agreed 100%.

My perspective is that the scopes we need will become clear as real-world use-cases are defined. I would avoid trying to decide too much up front without having a real use case. But there are certainly some obvious ones we can start with (like the basic farm info I described above). When we start to get into accessing individual records (logs, assets, etc) things will get more complicated.

**Comment by alexadamsmith** [comment]
I agree with all of you that the Community Aggregator will require us to set specific and limited OAuth2 scopes.  The less we share, the more farmers will participate in the community aggregator. And data privacy is one of the things that really sets farmOS apart, so we need to be sure not to compromise it!

@mstenta 's three basic scopes seem like a very good starting point.  
>    Access basic farm information (farm name, city/state/country/zip)
>    Access centroid GPS coordinate (this would be more indentifying than site/state/country/zip, so could be a separate add-on scope)
>    Access farm metrics (this would include things like total field area, asset counts, etc)

In the Community Aggregator issue there was also some discussion of letting users identify their basic type of operation (animal, vegetable, grain, other), and perhaps some other high-level information using farmOS flags.  If we create farm-level flags like this (as distinct from flags on individual logs or assets), I could see including them in farm metrics scope.

> Have we given any more consideration to garnering farmer feedback as to the nature and composition of the various scopes?

I agree strongly with @jgaehring 's idea about reaching out to farmers, especially when we are ready to move beyond simply displaying farms on a map.  We might ask folks what they would be _willing_ to share, and also what data they would _want_ to share / have access to.  I feel like the aggregator has a lot of potential to facilitate farmer's own research and planning, and I'm still thinking a lot about how we could allow farmers to share basic agronomic information that might be useful to other farmers.

**Comment by mstenta** [comment]
Closing this in favor of https://www.drupal.org/project/farm/issues/3167752

We are no longer working on farmOS v1. I will link to this from the new 2.x issue for historical context.
