### ISSUE TITLE
Installing language pack causes additional entries in taxonomy 

### ISSUE THREAD

**Issue by putyourlitterhere** [farmOS/farmOS#234]
As described here https://farmos.discourse.group/t/how-to-add-categories/205/5?u=pdorffarm
I can see that translations of default entries in farm log categories have been added (instead of replaced) by installing a language pack file.
Now every default entry appears twice: English and in installed language. 

I installed additional language by manually downloading the po file from 
https://localize.drupal.org/download?project=farm and imported it in /admin/config/regional/translate/import

**Comment by mstenta** [comment]
Thanks for reporting this @putyourlitterhere 

This is definitely a bug - and probably has something to do with the funky "auto-creation" of log categories farmOS does. I'll try to describe this here (and refresh on it myself at the same time).

First, Log Categories are taxonomy terms in farmOS, in the "Farm Log Categories" vocabulary (see path: `/admin/structure/taxonomy/farm_log_categories`).

The `farm_log` module provides a custom hook that allows other modules to automatically add terms to that vocabulary called `hook_farm_log_categories()`:

https://github.com/farmOS/farmOS/blob/09411cbb31cfafdf49d04e1344a95bcd86468732/modules/farm/farm_log/farm_log.api.php#L25

Whenever a module is enabled in farmOS, the `farm_log` module runs the function `farm_log_categories_create_all()` which asks all modules (including the newly enabled module) if they provide any categories, and if so it creates category terms for them.

https://github.com/farmOS/farmOS/blob/09411cbb31cfafdf49d04e1344a95bcd86468732/modules/farm/farm_log/farm_log.install#L11

https://github.com/farmOS/farmOS/blob/09411cbb31cfafdf49d04e1344a95bcd86468732/modules/farm/farm_log/farm_log.module#L385

https://github.com/farmOS/farmOS/blob/09411cbb31cfafdf49d04e1344a95bcd86468732/modules/farm/farm_log/farm_log.module#L344

This uses the `farm_term()` function to create the term... but only if the term doesn't already exist.

https://github.com/farmOS/farmOS/blob/09411cbb31cfafdf49d04e1344a95bcd86468732/modules/farm/farm_log/farm_log.module#L369

https://github.com/farmOS/farmOS/blob/09411cbb31cfafdf49d04e1344a95bcd86468732/modules/farm/farm_term/farm_term.module#L22

The first thing that function does is attempt to look up the term by name (to see if it already exists):

https://github.com/farmOS/farmOS/blob/09411cbb31cfafdf49d04e1344a95bcd86468732/modules/farm/farm_term/farm_term.module#L27

So that is probably where the problem lies... 

... or at least part of it.

There could be bigger issues here with translated terms.  I think most of the time you wouldn't want the old (untranslated) terms in there at all.  You would want them to be in your language.

But... what if there are multiple languages in the site (eg: English and Spanish, which is not uncommon in the US) - we don't want BOTH versions of the term.

What we DO want is for the terms themselves to have translations available. This would be "content translation" in Drupal parlance, I believe.  So far, we have only been thinking about "interface translation" for the most part.  I know that Drupal 8 has a better system for handling internationalization/localization of both, so I wonder if it would make sense to just wait until we are on D8 to think through these bigger questions.

In the meantime, I wonder if we need to restrict the log categories to being untranslated.  Or else figure out the bigger questions around term/content translation, multiple languages, etc.

**Comment by mstenta** [comment]
I'm going to close this as "won't fix" because we're focusing all efforts on farmOS 2.x now, and we are no longer automatically creating these categories in 2.x. If anyone wants to tackle a fix for this in 1.x, pull requests are welcome!
