### ISSUE TITLE
Add file link(s) to "Export CSV" function

### ISSUE THREAD

**Issue by ludwa6** [farmOS/farmOS#241]
Since i am using FieldKit to capture Observations in the field, including photo(s) as a rule, i would like the ability to export a CSV file of selected records, including links to files.

**Comment by mstenta** [comment]
I agree this could be really useful. I'm not sure the best place for it. Right now the CSV export is pretty directly linked to the columns in the table Views themselves. And those don't include all photos, nor do they include any files (two separate fields, so there would need to be two separate columns). We could override those columns for the CSVs specifically, but that drastically increases the amount of code to maintain for each. Maybe still worth it, and maybe we would end up needing to do that eventually anyway. The question is whether or not this particular addition is worth taking that step.

Another option (if we're sticking to CSVs) is creating a separate standalone CSV exporter for images/files specifically. This would let us tailor it to this purpose, and would be a single separate View configuration to maintain.

Alternatively, and possible right now: use the API. Instead of exporting as CSV you could write a Python script that pulls exactly what you want into a custom CSV via API requests. This takes more work on your end, but is possible right now without any changes in farmOS.

**Comment by ludwa6** [comment]
Thanks, Mike. Sounds like the easiest way -and probably best way for now- would be via the API.

I am no programmer but -looking at [the API documentation](https://farmos.org/development/api/)- i can see the endpoint i want for this purpose is 
`/log.json?type=farm_observation `

... and if i wanted it the full list of observations in XML format, then:
`curl [AUTH] [URL]/log.xml?type=farm_observation`

... but, now i wonder: can i assume from this that asking for CSV instead of XML would also work? i.e.:
`curl [AUTH] [URL]/log.csv?type=farm_observation`

I've searched that API documentation for mention of CSV, but there is none, so i don't know if this can work -but would be nice if it could :-)

Also: for this "Collect Observations" UseCase, all the data i really want -besides data captured as a rule in FieldKit (uid, name, timestamp, geofield)- will be that held typically in "notes" and/or attached "files"... And if there be any server-side limitation imposed on storage and/or download of files (my instance is Farmier-hosted, NB), then that would be important to know.   Seems to me i saw somewhere a limit on frequency of such calls to server, tho i'm not seeing it on this page.  Am i missing something, i wonder?

**Comment by mstenta** [comment]
> now i wonder: can i assume from this that asking for CSV instead of XML would also work?

No, unfortunately. Only JSON and XML are supported (and honestly we've only ever tested out the JSON format). This functionality is provided by the RESTful Web Services module (https://drupal.org/project/restws) which is what we use to provide farmOS's API.

> Seems to me i saw somewhere a limit on frequency of such calls to server, tho i'm not seeing it on this page. Am i missing something, i wonder?

farmOS itself doesn't have any limitations, but Farmier hosting has a few to be aware of:

- If you are in a free trial, you can only upload 5 files.
- File storage is charged an additional per-gigabyte fee on top of the hosting fee itself. See https://farmier.com/pricing
- Sensor assets can only receive one data POST request per minute.

Those limitations are just basic protections against spam/abuse, and shouldn't really affect normal users at all. But if they do, please let me know!

**Comment by mstenta** [comment]
I'm going to close this issue. I think it would be difficult to include this in the default farmOS CSV exporters, as described above, and a custom API-based CSV exporter is the easiest next step here.
