### ISSUE TITLE
Move crop/variety field from planting asset to seeding/transplanting log

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#245]
Early on in the development of farmOS, the "Crop/variety" term reference field was added to the "Planting" asset type. The thought being: the crop/variety of a planting is a "static" property - meaning it won't need to change over time.

But as I've talked with folks, a few use-cases have come up that conflict with that "static" assumption.

Two examples:

- Pasture seeding: in some ranching operations, a pasture will be seeded and re-seeded with multiple species over the course of many years. Tracking the pasture as a planting is useful to conceptualize the plants within it, but it means you need to edit the planting to add the new species over time, and that is not linked to the logs that actually seed them.
- Tree grafting: imagine a planting that represents a single tree, which you then graft other species onto over time. It would be nice if the "transplanting" (or perhaps a new "grafting") logs could add species to the planting over time.

**Comment by idoshmida** [comment]
another examples:

If some of the planting dies, the farmer will need to seed/transplant again (because of bad seeds, bad farmer, bad soil, bad watering...).
when reseeding, the type of seeds might not be the same as the crop/variety of the old planting. we could add a new crop/variety to the planting but it would not record the actual time and number of plants because its not a log.

**Comment by mstenta** [comment]
Closing old/stale GitHub issues. I'd love to discuss this more in the farmOS community forum if there is interest: https://farmOS.discourse.group.

We will have to think about how it affects the farmOS v2 data model...
