### ISSUE TITLE
Question about Farmos

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#255]
Hello,
I'm new to Farmos and trying to explore the world of Farmos.
In this context, I will have 1-2 questions.
1. How can I see the codes of Farmos?
2. How can I add action-link, that is, the green button to the screen attached?
3.How can I see the codes of the screen below?
Thanks for your help in advance.
![Ekran Alıntısı](https://user-images.githubusercontent.com/61236746/75012020-215e2d80-5492-11ea-848f-e7cfcc71547d.PNG)

**Comment by mstenta** [comment]
Hi @compact24 - See my responses to your other post over here: https://github.com/farmOS/farmOS/issues/246 - it explains how those links are managed in code and which Drupal hooks you can use to add your own.

If you are interested in getting started with farmOS development, I would recommend setting up a local development environment on your computer.  We have some instructions on the website to do this using Docker: https://farmos.org/development/docker/

Then, it will mainly be a process of learning about Drupal module development.  farmOS is built on Drupal, so all of the same concepts apply.  There are lots of tutorials online to learn the basic concepts of Drupal module development.  You will need to have some of that knowledge in order to understand how farmOS code is structured, and how best to make modifications/additions to it.

I would be happy to answer specific questions you have as you get deeper into the process! General questions like that might be better placed in the farmOS Forum, in the Development category: https://farmos.discourse.group/c/dev/6

Hope that helps! Welcome to the farmOS community! :-)

**Comment by idoshmida** [comment]
> If you are interested in getting started with farmOS development, I would recommend setting up a local development environment on your computer. We have some instructions on the website to do this using Docker: https://farmos.org/development/docker/
> 
> Then, it will mainly be a process of learning about Drupal module development. farmOS is built on Drupal, so all of the same concepts apply. There are lots of tutorials online to learn the basic concepts of Drupal module development. You will need to have some of that knowledge in order to understand how farmOS code is structured, and how best to make modifications/additions to it.
> 
> I would be happy to answer specific questions you have as you get deeper into the process! General questions like that might be better placed in the farmOS Forum, in the Development category: https://farmos.discourse.group/c/dev/6
> 
> Hope that helps! Welcome to the farmOS community! :-)
>

helped me too. thanks.

for developing, what benefits do i have using local instead of webhosted?

**Comment by mstenta** [comment]
> for developing, what benefits do i have using local instead of webhosted?

Depending on what you're doing, having it hosted locally allows you to use an IDE such as PHP Storm, among other things.
