### ISSUE TITLE
Multiple point selection on the map

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#259]
![harita](https://user-images.githubusercontent.com/61236746/75876066-05f60980-5e26-11ea-93ea-d65f2396a4a4.PNG)

Hello,

In our project, we use a map showing the location of our seedlings in the dashboard section. Each point represents a sapling.
When we hover over it, the information appears in a popup. When we click on it, we can go into detail.
My question is this.
Do you know that you can select more than one point with a mouse or by drawing? How should I add a map for this?
(I have tried such maps in the Openlayers section, but they didn't.)

I would be glad if you can help.

**Comment by mstenta** [comment]
Ah interesting ideas!

When you say "we use a map showing the location of our seedlings in the dashboard section" do you mean in the main farmOS dashboard (the homepage of farmOS), or in the "Assets > Plantings" map?

Just so I understand... assuming that you could select multiple points on your map, what would happen next? Would it show multiple popups? Or show one popup that includes information about each point, perhaps?

FYI: In the latest version of farmOS (7.x-1.3) we completely refactored the way the maps are built. We are still using OpenLayers (the latest version of the JS library), but we are no longer using the OpenLayers Drupal module (which I think is what you were looking at previously when you mention the "Openlayers section"). The good news is that it may be a bit simpler to explore some of these ideas, since we have more direct control now over the JavaScript that is used to build all the map features. Here is the standalone farmOS-map library that we use now: https://github.com/farmOS/farmOS-map
