### ISSUE TITLE
Permission changes to farm roles not saving

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS#267]
I am observing some strange behavior where I cannot change the permissions for the `Farm Manager/Worker/Viewer` roles.

Here is an example showing how the permissions don't save correctly for the default farmOS roles, but do save for a custom role;

![Peek 2020-03-28 11-39](https://user-images.githubusercontent.com/30754460/77830898-08781600-70e9-11ea-8fb7-be05d73827a1.gif)

Is it expected behavior that the default farmOS roles cannot have their permissions customized?

Installation created according to: https://farmos.org/development/configure-local-https-reverse-proxy/

**Comment by paul121** [comment]
@symbioquine that is correct. I do not believe there is a way to modify permission for the Farm roles via UI. You can do it via `hook_farm_access_perms` (docs [here](https://github.com/farmOS/farmOS/blob/0b1b2b9ca2405d8f89e41825e7eeeec6bc1b0aae/modules/farm/farm_access/farm_access.api.php))- basically when the Permissions page is submitted, changes are over-written by modules invoking that hook.

I'm sure @mstenta can explain more, just wanted to shoot a quick response. Perhaps this should be documented more?

**Comment by symbioquine** [comment]
Thanks @paul121! I'm satisfied with that answer for my own application since it is easy to work-around for most purposes by using additional custom roles to grant different permissions.

However, I do think the admin experience of having permissions changes that silently don't take effect is confusing. Minimally this behavior should be documented at https://farmos.org/guide/people/ (Happy to send a pull request for that.) Also ideally there would be some sort of communication as part of saving the permissions to indicate that some of the changes couldn't be saved.

**Comment by mstenta** [comment]
Great question @symbioquine - and thanks @paul121 for explaining.

@paul121 is right that it is not possible to override the permissions of the three roles that come with farmOS (Farm Manager, Farm Worker, and Farm Viewer) **via the UI**. This is because these three roles are considered "managed" roles, meaning they are created and maintained automatically by the Farm Access module. So the only way to modify them is via code. The hook @paul121 mentioned `hook_farm_access_perms` is the primary method for doing so.

@symbioquine you are correct: one option is to simply create your own roles alongside the three default ones.  Or, you can create your own "managed" roles in a module, but that might be a little harder to customize. Also worth noting: the three roles are provided by the Farm Access Roles module (https://github.com/farmOS/farmOS/tree/7.x-1.x/modules/farm/farm_access/farm_access_roles), and you can turn that off to remove them entirely, if you want full control over the roles and permissions and don't even want those three to appear as options.

We did this to try to balance flexibility and ease of control.  So you can choose to use the "managed" roles or not, and there are various options in between.  Hope that all makes sense!

This behavior is not well documented, and I agree it should be.  This is custom logic that farmOS adds on top of Drupal's normal permission system, to make it easier to maintain these "managed" roles.

I'm going to add the "question" label to this and close it. But if either of you want to take the initiative to document this on farmOS.org, that would be great! Not sure where the best place to do that would be. So maybe just having this GitHub issue that people can find via search is enough for a start. Thanks again for bringing it up @symbioquine !

**Comment by symbioquine** [comment]
Sure thing. Thanks for the explanation!

**Comment by symbioquine** [comment]
> if either of you want to take the initiative to document this on farmOS.org, that would be great!

@mstenta Just a friendly ping on the [above PR](https://github.com/farmOS/farmOS.org/pull/80) whenever you have time :)
