### ISSUE TITLE
google map api mistake

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#269]
Hello,
I get the error as attached in my project. When I searched, I saw that it was caused by google api key.
I bought a new api key. The error still persists when I add it alone. What am I missing? Can you help?
I changed the api keys of the maps(Google Hybrid, Google Satellite,Google Terrain) in the second picture. I think it was insufficient.
![google-maps-oops-something-went-wrong](https://user-images.githubusercontent.com/61236746/78276499-c9e4c000-751b-11ea-8338-d4402db8b0b5.png)
![maps](https://user-images.githubusercontent.com/61236746/78276558-dff28080-751b-11ea-88e2-adb7e460bf7b.JPG)

**Comment by mstenta** [comment]
Hi @compact24 - I can try to help you debug this...

First, worth noting: the new version of farmOS (7.x-1.3) has changed the mapping code completely, and the page you included a screenshot of is no longer included. We removed the OpenLayers Drupal module and replaced it with a more streamlined OpenLayers library for farmOS called farmOS-map.js: https://www.drupal.org/project/farm/issues/3083352

But, you should be able to still get Google Layers working in the old version that you have... AND you will absolutely want to follow these steps before you upgrade to the new version, to ensure that the API key is migrated properly.

First, go to /admin/config/farm/map - you will see a field there to type in your farmOS API key. Did you already enter it here?

Second, you should "Revert" the changes you made to the three Google layer configurations that you showed in your screenshot. See how they say "Database overriding code" right now? You need to revert those so that they are using the code defaults. Otherwise the change you make in the first step above won't have any affect.

See if that works.  If not, then we can debug further.

**Comment by compact24** [comment]
Thanks a lot it Works:)

**Comment by mstenta** [comment]
Oh excellent! I'm glad it was that easy! :-)
