### ISSUE TITLE
Cannot filter the "History of Assets" in an Area

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#270]
There seems to be a bug in the "History of Assets" fieldset that is included on Area pages. When submitting the form to filter or sort, the params are not posted to the current URL, but the base URL of the farmOS site. After submitting the farmOS dashboard is displayed.

History of Assets when loading the page:

<img width="955" alt="Screen Shot 2020-04-04 at 10 00 27 AM" src="https://user-images.githubusercontent.com/3116995/78456982-eab42f00-765b-11ea-9b84-5b0fc9d90cba.png">

After submitting, the dashboard page is loaded with these params:

<img width="1018" alt="Screen Shot 2020-04-04 at 10 01 06 AM" src="https://user-images.githubusercontent.com/3116995/78457002-0b7c8480-765c-11ea-83a9-80db3322ff45.png">

 I made sure I filled out all of the fields in the form, but still had the same issue. The other fieldsets under Assets or under Logs of Type all seem to work (Plantings, Observations, Harvests, etc) - it's just this "History of Assets" fieldset.

I'm unsure where to hunt this down... is it configured in the Views UI?

**Comment by mstenta** [comment]
Ah good catch @paul121 !

I may be working on this View for another reason soon - so I can take a look.

**Comment by mstenta** [comment]
Fixed by https://github.com/mstenta/farmOS/commit/31fbaeb902fe30559fac8463d608ea8441d201ad

Applying filters will take you to a separate page now, just like the other assets/logs lists do.

I also collapsed the "History of Assets" box by default so that it doesn't take up real estate on the Area record page unless you want it to. Assuming that it is not what people are looking for most of the time, so doesn't need to be open, but it's still there when they need it.
