### ISSUE TITLE
Rough Edges with Custom Asset Types

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS#274]
I'm trying to use farmOS to model a local seed bank inventory - to do this I created a module which enables a `seed` asset type. I'm hoping to share this module after iterating on it some for our use-case - I can share the code sooner for troubleshooting/collaboration purposes if necessary, but I'm hoping this issue can stay at the theoretical level for now.

Overall it seems to be working largely as expected, but there are some rough edges;

1. I can't get CSV import to work with inventory/location tracking values - Ideally it should take the value for inventory to create an observation of the current inventory and for location associate/create an area with the specified name. Is this possible? I don't see any assets with feeds mappings for the inventory value...
2. Inventory quantities are unit-less. I can work around this by independently adding the `field_farm_quantity_measure` and `field_farm_quantity_units` fields to my asset type, but then the best I can do is put them in a similar place in the form - I can't seem to get them inside the same field set. Would you consider accepting a pull request to add optional "Measure" and "Units" fields to the inventory tracking module?
3. References between assets in the same CSV import don't appear to work correctly. e.g. If I have a unit of seed which is derived from another - either a selection or a subsequent year's grow-out - there would be references between them. I haven't looked at the code for the feeds module yet, but in this scenario I would expect it to do some combination of multiple passes or topological sorting to ensure entities are created before the references are populated. I haven't tested it, but I believe this should affect imports of Animal which have parents listed as well. I'm kind of looking for an opinion on this one, is this an unreasonable expectation for importing data?
4. Links to assets with `id >= 1000` have a comma included in the id which breaks the link.

**Comment by mstenta** [comment]
Awesome @symbioquine !

> I can't get CSV import to work with inventory/location tracking values

This is one of the limitations that currently exists for ALL importers. None of them support Location, for example. The simple reason is because Location is determined by a log, so importing assets with location would also need to generate a log. We could make a some custom Feeds target plugins to do that... just haven't yet.

The same would be true of Inventory. And Group Membership. And Weight observations. Etc.

> Inventory quantities are unit-less.

Yup. See https://www.drupal.org/project/farm/issues/2916551

This is one of the only things that has prevented me from rolling out inventory on all asset types (as well as creating Seed and Material assets and others).

> Would you consider accepting a pull request to add optional "Measure" and "Units" fields to the inventory tracking module?

I'm actually thinking about going in a slightly different direction: https://www.drupal.org/project/farm/issues/2991394

> I haven't looked at the code for the feeds module yet, but in this scenario I would expect it to do some combination of multiple passes or topological sorting to ensure entities are created before the references are populated.

Nope, don't think it's that smart, unfortunately.

Any thing that needs to be referenced in an import needs to already exist in the system.

Generally speaking, I love Feeds.  It is a great architecture with it's plugins etc.  Makes it really easy to sketch up a CSV importer.  But it has very real limits, and I'm not sure if it is our best long-term approach in farmOS.  This is a great example.  Another example is that it doesn't let you "review" things before creating them, and isn't great about telling you when something went wrong. So sometimes it will create a record, but won't fill in all the details if one of them wasn't correct. And you won't know that unless you look closely.

@paul121 has been doing a little bit of work on Python-based CSV imports... PERHAPS with the hope of making something more generally useful in the future.  But it's starting from scratch, and it would not be baked into the farmOS UI itself... so still lots to think about there.

The other thing I'm keeping an eye on is Drupal 8 core's Migrate API, and specifically this module: https://www.drupal.org/project/feeds_migrate.  It's not ready for production use yet, though... and farmOS is still on D7.

> Links to assets with id >= 1000 have a comma included in the id which breaks the link.

This seems like it would be a spreadsheet formatting issue.  Can you fix that in the spreadsheet program itself to ensure that the values are saved to CSV without the comma?

**Comment by mstenta** [comment]
FYI I think my latest thinking is that https://www.drupal.org/project/farm/issues/2991394 would negate the need for https://www.drupal.org/project/farm/issues/2916551.

It's a pretty big architectural change, however... so I'm not sure if I want to go to the effort of doing it in Drupal 7 and then redo it in Drupal 8. We've already started building the Quantity fields in a new way for D8, which will make it much easier to add Inventory to the same thing, and then we can migrate data from farmOS D7->D8. So that's really where I'm leaning...

I know that doesn't help you in the short term, though. But hopefully it contextualizes where everything stands right now. :-/

Perhaps you could just use your Seed asset type without units for now? And just store them somewhere arbitrary that isn't perfectly linked up, but is still there for your reference? And then when we move to D8 everything will come together! :-)

**Comment by symbioquine** [comment]
@mstenta Thanks for all the info!

> Perhaps you could just use your Seed asset type without units for now?

Yeah, I'll stick with the work-around of independent measure/unit field instances for the time being.

> > I can't get CSV import to work with inventory/location tracking values
> 
> This is one of the limitations that currently exists for ALL importers. None of them support Location, for example. The simple reason is because Location is determined by a log, so importing assets with location would also need to generate a log. We could make a some custom Feeds target plugins to do that... just haven't yet.
> 
> The same would be true of Inventory. And Group Membership. And Weight observations. Etc.

> Generally speaking, I love Feeds. It is a great architecture with it's plugins etc. Makes it really easy to sketch up a CSV importer. But it has very real limits, and I'm not sure if it is our best long-term approach in farmOS. This is a great example. Another example is that it doesn't let you "review" things before creating them, and isn't great about telling you when something went wrong. So sometimes it will create a record, but won't fill in all the details if one of them wasn't correct. And you won't know that unless you look closely.
> 
> @paul121 has been doing a little bit of work on Python-based CSV imports... PERHAPS with the hope of making something more generally useful in the future. But it's starting from scratch, and it would not be baked into the farmOS UI itself... so still lots to think about there.

The CSV importer turned out to have too many limitations for my use-case. I ended up going with a one-off Python script;

```python3
from bs4 import BeautifulSoup
import sys, csv, requests, getpass

site_url = sys.argv[1]
csv_filename = sys.argv[2]
group_id = sys.argv[3]

session = requests.Session()

# Assumes a configuration similar to the one documented at https://farmos.org/development/configure-local-https-reverse-proxy/
if "farmos.local" in site_url:
    session.verify = '/home/{}/.local/share/mkcert/rootCA.pem'.format(getpass.getuser())

data = {
    'name': 'root',
    'pass': getpass.getpass(),
    'form_id': 'user_login',
}

login_req = session.post(site_url + '/user/login', data=data, allow_redirects=True)

if login_req.status_code != 200:
    print("Login failed", file=sys.stderr)
    sys.exit(1)

seed_asset_form_page_req = session.get(site_url + '/farm/asset/add/seed?destination=farm/assets/seeds')

seed_asset_form_page = BeautifulSoup(seed_asset_form_page_req.text, 'html.parser')

seed_asset_form_build_id = seed_asset_form_page.find("input", attrs={"name": "form_build_id"})['value']
seed_asset_form_token = seed_asset_form_page.find("input", attrs={"name": "form_token"})['value']

def get_asset_id_by_primary_id(primary_id):
    asset_csv_req = session.get("{site_url}/farm/assets/seeds/csv?field_primary_identifier_value_op=%3D&field_primary_identifier_value={primary_id}".format(site_url=site_url, primary_id=primary_id))

    csv_rows = csv.DictReader(asset_csv_req.text.splitlines())

    matching_rows = list(filter(lambda row: row['Primary Identifier'] == primary_id, csv_rows))

    if not len(matching_rows):
        return None

    return matching_rows[0]['Asset ID']

def add_seed_asset(name, primary_id, external_ids, description, grams, season, location, group_id, enclosing_seed_container=None):
    headers = {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'}

    enclosing_seed_container_field_value = ''
    if enclosing_seed_container:
        enclosing_seed_container_id = get_asset_id_by_primary_id(enclosing_seed_container)
        enclosing_seed_container_field_value = '{} ({})'.format(enclosing_seed_container, enclosing_seed_container_id)

    form_fields = {
        'name': (None, name),
        'field_primary_identifier[und][0][value]': (None, primary_id),
        'field_external_identifier[und][0][value]': (None, external_ids),
        'field_external_identifier[und][0][_weight]': (None, '0'),
        'field_farm_description[und][0][value]': (None, description),
        'inventory': (None, grams),
        'field_farm_quantity_measure[und]': (None, 'weight'),
        'field_farm_quantity_units[und]': (None, 'grams'),
        'location[areas]': (None, location),
        'group[group][]': (None, group_id),
        'field_enclosing_seed_container[und]': (None, enclosing_seed_container_field_value),
        'field_farm_seed_source[und][0][value]': (None, ''),
        'field_farm_season[und]': (None, season),
        'field_seed_date_acquired[und][0][value][date]': (None, ''), #'04/18/2020'
        'form_build_id': (None, seed_asset_form_build_id),
        'form_token': (None, seed_asset_form_token),
        'form_id': (None, 'farm_asset_form'),
        'op': (None, 'Save'),
    }

    post_req = session.post(site_url + '/farm/asset/add/seed?destination=farm/assets/seeds', files=form_fields)

    if post_req.status_code != 200:
        if not get_asset_id_by_primary_id(primary_id) is None:
            print("Skipped already existing seed asset: {} - {}".format(primary_id, name), file=sys.stderr)
            return

        raise Exception("Failed to add seed asset: {} - {}".format(primary_id, name))


with open(csv_filename, newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for idx, row in enumerate(reader):

        add_seed_asset(
            name=row['Name'],
            primary_id=row['Primary ID'],
            external_ids=row['External IDs'],
            description=row['Description'],
            grams=row['Quantity Value'],
            season=row['Season'],
            location=row['Location'],
            group_id=group_id,
            enclosing_seed_container=row['Enclosing Seed Container'])

        print("Added seed asset: {} - {}".format(row['Primary ID'], row['Name']), file=sys.stderr)
```

*Not beautiful, but highly effective :)*

> > Links to assets with id >= 1000 have a comma included in the id which breaks the link.
> 
> This seems like it would be a spreadsheet formatting issue. Can you fix that in the spreadsheet program itself to ensure that the values are saved to CSV without the comma?

This turned out to be a n00b error with views. If one deletes the primary id column from a view then the links stop working because the SQL query doesn't return the primary id any more. If you add it back naively it defaults to formatting with a thousands separator - which Drupal isn't smart enough to omit when it constructs the links.

The fix was adding the following into my `.views_default.inc` file;

```php
$handler->display->display_options['fields']['id']['separator'] = '';
```

**Comment by mstenta** [comment]
> Not beautiful, but highly effective :)

If it works, then it's beautiful in it's own way!

Glad to hear you got it working - and thanks for posting the script for others to adapt in the future!
