### ISSUE TITLE
Geolocate button doesn't work

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#277]
![geolocate](https://user-images.githubusercontent.com/61236746/79751839-efdfd200-831b-11ea-84ba-7516c6f060e7.JPG)

Hello,
When I click on the geolocate button on the maps, I cannot get my instant location.
Why is this caused?
Normally, when I enter another application, I can get the instant location.

**Comment by WhiteTigerTR** [comment]
be sure of two things.
1- enter the system via https
2- allow when browser wants to use location

**Comment by mstenta** [comment]
@compact24 The new version of farmOS (7.x-1.3) includes a new mapping library: https://github.com/farmOS/farmOS-map.  The code for the geolocate button changed as well, so it would be worth updating and testing that as a first step.

@WhiteTigerTR is correct, too: geolocation only works over HTTPS, and your browser and operating system have to be configured to allow location to be used.

We have a demo of the new farmOS-map library hosted here: https://farmos.github.io/farmOS-map

You can test the geolocate button there, outside of your own farmOS system, to confirm that it works by itself.  That demo is served via HTTPS, so that is one less factor as well.

I am going to close this, but reopen if you continue to have issues after doing those things.
