### ISSUE TITLE
areas  page does not open?

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#280]
Hallo,
We also show our seedlings as areas on the map. There are approximately 29000 areas, so the garden areas page does not open. Can there be a solution for this?
? q = admin / structure / taxonomy / farm_areas I cannot access this page.
 I record all that points by using the area importer.

My goal is to see the farmer on the map with the data from the satellite with the RTK device, and know which planting is next to him, and add log records into these plantings.(activities,seedings etc.)
Can I collectively register 29000 plantings from the assets section? the location of all of them is certain, if I save them from assets, can I enter their locations, of course?

otherwise, how can I reach the page that does not open when I use it from the fields section?

**Comment by mstenta** [comment]
Hi @compact24 - that's a lot of areas haha!

Yea, I think these should be represented as Planting assets, not as Areas.  I'm not surprised that the Areas page doesn't load.  But I'm also curious to see how the Assets > Plantings page (and map) will behave with that many geometries.  We shall see!

> My goal is to see the farmer on the map with the data from the satellite with the RTK device, and know which planting is next to him, and add log records into these plantings.(activities,seedings etc.)

Great, so the correct way to do this is to use the map on the Assets > Plantings page.  This will show the geometries of all Planting assets.  You can use the "Geolocate" button to find your current location from a phone, and then you'll be able to click on the Planting points/polygons near that, which will show the Planting's name in a popup and allow you to open its record.  From there you can add logs to that Planting.  So that should work fine, once you get all your Areas changed to Plantings.

First, an important question: how long have you been using farmOS?  Have you just started, and importing the areas was your first step?  If so, can you start over?  Or will there be other things that you will lose by starting fresh?  The only reason I ask is: if you can start from scratch, then you don't have to worry about deleting the 29000 areas... which is one less step to take.

> Can I collectively register 29000 plantings from the assets section? the location of all of them is certain, if I save them from assets, can I enter their locations, of course?

Since you have so many, I think the best way to do it would be to write a custom Python script (using https://github.com/farmOS/farmOS.py) to programmatically create all the plantings.  The script would basically need to do the following:

- Read the KML file that you originally used in the Area Importer.
- Create a Planting asset.
- Create an Observation log that defines the location of that Planting asset.

So for each "seedling" you will need at least: 1 Planting asset and 1 Log to define where it is.  See this page for more information: https://farmos.org/guide/location/
