### ISSUE TITLE
Inventory reconciliation log feature

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS#287]
The farmOS inventory system is pretty great already - especially for short-lived or coarse-granularity inventory quantities. However, it appears that *all* inventory adjustments are relative to the running total of the inventory quantity for a given asset. For longer run inventories small systematic errors can build up in these running total calculations.

One thing that would be very useful would be to have a special kind of inventory adjustment log which sets a new inventory total for a given asset - ignoring any prior inventory history.

To give an example, we're using farmOS to track seed inventory for a small local seed bank. Each time seed is removed from the inventory for distribution or regeneration the inventory quantity is reduced. These are modelled as actions with negative inventory adjustments. Differences in scales, measurement technique, or rounding can add up over time - resulting in large discrepancies in the total amount of seed still in the collection. Ideally, we would be able to log a new observation with the total current weight for a given accession and have the inventory reset to that value - perhaps with some reporting on the error between the running total and the new total.

**Comment by mstenta** [comment]
Yes! This is something I thought about too while I was building the inventory module, but ultimately decided to defer on because it made the queries more complex.

In farmOS 2.0.x, I'm hoping to simplify the way the "current inventory" calculation works, so that it is not being performed on-the-fly.  This will make it easier to have logic like this.  Then, the question is: how should the UI work for this?  I think I may have documented some ideas for this in the past... I'll see if I can find them.

**Comment by mstenta** [comment]
Ah ha! Here it is... :-)

This comment in the original "Inventory" issue: https://www.drupal.org/project/farm/issues/2912091#comment-12275326

And the changes made to the description when I made that comment: https://www.drupal.org/node/2912091/revisions/view/10653302/10653399

I originally thought about having three fields on the Inventory Adjustments:

- Asset (entity reference) - to indicate which asset the inventory adjustment is being made to
- Value (fraction) - to define the amount of inventory adjustment
- Reset (boolean) - allows the asset's inventory to be reset to the value provided

Another idea was, instead of "Reset", we have a dropdown with three options:

- Increment
- Decrement
- Reset

If "Increment" was selected, the asset's inventory would be increased by the amount in "value". If "decrement", then it would be decreased.  And if "reset", the "value" would become the new total inventory level moving forward.

All of these ideas are on shifting sands right now in farmOS 2.0.x.  I'm working under the assumption now that they will be part of the "Quantity Measurement" field (I think I described to you in another issue).

**Comment by tangix** [comment]
A quick question on the Inventory - I'm on 1.2 and Inventor seems to be only for Animals. I'm trying to track my beekeeping business with farmos and would like to have externally purchased items (jars, labels etc) tracked with lot number (required for Swedish regulations). Is this possible?

**Comment by mstenta** [comment]
@tangix - That's correct, inventory is only enabled on Animal assets currently. See this issue for context and next steps: https://www.drupal.org/project/farm/issues/2916551

And this recent forum comment: https://farmos.discourse.group/t/farmos-to-record-fertilizer-use/83/7

**Comment by tangix** [comment]
@mstenta 
OK, thanks for clarifying. 

Side note: Too bad farmOS is based on Drupal, I have 20+ experience with PHP development using different frameworks but since I haven't touch Drupal nor understand the Drupal architecture I am a complete loss here :-(

**Comment by mstenta** [comment]
"Too bad farmOS is based on Drupal" or "Too bad you haven't touched Drupal"? ;-)

FWIW: We are in the process of upgrading from Drupal 7 to Drupal 8/9, which will be a major refactoring of the codebase to follow Drupal's transition to more standard OO architecture on top of Symfony. So while it will still have a lot of Drupal-specific learning curve to it, hopefully it will be a bit more approachable for developers with PHP experience.

**Comment by symbioquine** [comment]
Based on what I've seen of the quantity/inventory features in 2.x, I think this can be marked as resolved in favor of https://www.drupal.org/project/farm/issues/2991394 - https://git.drupalcode.org/project/farm/blob/738040dc73b3d5cb76819a047b814ce59f01cde4/docs/model/logic/inventory.md#L12-16
