### ISSUE TITLE
Provide/accept GeoJSON over API alongside Well-Known Text (WKT)

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#292]
I believe @mstenta and I first discussed this a while back, but it came up again in https://github.com/farmOS/farmOS-client/pull/350#issuecomment-632168066:

> Another thing to consider, which I believe we've discussed before, is switching over from WKT to only using GeoJSON in areas, movement geometries, etc. I suppose there is a tradeoff, in that a string is a simpler and lighter format to transmit and store, as opposed to a JSON object, but I think the payoff of having the geometry in a native object format, which doesn't require complex parsing logic in order to concatenate, rearrange or otherwise manipulate the geometries, is well worth it. It would have benefits throughout FK, and probably elsewhere, but in this particular use case, it would eliminate much of the complexity of option 2, so that we could just rely on one canonical source for area geometries, without incurring the duplicate AJAX requests and storage overhead _nor_ the complexity and dependencies of such parsing logic. Obviously, switching everything over from WKT to GeoJSON would require major refactoring, both on the server and in FK, but it may be worth bearing in mind here, if it's a goal we'd eventually like to reach.

And as @mstenta points out:

> It would be a very breaking change in the API, though, so maybe we don't actually get around to it until farmOS 2.0.x? Things to think about...

So yea, this a far-off request that will take time to consider and implement. Maybe worth flagging for 2.0 so it can be reassessed at that time.

**Comment by paul121** [comment]
The `geofield` field type we're using in farmOS 2.x outputs the geometry in multiple types: WKT, lat, lon, bbox (separate left, top, right and bottom values) and geohash. I imagine it would be possible to add another attribute here that is formatted for Geojson.

Example:

```json
...
"geometry": {
"value": "POLYGON((-70.09535368905976 43.82031711252753,-70.1016533660729 43.81260209737101,-70.09911037718686 43.810683614539386,-70.09130802492288 43.81848228034846,-70.09535368905976 43.82031711252753))",
"geojson": "... we could add this?",
"geo_type": "Polygon",
"lat": 43.81569322296154,
"lon": -70.09666680722152,
"left": -70.1016533660729,
"top": 43.82031711252753,
"right": -70.09130802492288,
"bottom": 43.810683614539386,
"geohash": "dry1",
"latlon": "43.815693222962,-70.096666807222"
},
...
```

**Comment by mstenta** [comment]
That could work @paul121 - it feels a bit weird to me, but I can't think of a better option.

The weird part is that the `value` will be WKT, rather than being called `wkt` (I don't think we should try to change this IMO because `value` is a standard across most other field types as well).

I wonder if this is something we should open as an upstream request in the Geofield module itself: https://www.drupal.org/project/issues/geofield

Perhaps there has already been discussion about this kind of feature request, and reasons for/against it or other considerations.

I could also see this being handled in the farmOS.py / farmOS.js layers, and NOT on the server. There are JS and Python libs available to convert to/from WKT/GeoJSON.

**Comment by wgardiner** [comment]
Adding geojson supoort would be nice!

**Comment by paul121** [comment]
FWIW we now have what are basically some API endpoints for getting geojson data out. If you use `/assets/geojson/full/{asset_type}` you get geojson for many assets of a given type. 

Recently I was also thinking we should add an `/asset/{id}/geojson` to get geojson for a single asset.

Both of these would be separate from JSON:API though. I'm not sure what would be the best way to add this in a JSON:API friendly way. We could add a computed `geojson` field to assets that returns the geometry as geojson instead of WKT, but computing this on the fly for every request would prob be a performance issue. Caching the wkt->geojson somewhere would be idea, similar to how the `geofield` pulls out lat, lon & bbox as separate columns in the DB as I mentioned above. I'm not sure how easy it would be to add a `geojson` column to the `geofield` field type's SQL table.

**Comment by symbioquine** [comment]
Instead of inventing a new API style for this, we could us my [farmOS_wfs module](https://github.com/symbioquine/farmOS_wfs). I'd be happy to review/accept pull requests (maybe even help with writing) that support the GeoJSON format according to the more recent WFS/OGC specs. http://docs.opengeospatial.org/is/17-069r3/17-069r3.html

**Comment by symbioquine** [comment]
farmOS_wfs already supports bounding-box queries btw :)

**Comment by paul121** [comment]
Thanks @symbioquine, absolutely. Would the more recent WFS/OGC help with querying & returning certain attributes along with the GeoJSON as well? That is one of the gripes I have about our current GeoJSON endpoints, the attributes returned with each feature are hard-coded and filter options are limited.

It seems like WFS/OGC would provide more of JSON:API's features but return in GeoJSON instead. This would be great.

**Comment by symbioquine** [comment]
> Would the more recent WFS/OGC help with querying & returning certain attributes along with the GeoJSON as well? That is one of the gripes I have about our current GeoJSON endpoints, the attributes returned with each feature are hard-coded and filter options are limited.

The way farmOS_wfs is implemented currently it uses the Drupal PHP apis internally to dynamically find all the fields for a given (asset) entity and expose them as fields via the WFS api. This means that even bundle fields from contrib modules are available in queries.

> It seems like WFS/OGC would provide more of JSON:API's features but return in GeoJSON instead. This would be great.

Yeah, there's a fair bit of overlap in terms of the functionalty provided by `WFS` and `JSON:API`, but I think that's okay. JSON:API's mandate is to provide a 1:1 representation of the entities in Drupal whereas farmOS_wfs' mandate is to provide a representation of the assets (maybe logs in future) in a farmOS instance - in a way that is consumable for mapping/geographical purposes.

**Comment by mstenta** [comment]
This came up again in some recent OpenTEAM discussions in GitLab (https://gitlab.com/our-sci/software/json_schema_distribution/-/issues/64) and in Matrix.org chat (https://matrix.to/#/!jnoyZQGWvNoTUmWlIQ:matrix.org/$lAGCO25Tjl12T9C4Pp24GhFWM3xfDEh7zRX1Msxy-Oc?via=matrix.org). It reminded me of this old GitHub issue.

With this recent discussion, it made me realize a potentially big hurdle to supporting GeoJSON via the farmOS API. GeoJSON is not just geometry. It can contain other data. Which leads to the question that came up in chat:

> If someone `POST`s GeoJSON to the API which contains extra data, what do we do with that?

GeoJSON would need to be converted to WKT/WKB before it's stored in the farmOS database, so any "extra" data or structure that is embedded in it would be lost. As an API user, this would *not* be my expectation, and there isn't really a good way to make that limitation clear (maybe in JSON Schema, but users may not look there).

Another option would be to just make the GeoJSON read-only. But I don't really see any significant benefit in doing this. It's just more overhead for us to maintain in farmOS core, because it requires altering the Geofield module's default behavior.

I'm inclined to close this as "won't fix", and leave GeoJSON conversion to third-party tools that need it. Open to discussion on this, of course! But that's my current thinking...
