### ISSUE TITLE
Cannot autocreate term by name if the field is not a list

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#294]
I believe this commit de736afad10728615b9ad73dd20321f6163dab55 introduced this bug.

I was trying to create an animal asset and reference the `animal_type` directly with the term `name` rather than term `id`:

```python
    asset = {
        'name': f"Cow #{i}",
        'type': 'animal',
        'animal_type': {'name': 'cow'}
    }
```

At first I wasn't sure if the "autocreate term by name [feature](https://www.drupal.org/project/farm/issues/3134067)" was specific to only logs, and not assets....  but seems like it should work for assets too?

It seems like the commit that removed the check for `$field_values[0]` would break autocreating terms by `name` for any field that *does not* accept a list of taxonomy terms. In that context, `$field_values` IS an array, but is indexed by key (`name` in this case) rather than an index (`[0]`).

I wanted to try this out by creating a log via API, rather than an asset, but I'm not sure if there is a field for logs that ONLY accepts a single term... is that correct?

**Comment by paul121** [comment]
I've attempted to fix with this PR #295 

I'm curious if there might be a better way to structure that block of code in general, but this seems to work and avoids the PHP "undefined offset" message.

With that, I'm able to submit the above `asset` and the following `log` that both auto-create terms by `name`: (this still doesn't test a log with a field accepting only 1 term, nor does it answer the question of where that original PHP notice may have been coming from....?)

```python
        log = {
            'name': log_name,
            'type': log_type,
            'asset': [{'id': asset}],
            'quantity': quantity,
            'timestamp': loop_date.strftime("%s"),
            'log_category': [
                {'name': 'animal_weight_test'},
            ],
            'done': 1
        }
```

**Comment by mstenta** [comment]
Oops! Good catch @paul121 !

That was a dumb mistake on my part. I was seeing the PHP Notice, and then when I reviewed that line I mistakenly thought that the `[0]` was wrong, when in fact it was correct (though not great).  So I inadvertently broke exactly what that line was there to do in the first place. And then since I converted Seasons to a multi-value field (which was originally why I added that logic in the first place), I didn't test it again.  Serves me right for making last minute changes like that before packaging 7.x-1.4. :-)

> At first I wasn't sure if the "autocreate term by name feature" was specific to only logs, and not assets.... but seems like it should work for assets too?

Yes! In theory this should work for ANY entity type in the system (logs, assets, or anything else for that matter).

> I wanted to try this out by creating a log via API, rather than an asset, but I'm not sure if there is a field for logs that ONLY accepts a single term... is that correct?

I think that's true - the number of term reference fields that only accept one value is pretty limited, and I think may only be on assets at this point.  I'd have to double-check that, but I think it's true.  In either case, we want this code to work in both single-value and multi-value contexts.

> In that context, `$field_values` IS an array, but is indexed by key (`name` in this case) rather than an index (`[0]`).

This is a really good point...

I think your solution to add an `isset($field_values[0])` check to prevent the PHP Notice makes sense.

However, we might be able to simplify it even further...

Instead of:

```php
if (!isset($field_values[0]) || !is_array($field_values[0])) {
```

I think we can just do

```php
if (isset($field_values['name'])) {
```

This explicitly checks to see if the `name` key is set on the `$field_values` array. If it is, then I think it's safe to assume that we're working with a "single" value term reference field, which is ultimately what we're trying to isolate.

What do you think?  Does that make sense?

**Comment by paul121** [comment]
> ```php
> if (isset($field_values['name'])) {
>```

Aha! Yeah, good idea. That is much more readable.

I'll try and update that PR tomorrow unless you get to it before hand 👍

**Comment by paul121** [comment]
@mstenta just updated https://github.com/farmOS/farmOS/pull/295 to check for the `name` key. Seems to be working as we thought it might :+1:

**Comment by mstenta** [comment]
Thanks Paul! Looks good! Merging now.
