### ISSUE TITLE
include area units in area API

### ISSUE THREAD

**Issue by gbathree** [farmOS/farmOS#326]
We currently pull the areas via the farmOS API both directly, and as represented when pulling individual plantings in the `location` object.  See below:

```

    "farmos_planting": {
      "value": {
        "farmName": "Our Sci Test Farm",
        "url": "ourscitest.farmos.net",
        "name": "beet 4/1/20",
        "assetId": "575",
        "location": [
          {
            "uri": "https://ourscitest.farmos.net/taxonomy_term/8",
            "id": "8",
            "resource": "taxonomy_term",
            "name": "Field A"
          }
        ],
        "farmId": "7",
        "hash": "ASSET:7.575"
      },
      "meta": {
        "type": "farmOsPlanting",
        "dateModified": "2020-07-18T16:05:00.505-04:00"
      }
    },
```

Because we need to modify user inputted values for applications or harvests so they are comparable, we often need the field area (calculate lbs/acre from user inputting lbs).  If possible, include the area within the field in the api call for `location` within planting.  

@mstenta

**Comment by mstenta** [comment]
Thanks for opening this @gbathree - couple of thoughts...

First, it's relatively easy to add a new property to the root JSON for areas and assets in the API. We are doing that already to add "Location" to assets (as you mentioned). That is happening via `hook_entity_property_info_alter()`, eg: https://github.com/farmOS/farmOS/blob/e5423ac61586a2ae6f04975660a7c4509b48461e/modules/farm/farm_movement/farm_movement.module#L19

And, we have PHP functions already for calculating the area/length of polygons/lines, so we can use that.

These functions return area/length float values in meters squared/meters, respectively, without any units attached. We also have a function that we can use to return a "formatted" measurement, which would look at the default system of measurements (metric or imperial) in the farmOS settings, and return a string that includes the units on the end (eg: "**40 acres**" instead of "**161874.4**" square meters). However, this formatting function also does some clever stuff to use "sq.ft" instead of "acres" if it's a "small" area (less than a quarter acre, I believe). So I'm wondering if maybe we should ONLY include the meters/sq.meters measurement, and leave it up to the API user to convert it to the units they want.  This would be the most flexible, and easiest from my perspective. Would that work for you, @gbathree ?

It's simple enough to add these measurement to "Area" records.  However, adding them to the "Planting" record, as you described, is a bit trickier.  Although I think we would need to do this, because otherwise you would only be able to get the "Area" measurements and not the "actual" measurements of asset location (assets can occupy a more specific geometry within an area). So for that, I would have to look into adding the measurement to the existing `location` property in your example above, which is a bit more complex.

It also makes me wonder if we should add these measurements to Log records as well, because they store their own geometries too, and that could be useful to ask "how many square meters was this input applied to?"

It's also worth noting: we are NOT using these PHP functions to calculate the area/length that is displayed in the frontend maps in farmOS. This is using OpenLayers logic. So there is a chance that the different PHP and JS logic will produce slightly different areas/lengths (calculating the area of a polygon drawn with lat/lon points is more complicated than you'd think! the world is not a perfect sphere, and elevations differ, etc - so I won't be surprised if we see slight differences).

Also also note: the functions for calculating these measurements currently ONLY work on simple Polygon/LineString geometries. They will not work on GeometryCollections (which are compound geometries with multiple shapes), and that includes Polygons with a hole cut out of them.  If that's needed, we can expand the logic, but that should be a separate issue.

**Comment by mstenta** [comment]
Also a reminder to self to document this in farmOS.org when we add it.

**Comment by gbathree** [comment]
Thanks!  I'm going to ask some more questions thursday and put the notes here, I think there's more we should be doing that you're already doing well.

**Comment by mstenta** [comment]
Closing old/stale GitHub issues. The considerations for this have changed since farmOS v2. If there's still interest in this let's open a new forum topic to discuss first, and then create PR(s) to consider actual changes.
