### ISSUE TITLE
Animal asset Map Labels

### ISSUE THREAD

**Issue by blueskyted** [farmOS/farmOS#327]
I have added my cattle and sheep in mobs using records representing multiple animals using inventory. The map does not show an inventory count for each mob - instead it is showing how many records are located in each paddock. I gather this is a bug.

![image](https://user-images.githubusercontent.com/42083036/87893272-c7828380-ca82-11ea-87db-214c30f60b68.png)
As my animals are grouped into mobs, the Metrics are pretty meaningless for me. I suppose that Metric>Animals means 6 animal asset records exist, however in reality it records an inventory of several hundred cattle and sheep. metrics should be taking into account inventory.
![image](https://user-images.githubusercontent.com/42083036/87893308-dcf7ad80-ca82-11ea-8761-67587ea0d860.png)

**Comment by mstenta** [comment]
Hmm I looked into this and it turned out to be more complicated than I thought. I'll try to summarize so that we can pick it up again later...

First, the "map icons" and "metrics" are two separate things, and so they need to be addressed separately.

The map icons may not be possible, at least not without refactoring the way that they are created. We don't actually create the icons ourselves and put a specific number in there. All we are doing is providing a GeoJSON array of points that represent the location of individual animal assets. Then, OpenLayers "clusters" those points together and puts a number on it to represent how many points are "clustered" together. You'll notice that if you zoom in, the cluster breaks apart (so a single "3" icon will separate into three "1" icons). We don't have control over the number that is displayed in the cluster icon itself, nor should we change it, in my opinion, because it would make the "clustering" behavior more confusing. So the only other option might be to rethink clustering entirely. :-/

The metrics are a little more approachable, but also complicated. Currently we have a function that will take a single asset and return it's current inventory. But we don't have a function that gives us the TOTAL inventory of all assets of a given type.  The database query for getting an individual asset's inventory is rather complicated.  It might require some refactoring to generalize that query so it can be reused for this.

**Comment by symbioquine** [comment]
> The map icons may not be possible, at least not without refactoring the way that they are created. We don't actually create the icons ourselves and put a specific number in there. All we are doing is providing a GeoJSON array of points that represent the location of individual animal assets. Then, OpenLayers "clusters" those points together and puts a number on it to represent how many points are "clustered" together. You'll notice that if you zoom in, the cluster breaks apart (so a single "3" icon will separate into three "1" icons). We don't have control over the number that is displayed in the cluster icon itself, nor should we change it, in my opinion, because it would make the "clustering" behavior more confusing. So the only other option might be to rethink clustering entirely. :-/

I haven't tried it yet, but I think this should be fairly easily accomplished by ensuring the relevant inventory attribute is present in the GeoJSON, then providing a custom label function which sums that inventory attribute for all features in the cluster. See https://gis.stackexchange.com/questions/98299/labelling-cluster-features-in-openlayers

**Comment by guillermo-farmos** [comment]
Hi to all, 

Any progress with mob labels representing the current mob tally?

Also, about label color, I find useful identifying animal species by colors, for example
   blue --> cattle
   green --> sheep
   orange --> deer
   grey --> horse
   yellow --> beehives
etc.

Color brings instant understanding of mob type location on the map, which is very useful for a busy farmer that shifts mobs several times a day (my case)

Cheers

**Comment by mstenta** [comment]
Hi @buihug - thanks for raising this issue again. I forgot about it. :-)

This was originally opened for farmOS v1, and many of the considerations have changed since farmOS v2 was released. I'd love to give them some fresh thought.

In the meantime, we have also moved "discussions" like this to the farmOS community forum (https://farmOS.discourse.group), and we try to limit GitHub to very specific/targeted bug reports and pull requests. With that in mind, I'd like to suggest that we close this issue and start a new forum topic to discuss these ideas more broadly. We can link to this issue for historical context.

Would you mind starting a new forum topic @buihug? Feel free to copy/paste some of your previous comment.

**Comment by paul121** [comment]
I think there was already a forum topic opened for this ;-) https://farmos.discourse.group/t/animal-asset-map-labels/422

**Comment by mstenta** [comment]
Ah right! Thanks @paul121 - and apologies for the back and forth between forum and GitHub @blueskyted - we're still figuring out how to organize all this stuff. :sweat_smile:

**Comment by guillermo-farmos** [comment]
Thanks @paul121 & @mstenta

Then, I suggest somebody deletes posts 2, 3 & 4 from [farmos topic 422](https://farmos.discourse.group/t/animal-asset-map-labels/422), which leads one to here :)

Also, if this thread is closed, why is that I am able to write a comment here? It is a bit confusing. Could it be set to read only?

**Comment by mstenta** [comment]
> Also, if this thread is closed, why is that I am able to write a comment here? It is a bit confusing. Could it be set to read only?

Yea I'm not "locking" the issues... just trying to encourage everyone to use the forum. :-)
