### ISSUE TITLE
Ability to transfer inventory across multiple locations

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#357]
In the early stages of planning some inventory features for a farm client next growing season.

The farm has materials (chemicals, fertilizers, etc) stored in a few different locations. They will sometimes transfer inventory of the same material from one location to another. It would be great if the future inventory system could support this. I'm assuming this could be implemented in a custom form that increments the inventory of one material asset, and decrements another. But perhaps there is more complexity to think about?

Requirements that come to mind:
1. Material needs to be "moveable"; be able to assign this asset a location
2. Interface to transfer inventory between two assets of the same material type
3. Handle different units? Auto-convert? Prompt the user to do a conversion?

**Comment by mstenta** [comment]
All of this will be possible on our current trajectory!

> Material needs to be "moveable"; be able to assign this asset a location

farmOS 1.x already has inventory tracking for assets, but it is only enabled on the Animal asset type (for head counts). In 2.x the plan is to enable it on more types, and maybe add some new ones for specific material tracking purposes. Imagine having a "Seed" asset type, with an asset for each type of seed. Each asset can have a location, so you might call one asset "Corn seed stored in the East Barn" and one "Corn seed stored in the West Barn". Inventory adjustments are used to increment/decrement their inventory levels, so you could have a log "Transfer corn seed from East to West Barn", with two inventory adjustments: one that decrements the inventory of "Corn seed stored in East Barn" and one that increments "Corn seed stored in West Barn". And because they are assets, you could also just move the whole thing without touching inventory.

That covers the basic data architecture... which then leads to your next point (about making it easy to use)...

> Interface to transfer inventory between two assets of the same material type

I can imagine various quick/helper forms for common tasks like this, which simplify the process of creating logs with inventory adjustments on them. We might want other things like a harvest quick form that archives a planting and automatically creates/increments inventory of a product asset that is ready to sell. Or in the future perhaps some features that track inventory of product as it is packed into boxes that are shipped to wholesale accounts. Lots of possibilities!

In general, "inventory management" is just a more granular tracking mechanism - which means more data entry. So there will need to be helper forms like these to make it truly usable/useful IMO.

> Handle different units? Auto-convert? Prompt the user to do a conversion?

This is where things get tricky. ;-)

Have you seen these?

- https://www.drupal.org/project/farm/issues/2916551
- https://www.drupal.org/project/farm/issues/2361915

There are definite possibilities to automate unit conversions, but in the meantime a simpler approach is to just use consistent units internally.

The inventory adjustments will not have any strict checks on them to ensure a balanced transaction (like double-entry bookkeeping does), so it would be possible for you to create a log that says "decrement asset 1 by 16 ounces, and increment asset 2 by 1 pound". It will also mean you can potentially track inventory in different units on the SAME asset. My (current) thinking there is: the "current inventory" of an asset will be the SUM of all adjustments of a particular "unit term". So an asset may actually have multiple "current inventories". Obviously that might not make sense to anyone in practice, hence why the recommendation is to always use consistent units on a particular asset. But by allowing that, it will allow us to sidestep the need to enforce unit consistency / convert units for a single asset.

These are still brainstorms at this point, and just where I am currently leaning, with regard to inventory units handling. The issue I linked to above may be a bit outdated in that regard. I'd love to hear more thoughts and critiques of these ideas before we truly start down the path!

**Comment by tangix** [comment]
As a beekeeper, add me to the list of interested parties. We need to track and trace supplies such as jars and chemicals. Today we do that in Excel outside of farmOS...

**Comment by mstenta** [comment]
Cleaning up old issues... Closing this and https://www.drupal.org/project/farm/issues/2916551.

farmOS 2.x has a new inventory tracking system that may cover most of this. We can open new issues/discussions in the forum if necessary.
