### ISSUE TITLE
remove map

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#363]
Do I have a chance to remove the map from this screen? (farm/area/1 page)

![Ekran Alıntısı00009](https://user-images.githubusercontent.com/61236746/97577804-f3f25800-1a00-11eb-8297-81a4ba0311e2.JPG)

**Comment by mstenta** [comment]
Do you want to remove that map from ALL area pages? Or just some?

**Comment by compact24** [comment]
No I just want to remove it from this screen. 
Do we have a chance to remove all pages?

**Comment by mstenta** [comment]
The map will only display on `/farm/area/%` pages if the area has a geometry. Otherwise the map will not show.

> Do we have a chance to remove all pages?

I'm not sure what you mean.

**Comment by compact24** [comment]
> The map will only display on pages if the area has a geometry. Otherwise the map will not show.`/farm/area/%`


Do we have a chance to remove or hide it even in geometry?

**Comment by mstenta** [comment]
Anything is possible! Just a matter of how deep you want to go with overriding/altering farmOS. :-)

But out-of-the-box farmOS will always show that map on area pages.

Can you describe a little more what you want to achieve overall so I can understand and maybe give better recommendations?

**Comment by compact24** [comment]
I entered the coordinates of our plants on the map, about 25,000. 
Therefore, when loading the map, the page is very tight. I thought if I remove the map, the page will open faster so I want to remove the map.

**Comment by mstenta** [comment]
> Therefore, when loading the map, the page is very tight. I thought if I remove the map, the page will open faster so I want to remove the map.

If you put this into a custom module and clear your cache it will display the WKT geometry instead of the map on all area pages:

```
/**
 * Implements hook_field_display_ENTITY_TYPE_alter().
 */
function mymodule_field_display_taxonomy_term_alter(&$display, $context) {
  if ($context['view_mode'] == 'full') {
    if ($context['instance']['field_name'] == 'field_farm_geofield') {
      $display['label'] = 'inline';
      $display['module'] = 'geofield';
      $display['type'] = 'geofield_wkt';
      $display['settings'] = array('data' => 'full');
    }
  }
}
```

(Replace `mymodule` with the name of your custom module. And you will need to clear cache for it to be picked up.)

Hope that helps!

> I entered the coordinates of our plants on the map, about 25,000.

As an aside, I don't think you should enter your plants as "Areas" in farmOS - ideally they should be Planting assets. The "Areas" should only be for "places".

Your Planting assets can be located IN Areas, and can also define a more specific geometry (single point per planting, if that's what you want). See: https://farmos.org/guide/location/

**Comment by compact24** [comment]
I tried the code, it did not do exactly what I wanted, or rather it gave an error. 
Can I just remove the map from the page above (/farm/area/%) even if it has any geometry?

**Comment by mstenta** [comment]
What error did you see?

That code is the best way to remove the map from the area page.

**Comment by compact24** [comment]
![311](https://user-images.githubusercontent.com/61236746/97961418-58783300-1dc4-11eb-898f-fa5f931f2564.JPG)
![312](https://user-images.githubusercontent.com/61236746/97961442-6463f500-1dc4-11eb-881a-a7e97c3b64d8.JPG)
![313](https://user-images.githubusercontent.com/61236746/97961462-6a59d600-1dc4-11eb-95c2-2cfde41b1c12.JPG)


![Ekran Alıntısı8999](https://user-images.githubusercontent.com/61236746/97961048-9b85d680-1dc3-11eb-87f2-968b18be7ccc.JPG)

I am getting an error like on the screen. For example, the map on the Dashboard screen is not loaded. Also, this affects every page, just isn't there a way to remove the map on the page I specified (/farm/area/%)?

**Comment by mstenta** [comment]
Thanks! Seeing that helps!

You need to add the following at the top of your module file:

```
<?php
```

This tells Apache that the file is PHP code and should be interpreted as such. Otherwise it will just print the code to the page, like you are seeing on all of your pages right now.

**Comment by compact24** [comment]
Yes, it removed the map from the screen, thanks. But in the background, I think it continues to load the fields. That's why the page is a little late to open. Do I have a chance to do anything to prevent this?

**Comment by mstenta** [comment]
Great!

> But in the background, I think it continues to load the fields. That's why the page is a little late to open.

It's true that the field data will still be loaded, but the map is not. The field data is just text - it will not affect the page load time. So something else might be slowing you down.

Do you see the same delay on other pages (specifically pages without maps)?

**Comment by compact24** [comment]
![78](https://user-images.githubusercontent.com/61236746/97991116-0b12ba80-1df2-11eb-8367-01b2a9954f8e.JPG)

While the view page opens slowly, the edit page opens normally. I could not understand why.

Is there any way to resolve this situation?

**Comment by compact24** [comment]
We have 2 setups like in the example. 1 of them the page opens very fast while the other is slow. Could it be because of the asset part or something else working in the back?

![4](https://user-images.githubusercontent.com/61236746/98123183-92c7fa00-1ec2-11eb-960b-b784fd92e306.JPG)


![5](https://user-images.githubusercontent.com/61236746/98123195-96f41780-1ec2-11eb-818e-2642145796f6.JPG)

**Comment by mstenta** [comment]
Does the slower one have more Logs associated with it?

**Comment by mstenta** [comment]
Can you define "slow"? How many seconds fast vs slow?

**Comment by compact24** [comment]
Actually there is no difference, the same number of records. It takes 25 seconds to open. the other opens immediately.

Could it be due to existence history? If I remove it, is there any chance it will speed up?

**Comment by mstenta** [comment]
25 seconds is a LOT!

Going back to your original suspicion: how big is the geometry data in each? Is the slow one HUGE? Maybe a lot bigger than I'm imagining?

**Comment by compact24** [comment]
There are 26000 points in the fields section, which is already a problem when loading them. My aim on this page is to open the page without loading them.

**Comment by mstenta** [comment]
> I entered the coordinates of our plants on the map, about 25,000.

Ah yes you already mentioned this...

I'm not sure what we can do about loading the data. Geometry is a field on the entity, so Drupal is going to load it in many contexts.

I think the real issue is that a single area shouldn't be storing that much data. It should be broken up - I mentioned above:

> As an aside, I don't think you should enter your plants as "Areas" in farmOS - ideally they should be Planting assets. The "Areas" should only be for "places".
> 
> Your Planting assets can be located IN Areas, and can also define a more specific geometry (single point per planting, if that's what you want). See: https://farmos.org/guide/location/

But... it may just be kicking the problem elsewhere.

Do you experience extremely slow loading of those points on the dashboard map as well?

> Could it be due to existence history? If I remove it, is there any chance it will speed up?

What do you mean by "existence history"?

**Comment by compact24** [comment]
Removing the map was not the solution. Is removing the asset side the solution?

![4](https://user-images.githubusercontent.com/61236746/98127993-6616e100-1ec8-11eb-9df6-547b6dcdd05e.JPG)

For example, this page does not have a bottom section, so I install it very quickly on the other page.
farm/area/%

Or can I prevent areas from loading on this page?

Where does it load areas when loading this page? What is slowing down the page?

Is there any way to speed up the page?

**Comment by compact24** [comment]
> What do you mean by "existence history"?

I typed wrong. I was going to say can I remove the asset history from this page?

**Comment by compact24** [comment]
> As an aside, I don't think you should enter your plants as "Areas" in farmOS - ideally they should be Planting assets. The "Areas" should only be for "places".
> 
> Your Planting assets can be located IN Areas, and can also define a more specific geometry (single point per planting, if that's what you want). See: https://farmos.org/guide/location/

I have no chance to use the asset part. I do not enter the saplings one by one, I transfer them collectively from the fields (area importer). 
Also, the location of the saplings comes to me as kml file. the coordinates of all of them are clear, I do not enter manually. On farmos, I can only do this from the fields. only one already causes trouble on that page (farm/area/%), the rest is working. If I could speed up that page a little bit, I think my problem will be solved.

**Comment by mstenta** [comment]
@compact24 This may be outside the scope of the kind of support I can provide. Putting tens of thousands of points in a single area geometry is not really the designed use case for farmOS - so it's not surprising that it causes performance issues. There may be ways to optimize, but I really feel that this data should be split up somehow. The solutions we've been talking about are essentially hacking out core features of farmOS to make this work for you - which I fear is the wrong path to go down. I'm not sure if I have a better solution.

One final idea you can consider: Change the Area geometry from a set of 26,000 points to a single polygon geometry that encompasses all of them, create a single Planting asset that represents all your saplings, with a location of the Area. Then edit that asset's movement log and upload the KML file and import the points to the log geometry.

This will essentially move all of the points to the asset level, and leave the area as a simple boundary on the map. When you look at the map on the dashboard you will see the boundary, and when you look at the map on /farm/assets/plantings, you will see the individual points. However, this may just be moving the problem... it may still take a while to load the /farm/assets/plantings map, and the movement log for that asset itself, in the same way that the area page is behaving now. But, perhaps that's better because you may be accessing the area page more frequently, so that would load fast.

That's probably the best advice I can give, given all the considerations here. I hope it helps and makes sense!
