### ISSUE TITLE
Add new base layers

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#373]
I want to add my own base layers to the map on the dashboard screen. I tried the example you gave. Layer has arrived, but how can I do it as a radio button and it always remains selected, how can I remove it? 

![12345](https://user-images.githubusercontent.com/61236746/99542417-199ccc80-29c3-11eb-9443-bad21bbe6dff.JPG)

**Comment by mstenta** [comment]
There is a `base: true` setting that makes it a radio button. Can you share some code? I might be able to tell you where to put it.

**Comment by compact24** [comment]
https://github.com/farmOS/farm_map_no

I used the same codes here, just changed the url address.

**Comment by mstenta** [comment]
Ah OK - I think the reason that one is not set as a base layer is because it does not cover the whole world - just Norway. So without a whole-world underneath it you would see blank map outside of the Norway region.

But I think it would just require `base: true` added to the layer config. See the example in this section:

https://github.com/farmOS/farmOS-map#attribution

**Comment by compact24** [comment]
Yes it is. turned to radio button thanks.
