### ISSUE TITLE
Add openStreetMaps layer(s)

### ISSUE THREAD

**Issue by cavebeat** [farmOS/farmOS#39]
If openStreetmaps could be used additionally or instead of GoogleMaps this could also help to use it as an airGapped-non-internet appliance, as described in https://github.com/farmOS/farmOS/issues/37

I am sure, it's possible and encouraged allowed to download and use the data from openStreetMaps locally. 

I do not know how googleMaps offers the layer compared to OSM... and what's needed to offer them also the same way... 

but it's an option possibly

**Comment by mstenta** [comment]
Agreed! It actually wouldn't be too hard to make OpenStreetMaps an option in addition to Google Maps.

I would recommend looking at these two modules, which add Norwegian and Finnish mapping layers to farmOS:

https://github.com/farmOS/farm_map_no

https://github.com/rkioski/farm_map_fi

I wrote the farm_map_no module, and the farm_map_fi module was based off of that I believe.

If I remember correctly, it alters the layers in the default farmOS maps so that the new layers appear over the Google Maps ones.  It would also be possible to write an alter hook that disables the Google layers entirely.

For the time being, we do need to keep Google Maps, because they seem to be the best freely-available satellite images in the United States - not perfect everywhere, but the best overall I've found.

The modules above are sort of just little temporary hacky solutions - ultimately I'd like to see a more robust way for farmOS to offer different layer options.  The underlying Openlayers module provides a LOT of flexibility, but if you aren't familiar with it it can be very hard to use. So it would be nice to provide some simplified UI in farmOS that let's you configure things. I started a feature request along these lines a while back, but haven't gotten around to it yet: https://www.drupal.org/node/2772955

There are a few other related issues you might want to take a look at on drupal.org, organized into the "Farm Maps" component: https://www.drupal.org/project/issues/farm?component=Farm+Maps

**Comment by mstenta** [comment]
I added an issue for this to drupal.org, so I can link to it in the roadmap: https://www.drupal.org/node/2906648

**Comment by mstenta** [comment]
I added and OpenStreetMap base layer to farmOS.

See https://www.drupal.org/node/2906648#comment-12246397

**Comment by flaviomx14** [comment]
Hello all,

How to update this module?

Thanks!

**Comment by mstenta** [comment]
@flaviomx14 There are instructions for updating farmOS here: http://farmos.org/hosting/updating/

It is basically the same process as updating Drupal, so if you are not familiar with that, here are the general Drupal updating instructions: https://www.drupal.org/node/1223018

**Comment by flaviomx14** [comment]
Thank you!  my update is ok, but how show to openlayer on farmos?
Sorryi am new in farm OS.

**Comment by mstenta** [comment]
Oh! Ok... so if you are looking at your map, you should see an icon in the top right for layers. If you hover over that, it will show the layers that are currently displayed... and you should see a section for "Base layers" with Google Maps and Open Street Map.

You can toggle to view Open Street Maps there. But... that will only be temporary. Once you reload the page or go to another page, it will go back the default of Google Maps.

If you want to make Open Street Maps the default, there is a setting for that in /admin/config/farm/map.  You can toggle it there and it will change it permanently.

Hope that helps!

**Comment by flaviomx14** [comment]
ok Michel,

Thank you very much!


FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 18 de out de 2017, à(s) 10:37, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


Oh! Ok... so if you are looking at your map, you should see an icon in the top right for layers. If you hover over that, it will show the layers that are currently displayed... and you should see a section for "Base layers" with Google Maps and Open Street Map.

You can toggle to view Open Street Maps there. But... that will only be temporary. Once you reload the page or go to another page, it will go back the default of Google Maps.

If you want to make Open Street Maps the default, there is a setting for that in /admin/config/farm/map. You can toggle it there and it will change it permanently.

Hope that helps!

**Comment by flaviomx14** [comment]
Hello Michael, how are you?!

I have installed a new version of farmOs today.
But i have some problem. The map dont show and i make update of the system but i found this error:
Can you help me?
[cid:6E91913A-0430-4800-8952-2C0836E4A641]



FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 18 de out de 2017, à(s) 10:24, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


@flaviomx14<https://github.com/flaviomx14> There are instructions for updating farmOS here: http://farmos.org/hosting/updating/

It is basically the same process as updating Drupal, so if you are not familiar with that, here are the general Drupal updating instructions: https://www.drupal.org/node/1223018

**Comment by mstenta** [comment]
@flaviomx14 What error did you see?

**Comment by flaviomx14** [comment]
Did you see the picture?


This is one of error:

Unresolved dependency    elements (missing)
Farm Area require this module


FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 15 de fev de 2018, à(s) 15:33, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


@flaviomx14<https://github.com/flaviomx14> What error did you see?

**Comment by mstenta** [comment]
No there is no picture attached. (Note that this is posted to https://github.com/farmOS/farmOS/issues/39, which may not receive email attachments.)

But the "Unresolved dependency    elements" gives me a good clue.

farmOS uses a patched version of the Openlayers module. Did you try to update the Openlayers module? That would not have the necessary patches to it.

Always use the farmOS code that is packaged on drupal.org/project/farm - this will include all the dependencies and patches that are required.

**Comment by flaviomx14** [comment]
Yes i have update all modules in farmOS.


Always use the farmOS code that is packaged on drupal.org/project/farm<http://drupal.org/project/farm> - this will include all the dependencies and patches that are required.

Yes I download from there.

FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 15 de fev de 2018, à(s) 15:38, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


No there is no picture attached. (Note that this is posted to #39<https://github.com/farmOS/farmOS/issues/39>, which may not receive email attachments.)

But the "Unresolved dependency elements" gives me a good clue.

farmOS uses a patched version of the Openlayers module. Did you try to update the Openlayers module? That would not have the necessary patches to it.

Always use the farmOS code that is packaged on drupal.org/project/farm<http://drupal.org/project/farm> - this will include all the dependencies and patches that are required.

**Comment by mstenta** [comment]
> Yes i have update all modules in farmOS.

How did you update the modules? Did you download Openlayers from https://www.drupal.org/project/openlayers?

If so, that will not include the necessary patches to the module.

**Comment by flaviomx14** [comment]
I Have update into Drupal webpage administrator.

Modules >> Atualization


FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 15 de fev de 2018, à(s) 15:45, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


Yes i have update all modules in farmOS.

How did you update the modules? Did you download Openlayers from https://www.drupal.org/project/openlayers?

If so, that will not include the necessary patches to the module.

**Comment by flaviomx14** [comment]
When I do a new installation I need to download the Openlayers separately or it already comes with the Farmos package?


FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 15 de fev de 2018, à(s) 15:45, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


Yes i have update all modules in farmOS.

How did you update the modules? Did you download Openlayers from https://www.drupal.org/project/openlayers?

If so, that will not include the necessary patches to the module.

**Comment by mstenta** [comment]
> I Have update into Drupal webpage administrator.
> Modules >> Atualization

Unfortunately, that method (which comes with Drupal), does not work for updating all of the components of farmOS.  This is because farmOS is a Drupal Distribution, so it has some more specific update requirements.

The update instructions are available on farmOS.org here: http://farmos.org/hosting/updating/

> When I do a new installation I need to download the Openlayers separately or it already comes with the Farmos package?

When you do a new farmOS installation, all you need to do is download the ZIP or TAR.GZ file from http://drupal.org/project/farm - and that will contain all the modules you need (including Openlayers). It will also include all the necessary patches that are applied to those modules.

When you UPDATE a farmOS installation, you will basically do the same thing: download the packaged ZIP or TAR.GZ file. That will include all the module updates as well.

If you download any modules separately, or if you use Drupal's built-in updater, they will NOT have the necessary patches. So it is always recommended that you follow the update instructions on farmOS.org here: http://farmos.org/hosting/updating/

I should add a note to that page that the built-in Drupal module updater should not be used.

**Comment by mstenta** [comment]
I added a todo to the farmOS.org documentation to make note of that: https://github.com/farmOS/farmOS.org/issues/25

**Comment by flaviomx14** [comment]
Hello,

Form me install a new module like farm_map_fi_master to test, I can do it through the admin website?

att.

FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 15 de fev de 2018, à(s) 16:29, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


I added a todo to the farmOS.org<http://farmOS.org> documentation to make note of that: farmOS/farmOS.org#25<https://github.com/farmOS/farmOS.org/issues/25>

**Comment by mstenta** [comment]
See https://github.com/farmOS/farmOS/issues/52

**Comment by flaviomx14** [comment]
THANK YOU VERY MUCH!


FLAVIO F NOGUEIRA
ENG TELECOMUNICACOES






Em 17 de fev de 2018, à(s) 16:09, Michael Stenta <notifications@github.com<mailto:notifications@github.com>> escreveu:


See #52<https://github.com/farmOS/farmOS/issues/52>
