### ISSUE TITLE
Harvest category does not appear in edit log

### ISSUE THREAD

**Issue by Ecological-Interaction** [farmOS/farmOS#392]
Cannot edit a log to 'harvest' category. 
Harvest category does not appear.

<img width="1280" alt="Screenshot 2020-12-21 at 16 40 04" src="https://user-images.githubusercontent.com/71128180/102794287-749f5600-43ab-11eb-9785-9fe67a1cdc4a.png">

**Comment by paul121** [comment]
Hi @Ecological-Interaction ! Just to confirm, is there a "harvest" log category listed at {url}/admin/structure/taxonomy/farm_log_categories? This category wouldn't come by default, but is something you can add.

**Comment by Ecological-Interaction** [comment]
Hi Paul 

Yes 

Actually I realised I want to edit the Log Type from Activity to Harvest.
A better question would be if there is a way to edit / Change the Log Type?

Thanks

**Comment by paul121** [comment]
Ah, no, unfortunately there is not a way to edit the log type. This is because each log type can have different "fields" on them, so changing the log type could mean converting and/or losing data that is stored on the log, if the new log type does not have the same fields.

Aside from creating new logs, trying to think of other options... hopefully there aren't many to change! Maybe someone else has another idea.

**Comment by mstenta** [comment]
@paul121 is correct, you can't change the type of a log. The only option is to create a new harvest log and copy the information over.

If you have a lot of logs, and they are relatively simple, you may be able to export a CSV and then reimport it. But note that there are some very big limitations to this! Read the following links thoroughly:

https://farmos.org/guide/export/

https://farmos.org/guide/import/

The "best" solution (if you have a lot of logs that need to change) is to use the API. You can write a Python script that loads the logs you want, changes the type, and pushes them back to the server (which will create new logs).

I think those are your best options. Hope that helps!
