### ISSUE TITLE
Warning divion by Zero 

### ISSUE THREAD

**Issue by maoneid** [farmOS/farmOS#396]
**Describe the bug**
Warning Error, division by zero 

**To Reproduce**
1. Go to animal item view and detail 'http://localhost/farm/farm/animal/sapi'
2. See error
or
1. see weight report http://localhost/farm/farm/asset/1/weight

run on PHP 7.4, Ubuntu 20
Warning: Division by zero in farm_livestock_weight_dlwg() (line 137 of /var/www/html/farm/profiles/farm/modules/farm/farm_livestock/farm_livestock_weight/farm_livestock_weight.module).

**Comment by maoneid** [comment]
It is happened when I input weght more than twice a day. so timediff_days = 0 .

`$timediff_days = round($timediff/86400,2);

      // Calculate dlwg.
      $dlwg_value = round($weight_difference/$timediff_days,3);`

**Comment by mstenta** [comment]
Good find @maoneid ! If you think there's an obvious fix based on your investigation please feel free to suggest it or start a pull request.

Otherwise we'll try to remember to fix this when we port the weight module to farmOS 2.x in the next few months.

**Comment by AugustoHA** [comment]
@maoneid could you add more details about this problem, including some input examples? 
I manage to reproduce it, but only when both timestamps were equal in day and minute (EG: 04/10/2021 10:00). Otherwise, it didn't show the warning.

So if that is the problem, a simple but not elegant solution is to verify if the timediff_days equal zero and then set to one.

**Comment by mstenta** [comment]
Closing old issues, see https://github.com/farmOS/farmOS/pull/422#issuecomment-1004316168
