### ISSUE TITLE
docker-compose stucks at "[core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'"

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [farmOS/farmOS#410]
**Describe the bug**
Hello all,

When I try to install farmOS 2x with using docker-compose, I stuck at the message below:

`[core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'`

My docker and docker-compose are:

```
$ docker -v
Docker version 20.10.3, build 48d30b5

$ docker-compose -v
docker-compose version 1.25.0, build unknown
```

How should I proceed?

Best,
Orkut

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by mstenta** [comment]
Hi @orkutmuratyilmaz - that's good! The farmOS Docker container extends from the Apache container, so that means that everything started up and Apache is running. Try opening your browser and going to http://localhost (assuming you are running this locally) - you should see the farmOS installation page.

If you run `docker-compose up` it will show the running Docker container logs in your active terminal until you stop the process or close the terminal.

If you run `docker-compose up -d` (notice the `-d` flag) it will start up the containers in the background, and won't show you the logs. You can close the terminal and the containers will continue running until you manually run `docker-compose down`.

Hope that helps!

**Comment by orkutmuratyilmaz** [comment]
I am really sorry for forgetting to thank you.

Best,
Orkut
