### ISSUE TITLE
Commas in Area Asset names cause problems

### ISSUE THREAD

**Issue by JBruceDawson** [farmOS/farmOS#46]
I've now created (twice!) area names with commas in them, and ended up with two areas, one with the name before the comma, and one with a name after the comma.

Is there any way to ignore the comma when working with areas?

**Comment by JBruceDawson** [comment]
farm-7.x-1.0-beta15

**Comment by mstenta** [comment]
Hi Bruce! Ah yea... that is an annoyance. There is a workaround: if an area has commas in the name, wrap the whole name in double-quotes. Then it will know to treat that as one area.

In the future, I am going to replace the "autocomplete" field for referencing (and creating) areas with the same kind of lookup widget that is used for assets.  I ran into an issue when I tried to do that earlier, though, so I need to figure that out: https://www.drupal.org/project/farm/issues/2893550

**Comment by mstenta** [comment]
Closing this as "won't fix" for the 7.x-1.x branch. In farmOS 2.x (our current focus), areas are no longer taxonomy terms, and cannot be created on-the-fly via autocomplete text fields. So this won't be an issue anymore. A bit of a step backwards in some ways, because you can't create them quickly, but for good reasons...
