### ISSUE TITLE
Migrations failing on MySQL

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#506]
https://github.com/farmOS/farmOS/blob/bd6499ecb52c52952c561f4017cf04a0087ab4ce/modules/core/migrate/src/EventSubscriber/FarmMigrationSubscriber.php#L342
Migrations failing when using MySQL as the DB.
Failing with:

```
In ExceptionHandler.php line 53:

  SQLSTATE[HY000]: General error: 1093 You can't specify target table 'taxonomy_term_revision' for update in FROM clause: UPDATE taxonomy_term_revision
          SET revision_log_message = :revision_log_message
          WHERE revision_id IN (
            SELECT r.revision_id
            FROM "migrate_map_farm_migrate_taxonomy_animal_type" mm
            INNER JOIN taxonomy_term_revision r ON mm.destid1 = r.tid
          ); Array
  (
      [:revision_log_message] => Migrated from farmOS 1.x on 2022-02-24
  )


In StatementWrapper.php line 145:

  SQLSTATE[HY000]: General error: 1093 You can't specify target table 'taxonomy_term_revision' for update in FROM clause

```

**Comment by mstenta** [comment]
Thanks for reporting this @Skipper-is ! It appears that there is one custom query in our migration code that works fine in PostgreSQL, but doesn't work in MySQL (which is funny, because usually it's the other way around - PostgreSQL tends to be "stricter" than MySQL).

This seems to be the offending query: https://github.com/farmOS/farmOS/blob/bd6499ecb52c52952c561f4017cf04a0087ab4ce/modules/core/migrate/src/EventSubscriber/FarmMigrationSubscriber.php#L342

Notably, all that query does is add a revision message to entities when they are migrated so you have a little "Migrated on [date]" message for reference.

As a temporary workaround, if you don't mind losing that message, you can disable that by commenting out this line: https://github.com/farmOS/farmOS/blob/bd6499ecb52c52952c561f4017cf04a0087ab4ce/modules/core/migrate/src/EventSubscriber/FarmMigrationSubscriber.php#L125

That will prevent that query from running, and should allow the migration to proceed.

**Comment by mstenta** [comment]
Just noting this down for future reference... after @Skipper-is commented out the line described above, they ran into this later on in the migration:

```
[error]  Migration failed with source plugin exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column &#039;id&#039; in on clause is ambiguous: SELECT DISTINCT &quot;fa&quot;.*, &quot;fs&quot;.&quot;type&quot; AS &quot;sensor_type&quot;, &quot;fs&quot;.&quot;settings&quot; AS &quot;sensor_settings&quot;, &quot;map&quot;.&quot;sourceid1&quot; AS &quot;migrate_map_sourceid1&quot;, &quot;map&quot;.&quot;source_row_status&quot; AS &quot;migrate_map_source_row_status&quot;
FROM
&quot;farm_asset&quot; &quot;fa&quot;
INNER JOIN &quot;farm_sensor&quot; &quot;fs&quot; ON fa.id = fs.id
LEFT OUTER JOIN farm2_vhf.migrate_map_farm_migrate_asset_sensor &quot;map&quot; ON id = map.sourceid1
WHERE ((fs.type = &#039;&#039; OR fs.type IS NULL)) AND ((&quot;map&quot;.&quot;sourceid1&quot; IS NULL) OR (&quot;map&quot;.&quot;source_row_status&quot; = :db_condition_placeholder_0))
ORDER BY &quot;id&quot; ASC; Array
(
    [:db_condition_placeholder_0] =&gt; 1
)
 in /opt/drupal/web/core/lib/Drupal/Core/Database/Driver/mysql/ExceptionHandler.php line 50

In MigrateToolsCommands.php line 983:

  farm_migrate_asset_sensor migration failed.

```

But then they switched to PostgreSQL, and everything worked properly. So these both seem to be bugs with MySQL databases...

**Comment by mstenta** [comment]
I'm going to close this as "won't fix" - but if anyone has the time/interest in fixing it please feel free to reopen! I think at this point most people are either starting on farmOS v2 (and can use MySQL if they want), or they can migrate to PostgreSQL since that's the official recommended database for farmOS now.
