### ISSUE TITLE
Default status when creating a new log

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS#508]
In farmos2.x-Beta3 the default status when creating a new log is set to `Pending`. In 1.x this default was set to `Done`. For consistency it might make sense to change this default in 2.x to `Done`. 

It would be good to check the default stats on submitting a log with the API also to make sure it is consistent. 

I can see the different use cases for the default to be selectable by the user. Weather you use farmOS more for planning you would want it to default as `Pending` or if you use it more for recording past events the default would be more useful as `Done`.  This option could be a nice feature.

**Comment by mstenta** [comment]
Thanks @botlfarm! This was an oversight.

I agree making this configurable would be cool! But as a first step I think we should simply default to `Done` for consistency with v1. This is a "bug" IMO (and making it configurable could be a follow-up feature request - although I might suggest we wait to see if anyone requests it - this is the first time its come up).

> It would be good to check the default stats on submitting a log with the API also to make sure it is consistent.

+1 This might be the first thing to check actually... because ideally this works consistently between the UI and API, so if it's also defaulting to `pending` via API-created logs, then we should be able to fix both together.

**Comment by botlfarm** [comment]
As a follow up though the default might be able to be set with some logic. If you create a log in the future it could default to `Pending` and if the date is in the past it could default to `Done`. Rechecking 1.x this is how it behaved.

**Comment by mstenta** [comment]
> If you create a log in the future it could default to `Pending` and if the date is in the past it could default to `Done`. Rechecking 1.x this is how it behaved.

I forgot all about that! 😆

Trying to remember how that worked now...

**Comment by mstenta** [comment]
Here is the JS from the `7.x-1.x` branch of the `log` module that handled auto-toggling the `done` checkbox in forms when the date/time was changed: https://git.drupalcode.org/project/log/-/blob/7.x-1.x/log.done.js

We could re-implement something similar in the `2.x` branch (of `log`, not farmOS)...

That would not cover API-generated logs, however. But I dunno, maybe that's OK? Maybe defaulting to "pending" isn't actually a bad thing in that case, and the API consumer can simply set the status to `done` in their relevant code to be explicit.

**Comment by mstenta** [comment]
Opened an issue in the Log queue for this: https://www.drupal.org/project/log/issues/3268946

I will close this - thanks again for bringing it up @botlfarm !
