### ISSUE TITLE
Error Load Module

### ISSUE THREAD

**Issue by flaviomx14** [farmOS/farmOS#52]
What is the correct process for loading the Finland map module?
I uploaded the map through the web page but it gives an error. The original map disappears after uploading this module.
I'm testing this module, because I'll change it to load my own map.
Thanks!

**Comment by mstenta** [comment]
To add additional modules to a farmOS instance, you would download the module folder to (webroot)/sites/all/modules/[module-name]

It is very important that you put the modules in sites/all/modules, and NOT in profiles/farm/modules, because the latter will be replaced when you update farmOS, but the sites directory is where you put your site-specific code and files.

Then, within farmOS, go to /admin/modules, find the module in the list and enable it.

More information about installing modules in a Drupal 7 site (which is what farmOS is based on) can be found in the drupal.org documentation: https://www.drupal.org/docs/7/extend/installing-modules

Is that what you did?

**Comment by mstenta** [comment]
Specifically, I recommend using the "Manual module import" instructions: https://www.drupal.org/docs/7/extend/installing-modules#man_mod_over
