### ISSUE TITLE
Cannot view term pages after 2.0.0-beta4

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#525]
**Describe the bug**

After upgrading to 2.0.0-beta4 when trying to view a term page (it seems to be any, not only `plant_type`) I get the following: `Route "view.farm_asset.page_term" does not exist`

This is on an instance with `farm_update` disabled. I understand that this "becomes my problem" when not using `farm_update` but we should include these types of breaking changes in release notes in the future.

I think we should also be careful about *adding* displays to views in the future. If I had overridden this view (eg: removed a field from the `page` display of assets) I think I would need to re-import the entire `farm_asset` view and in the process lose my changes (unless I dug into the long view `.yml` source and somehow pulled in only the changes I wanted... a task I personally would not be confident in taking on myself :smiley: )

**To Reproduce**
1. Upgrade a site from 2.0.0-beta3 to 2.0.0-beta4 that does not have `farm_update` enabled
2. After upgrading, navigate to a taxonomy term page (eg: `/taxonomy/term/5`)
3. Observe error

**Additional context**
```
Symfony\Component\Routing\Exception\RouteNotFoundException: Route "view.farm_asset.page_term" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 206 of /var/www/html/web/core/lib/Drupal/Core/Routing/RouteProvider.php).
```

**Comment by mstenta** [comment]
Ouch thanks for raising this @paul121!

> This is on an instance with `farm_update` disabled. I understand that this "becomes my problem" when not using `farm_update` but we should include these types of breaking changes in release notes in the future.

That makes good sense. Perhaps we can add a note to the [release procedure](https://farmos.discourse.group/t/2-x-release-procedure/1070) to this effect. And/or adopt some kind of convention in out `CHANGELOG.md` - sort of like the way Drupal core mentions whether or not an update makes changes to `.htaccess` files (eg: on the bottom of https://www.drupal.org/project/drupal/releases/9.3.12).

> I think we should also be careful about adding displays to views in the future. If I had overridden this view (eg: removed a field from the `page` display of assets) I think I would need to re-import the entire `farm_asset `view and in the process lose my changes (unless I dug into the long view `.yml` source and somehow pulled in only the changes I wanted... a task I personally would not be confident in taking on myself smiley )

I think a better approach would be to encourage *cloning* of a View instead of altering the ones that are provided by core farmOS. I don't think we can guarantee that new displays won't be added in the future.

This is just sort of the nature of the beast, I think. We need to strike a balance between providing sane default configurations, while also accepting that downstream users may want to do something slightly different. Ultimately it is sort of "their problem" if they are overriding core config - but we could certainly make a better effort to communicate those considerations and help establish some best practices to avoid pitfalls like this.

I'm not sure what we can do to resolve *this* particular issue, apart from creating it in case someone runs into it and searches the queues for an answer. So is it OK to close this? Or do you have an idea for resolving it in another way?

**Comment by paul121** [comment]
Sorry @mstenta missed your response here. yes, OK to close this, I don't have any better ideas just wanted to flag it!

> And/or adopt some kind of convention in out CHANGELOG.md - sort of like the way Drupal core mentions whether or not an update makes changes to .htaccess files (eg: on the bottom of https://www.drupal.org/project/drupal/releases/9.3.12).

Hadn't noticed this before! Yes something like this would be interesting..

> I think a better approach would be to encourage cloning of a View instead of altering the ones that are provided by core farmOS. I don't think we can guarantee that new displays won't be added in the future.

+1
