### ISSUE TITLE
Expose sensor data and config via REST API

### ISSUE THREAD

**Issue by nielswart** [farmOS/farmOS#57]
It would be nice if it was possible to easily extract all data via the REST API.

**Comment by mstenta** [comment]
Thanks for opening this @nielswart - I agree!

For reference (and for others who find this), the current incarnation of the farm_sensor_listener module creates an endpoint URL for each sensor asset that allows data to be pushed to it via POST requests.  Sending a GET request to the same URL will return the latest data point(s) from that sensor - but it doesn't currently offer an option to return all data, or ranges of data. So we can expand on that existing endpoint to add those capabilities.

**Comment by leogaggl** [comment]
Was about to add a new issue when I found this @mstenta  . Just to clarify we would really love to be able to expose sensor asset private key via API. Currently, there is no way to get the private key for a sensor to allow pushing data without human involvement.

Unfortunately, I don't have the reasons why a private key is per sensor (rather than as an API key for all sensors). Obviously, there are some advantages with sharing these per sensor. But from an integration perspective (such as getting sensor data from an IoT platform) it's more complex.

**Comment by mstenta** [comment]
Thanks @leogaggl - I think these two are slightly different feature requests, but for now we can discuss both in this issue, as an umbrella for generally making the custom sensor module content and config available over API.

> I don't have the reasons why a private key is per sensor (rather than as an API key for all sensors).

We did this for security purposes. The thought being: if you have a bunch of sensors, and one of them gets compromised, you can disable access to your farmOS from *just* that sensor.

> But from an integration perspective (such as getting sensor data from an IoT platform) it's more complex.

Agreed - but I think exposing the public/private keys via the API would also solve this, correct?

**Comment by mstenta** [comment]
Closing old issues... and I think a lot of this will work out-of-the-box in farmOS 2.x. But if there are remaining pieces missing we can open new issues as they come up.
