### ISSUE TITLE
Run on Rasperry Pi via Docker

### ISSUE THREAD

**Issue by chrowe** [farmOS/farmOS#58]
I can get docker and docker compose installed but then when I run
` sudo docker-compose up`
I get
```
Creating network "farmos_default" with the default driver
Pulling db (mariadb:latest)...
latest: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm in the manifest list entries
```

Steps to recreate
1. Install docker with`curl -sSL https://get.docker.com | sh` from https://www.raspberrypi.org/blog/docker-comes-to-raspberry-pi/#
2. Install docker compose following https://www.berthon.eu/2017/getting-docker-compose-on-raspberry-pi-arm-the-easy-way/ with a few modifications
```
git clone https://github.com/docker/compose.git
cd compose
docker build -t docker-compose:armhf -f Dockerfile.armhf .
docker run --rm --entrypoint="script/build/linux-entrypoint" -v $(pwd)/dist:/code/dist -v $(pwd)/.git:/code/.git "docker-compose:armhf"
sudo cp dist/docker-compose-Linux-armv7l /usr/local/bin/docker-compose
sudo chown root:root /usr/local/bin/docker-compose
sudo chmod 0755 /usr/local/bin/docker-compose
```
Note: step 2 takes a long time (maybe 2 hours)

**Comment by mstenta** [comment]
> latest: Pulling from library/mariadb
> ERROR: no matching manifest for linux/arm in the manifest list entries

Hmm yea that's what I expected. It is made for x86 architecture, so it's not compatible with ARM.  That's the MariaDB container, anyway, but we'll run into the same thing with the farmOS image itself.

From https://blog.hypriot.com/getting-started-with-docker-on-your-arm-device:

> So the CPU architecture here is ARM rather than x86/x64 by Intel or AMD. Thus, Docker-based apps you use have to be packaged specifically for ARM architecture!

So I see this as 3 problems:

1. farmOS Docker image doesn't work on ARM
2. MariaDB Docker image doesn't work on ARM
3. Docker Compose requires manual compile in Raspbian (not really a problem, but certainly annoying)

The first one can be solved by providing a second Docker image for farmOS on Docker Hub that is specifically for ARM architectures. I think we would just need to create a second Dockerfile, which inherits from an ARM compatible base image (https://github.com/docker-library/official-images#architectures-other-than-amd64), and then add a new tag to Docker Hub for that image.

The second and third may not actually be necessary.  Docker Compose makes it easy to set up both a farmOS and MariaDB container at the same time, linked together, for local development.  But on a Pi, we can take a slightly different approach if we want: just use the farmOS image, and install farmOS using a local SQLite3 database (instead of MariaDB).  farmOS (Drupal) provides this as an option during install.  Using SQLite3 means that a separate database server isn't necessary - the farmOS database just gets saved to a single file in the [webroot]/sites/default/private directory.  If we recommended this approach, we would just want to document what the correct commands are for starting/stopping/destroying the farmOS container (and volume mounts, environment variables, etc) without using Docker Compose.

So either way, step 1 is to make an ARM compatible farmOS image.

**Comment by mstenta** [comment]
Looks like this may have been resolved upstream: https://github.com/docker-library/drupal/issues/89

Very timely too... I just recently modified the farmOS `Dockerfile` to inherit from the official Drupal image, as part of PHP 7 support branch: https://github.com/farmOS/farmOS/commit/1f24c9df2f3489939cd85f28b5a0afdf2ac77ea7

So this might just work? Let's try it!

**Comment by mstenta** [comment]
I tried it on a Pi Zero W and couldn't get docker to run...

```
$ sudo service docker start
Job for docker.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

I was able to get Docker to run on a Pi 3 Model B, and running `sudo docker pull farmos/farmos:7.x-1.x` works!

But, attempting to start a farmOS container (with `sudo docker run --rm farmos/farmos:7.x-1.x`) fails with the following error: 

```
standard_init_linux.go:190: exec user process caused "exec format error"
```

However, building the image locally works!

```
git clone https://github.com/farmOS/farmOS.git
cd farmOS
sudo docker build farmos .
sudo docker run --rm -p 80:80 farmos
```
Installed it into an SQLite database (that's an option during Drupal install).

Installation took a long time, but it's working!

**Comment by mstenta** [comment]
To summarize, here are the commands to run farmOS on Raspberry Pi with Docker (only works on Pis that support arm64 Docker images).

```
sudo curl -sSL https://get.docker.com | sudo sh
git clone https://github.com/farmOS/farmOS.git
cd farmOS
sudo docker build -t farmos .
sudo docker run -p 80:80 -v ${PWD}/.data/www:/var/www/html farmos
```

**Comment by mstenta** [comment]
I created a new documentation task so we can copy those commands into farmOS.org docs: https://github.com/farmOS/farmOS.org/issues/39

I'm going to close this issue because this works now!
