### ISSUE TITLE
Status Message Doesn't work with Clean URLs Turned Off

### ISSUE THREAD

**Issue by almostengr** [farmOS/farmOS#59]
The status message listed on the line below, won't navigate to the non-clean URL if Clean URLs are not turned on.  This resulted in navigating to a page that doesn't exist. 

As you see in the screenshot below, the URL should navigate to the clean URL but instead it doesn't. Thus it results in a 404 not found.

The "l" function is recommended to be used for this.

https://github.com/farmOS/farmOS/blob/8ae82d1a2496e9cfd7029de4f8486d5b5219da0e/modules/farm/farm_asset/farm_asset.pages.inc#L214

![screenshot from 2018-03-07 21-41-36](https://user-images.githubusercontent.com/15150637/37131882-53cc484a-2250-11e8-9437-2ec9e18a5e7d.png)

**Comment by mstenta** [comment]
Thanks for the heads up @bitsecondal !

Can you test this for me?  Replace that line with this:

`  drupal_set_message(t('Asset saved: <a href="@uri">%title</a>', array('@uri' => url($farm_asset_uri['path']), '%title' => entity_label('farm_asset', $farm_asset))));`

The `l()` is _usually_ the recommended way to build links, you are correct.  In this context, however, `url()` is recommended because the link is inside a translatable string.  See https://www.drupal.org/docs/7/api/localization-api/dynamic-or-static-links-and-html-in-translatable-strings

The `l()` function actually calls the `url()` function to build the path, so both end up with the same result anyway. :-)

If that works, I will also fix this in the Log module and the Farm Plan module (which have similar messages when entities are saved).  We may want to review other instances of drupal_set_message() to see if there are others. Or just feel free to post issues if/when you encounter them. :-)

**Comment by mstenta** [comment]
I fixed this in the farm_asset, farm_plan, and log modules.
