### ISSUE TITLE
Enable/disable data stream notification not working from the quick-menu.

### ISSUE THREAD

**Issue by bitfieldfarm** [farmOS/farmOS#613]
In the notification's list view, the deactivate menu item is not working.
It works if it's deactivated (or activated) while editing the notifacation itself.

Also, it's not working to re-activate a notification directly from the list of deactivated notifications.

**Comment by paul121** [comment]
Thanks for reporting @bongorongo ! I'm able to reproduce when logged in as a manager user. As the admin user this works as expected.

Error message as manager user:

> 403 error: {"message":"The following permissions are required: \u0027edit data_stream_notification\u0027 OR \u0027edit data_stream_notification data_stream_notification\u0027."}

It's likely that our permissions in the routing definition are incorrect, should be `data_stream_notification.update` instead of  `data_stream_notification.edit`:

https://github.com/farmOS/farmOS/blob/c787d7e25641d8499a9af5e618d7eee921a85672/modules/core/data_stream/modules/notification/data_stream_notification.routing.yml#L7

**Comment by paul121** [comment]
Unable to test this fix at this moment but that is my suspicion
