### ISSUE TITLE
Structure assets are rendered under land assets

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#651]
**Describe the bug**

Structure assets are currently being rendered underneath Land assets, which means that if you have a building with a polygon that overlaps a field, and you click on it in the dashboard map, you see a popup for the field instead of the building. In order to see a popup for the building you have to turn off the land layers.

**To Reproduce**

1. Create a Land asset with a polygon geometry.
2. Create a Structure asset with a polygon geometry that is inside the Land asset's geometry.
3. Go to the Dashboard and click on the Structure asset in the map.

**Expected behavior**

The expectation is that clicking on the Structure asset will show a popup for the Structure asset, but instead it shows a popup for the Land asset. In order to see a popup for the Structure asset you must first turn off the Land asset layer.

**Screenshots**

![Screenshot from 2023-03-08 16-48-25](https://user-images.githubusercontent.com/95381/223858427-439fc9b6-423b-43dc-bada-640f46ba869f.png)

![Screenshot from 2023-03-08 16-48-45](https://user-images.githubusercontent.com/95381/223858446-474ebff5-0257-41ed-8bc4-da455aba57ba.png)

**Additional context**

https://farmos.discourse.group/t/remove-map-from-dashboard/1556/4?u=mstenta

**Comment by mstenta** [comment]
Obviously, this won't ALWAYS work the way you want it to, because it is based on the order of layers on the map. But we can make some decisions that are true most of the time, such as: "buildings are smaller than land, so rendering them on top improves UX"

**Comment by symbioquine** [comment]
I think there's two separate potential problems here;

1. The order of rendering (maybe?) making some features harder to see
2. The order in which features are considered upon clicking making some features harder to select

It looks like most of the bug here is that it is impossible to select the greenhouse without a work-around. I believe that we could fix that without changing the rendering order by instead improving the logic of the [popup behaviour](https://github.com/farmOS/farmOS/blob/a1babd86a495a15af60f3c95dba1299ee73a3b10/modules/core/map/js/farmOS.map.behaviors.popup.js#L17-L21) to be something like;

```
const features = instance.map.getFeaturesAtPixel(event.pixel);
// Either:
// - Display a popup with a list of all features
// - Display the feature either with the smallest area or centroid closest to the clicked point
```

**Comment by mstenta** [comment]
> centroid closest to the clicked point

This is a stroke of genius @symbioquine!

I was discouraged because I realized we didn't have an easy way to control layer ordering (which we may still want to add at some point), but this would solve the issue at hand in a much better way.

**Comment by symbioquine** [comment]
Thanks, but centroid doesn't solve the problem of selecting the smaller of two concentric circles or similar cases where two shapes have the same centroid, but where one is smaller and lies completely within the other.

![image](https://user-images.githubusercontent.com/30754460/223896933-c8ac698d-1dae-4809-bb7a-7c327d280876.png)

![image](https://user-images.githubusercontent.com/30754460/223896954-90f3da17-b551-453e-a44a-d26e84d7d275.png)


That's why I suggested those two (area and centroid) as part of the same strategy. I think there must be a way to combine them to solve all these cases, but I just haven't thought of it yet...

**Comment by mstenta** [comment]
@symbioquine @paul121 and I played around with this a little on today's dev call. We managed to get something together that is a significant improvement over the current behavior, and fixes the issue described above in most common cases. It doesn't cover every edge case, and introduces a potential new issue in a very specific (and probably rare) circumstance, but it is still better than what we have now, so I'm going to put together a PR with this change as a first step.

A little more detail...

First, we realized that there is no `getCentroid()` function in OpenLayers like we thought. There is, however, the ability to `getCenter()` of an extent object. We can do `feature.getGeometry().getExtent()`, but that returns an array of extent coordinates, not an extent object. So, in order to use `getCenter()` we would need the ability to generate an extent object, which the default farmOS-map.js packaged library does not include. So we would need to add it upstream first (maybe using one of the strategies we've been talking about in https://github.com/farmOS/farmOS-map/pull/189).

So, instead we decided to *only* go by the area of the feature that is clicked, using `feature.getGeometry().getArea()`. This function *is* available. We use `getFeaturesAtPixel()` to get *all* features at the point of click, and then sort them based on area from smallest to largest using a function that @symbioquine sketched up. This worked great, essentially allowing the smallest feature's popup to be displayed when multiple features are clicked. This solves the original (and most common) issue described above, where a smaller asset geometry overlaps a larger asset geometry.

This works well for polygons, as well as lines and points. It gives lines and points an area of 0, so they float to the top of the list and take priority if you click on them, which works well in practice.

There is one edge-case we discovered, though, where the current logic does not work well: geometry collections. If `feature` is a `GeometryCollection`, then `feature.getGeometry().getArea()` returns 0. This means that geometry collections always float to the top. Depending on all the geometries involved, it's possible to end up in situations where you can't get certain asset popups to appear, because the geometry collection asset always takes precedence.

We decided to punt on that problem for now, because in practice it should be rare, and the change we did make solves the most common issue. We can address this edge case, and others if they pop up (pun intended! :smile:), as next steps...

**Comment by mstenta** [comment]
Pull request: https://github.com/farmOS/farmOS/pull/652
