### ISSUE TITLE
Google Map not displaying.

### ISSUE THREAD

**Issue by darrenjlobb** [farmOS/farmOS#68]
Having problems with my FarmOS install in that the google maps have stopped appearing on any page.

Just get grey box with the error:

"Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details."

Was working fine before!

**Comment by mstenta** [comment]
Hi @darrenjlobb - are you using Chrome? If so, try this: right click and select "Inspect". A new window will appear with a set of tabs. Click the "Console" tab. This should show you some more detailed clues about what's breaking the map. If you copy and paste those messages here, I can help debug.

Also: do you think this was related to any patches you applied? You and I discussed two different patches last week - but I'm not sure if you ended up applying either of them. I would be curious to know if that had anything to do with this.

**Comment by darrenjlobb** [comment]
Errors in console:

Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
_.Ub @ js?v=3.22&callback=Drupal.openlayers.openlayers_source_internal_googlemaps_initialize:43
util.js:229 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
ZB.j @ util.js:229
util.js:229 Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
ZB.j @ util.js:229

Looks like some kind of API key error?

I did apply the patch for the new version of PHP, which fixed the errors I was getting at the top of the page...I must admit I didnt notice if this was broken at the time, but it could well have been?

**Comment by mstenta** [comment]
Oh right... you also said that you moved to a different server recently, correct? Did the domain/URL of your farmOS site change?

If so, you probably need to set up API keys for Google Maps.  They are not required if you are hosting locally, or if you were grandfathered in from before that became a requirements - but they are required now.

There are instructions for doing that here: http://farmos.org/hosting/googlemaps/

Give that a try - I bet that's what the problem is.

**Comment by darrenjlobb** [comment]
Thanks for the info Michael, that is almost certainly the problem as yes I have moved the site to a new server here in the rack!

I have just successfully generated a new API key, and enabled as per steps 1/2, however cant find the option in the config to enter the new key, the link shown doesn't give me any options other than a tick box to "Show dashboard maps"

Has it moved elsewhere / can i find it in a config file somewhere?

**Comment by darrenjlobb** [comment]
Found a setting to allow me to enter the API key at /admin/config/content/geocoder , however not joy as of yet...

**Comment by mstenta** [comment]
@darrenjlobb Ah yea, the /admin/config/content/geocoder SEEMS like the right place, but it's not. That is provided by the Geocoder module and we're not actually using that configuration anywhere. A lot of people have been confused by that.

That's why I added an option to /admin/config/farm/map in farmOS 7.x-1.0-beta16.

What version of farmOS do you have? If you're not seeing a field for "Google Maps API Key" in /admin/config/farm/map then you probably don't have the latest version.

**Comment by darrenjlobb** [comment]
Updated to latest version, option was there then, entered new API key and everything working perfectly!

Thanks!

**Comment by mstenta** [comment]
Wonderful! :-D
