### ISSUE TITLE
KML export module assigns a polygon to an Animal asset

### ISSUE THREAD

**Issue by guillermo-farmos** [farmOS/farmOS#685]
**Description**
A selected _Animal_ asset will be included in an exported KML file and a _Polygon_ shape will be assigned to the animal(**!**)
(This polygon corresponds to the shape of the asset in which the animal is currently located.)
.

**Steps to reproduce the behavior**
1. Go to your asset page (*https://<your_famr_name>.farmos.net/assets*)
2. Select just two assets: an Animal asset and the asset where the animal is located (Animal: "Daisy"; Structure: "Milking shed")
3. Select "Export KML" from the **Action** drop down at the bottom of the assets page
4. Click the "Apply to Selected Assets" button

![problem_2_a](https://github.com/farmOS/farmOS/assets/45529606/92ae4ec1-14b3-42a9-92c6-c3ac1c487c8d)

5. Click the link to the exported KML file that appears in the _Status Message_ at the top of the page.
6. Open the KML file to verify that the animal's _Placemark_ includes a _Polygon_ which is the same shape as the polygon of the asset where the animal is currently located.

![problem_2_b](https://github.com/farmOS/farmOS/assets/45529606/ef0e5101-efe2-4b26-94a0-04fa3d30a24a)

**Expected behavior**
No _Polygon_ should be included in a KML file for _non-location_ assets (animal, plant, machinery, inventory, etc.)

**Additional notes**
The above cannot be tested in [asset-link-test.farmos.net ](https://asset-link-test.farmos.net/) as no KML modules are activated.

**Comment by mstenta** [comment]
I appreciate the testing @guillermo-farmos!

This is not a bug, however.

If you click on your "Daisy" asset in the farmOS UI, you will see that it *does* indeed have geometry. As you said:

> a Polygon shape will be assigned to the animal(!)
(This polygon corresponds to the shape of the asset in which the animal is currently located.)

It is intended behavior.

Imagine someone who rotates livestock through paddocks. They want to know where that livestock currently is. They assign geometry to their animal assets by creating a "movement" log. This movement log has a geometry associated with it (automatically pulled from the paddock that was referenced, for example, or manually overridden to be a more specific geometry). The animal asset's location and geometry is determined by its most recent completed movement log.

This same geometry is then also available via the API, or via other export mechanisms like the KML export you tested. This would be useful if you needed to share the current location of your animals with another person or another piece of software. Imagine visualizing this in various ways to help with rotation planning, for instance.

See these sections of the user guide and data model docs for more information:

- https://farmos.org/guide/location/
- https://farmos.org/model/logic/location/

Hope that all makes sense!

**Comment by guillermo-farmos** [comment]
Yes, it makes sense (Thanks Mike @mstenta for the very detailed answer)
.
.
.

I thought it could be a bug in terms of **_data redundancy._**

Also, it generates **_larger KML files_**. For example,

_Scenario:_
= 1 mob of 1,000 cows
= currently grazing an irregular, 11-vertices paddock ---it could have been a much more complex polygon though

_KML outputs:_ 
![problem_2_c](https://github.com/farmOS/farmOS/assets/45529606/7cf2b99a-d8b1-4648-8334-366fa3adc3ab)
.
.
.

I see now the **_intended behavior_** described in the FarmOS guide for [_Movements and Location_](https://farmos.org/guide/location/) ...
> Every Log has a "Location" reference field (for referencing the location Asset that things are moving to), **a "Geometry" field** (for recording the precise geometry where things are moving), and an "Is movement" field (for designating the Log as a movement).

... and the **current** FarmOS [_Logic_](https://farmos.org/model/logic/location/#logic)
>The logic for determining an Asset's geometry is as follows:
>
    Is the Asset fixed?
        Yes: Does it have an intrinsic geometry?
            Yes: intrinsic geometry
            No: no geometry
        No: Does it have a movement Log?
            Yes: Does the movement Log have geometry?
                Yes: movement Log geometry
                No: Does the movement Log reference a location Asset?
                    Yes: (recurse to determine location Asset's geometry)
                    No: no geometry
            No: no geometry
>
>Geometry
>
>When a Log is saved without a geometry, and it references locations that have geometries, the combined geometries of the referenced locations will be copied to the Log. Assets referenced in the Location relationship are given first priority. If none are found, then Assets referenced in the Log's Asset relationship will be used. In the latter case, only Assets that are explicitly designated as locations will be included, and geometry will not be copied if the Log is a movement (otherwise it would be impossible to clear the geometry of a non-fixed location Asset via movement Logs).

.
.
.

However, I wonder if an **_alternative logic_** could do the job of **_pointing_ to a geometry** while avoiding data redundancy:

    Is the Asset fixed?
        Yes: Does it have an intrinsic geometry?
            Yes: **_point_** to its intrinsic geometry
            No: no geometry
        No: Does it have a movement Log?
            Yes: Does the movement Log reference to a location Asset? 
                Yes: (recurse to the top question)
                No: no geometry
            No: no geometry

**Comment by mstenta** [comment]
> Also, it generates larger KML files.

This is true if you export all of your individual animals separately. A better way to do it might be to group them all together into a single herd (using the Group module), and track the location of the herd as a whole. Then only export the KML of the herd, instead of individual animals.

Generally speaking, farmOS is not opinionated about how you use it. It just provides general tooling to be able to do whatever you want. If you want to export all your animals as individual geometries you can. Although I agree that wouldn't really make sense in most cases.

> I wonder if an alternative logic could do the job of pointing to a geometry while avoiding data redundancy

Actually this data redundancy is intentional as well, and is desirable for a number of reasons. This ensures that you always have accurate data on the LOG level itself - regardless of what happens outside of that. For example, imagine you create a log to record fertilization of a field. It automatically copies the geometry of the field AT THAT TIME. If you then were to change the geometry of that field, we would NOT want the geometry of the log to change, because that is not what you fertilized presumably.

The other feature we get by having a separate geometry on the logs themselves is the ability to have more specific geometry on the log. This is necessary for cases where you may only be moving animals to a SUBSET of a field (using movable fencing for example). You don't want to create separate land assets for every location of your fence, so instead you can say that the animals moved to "Paddock 1" but then draw a smaller geometry within that to specify exactly where INSIDE "Paddock 1" the fence was set up. Thus, you can move the same animals around multiple times within a single area.

This level of granularity is important for accurate record keeping.

Hope that all makes sense! :-)

**Comment by guillermo-farmos** [comment]
Makes perfect sense, thank you Mike!
