### ISSUE TITLE
Filter option allow reset after apply with no input

### ISSUE THREAD

**Issue by LunarDerrick** [farmOS/farmOS#693]
Hi, I noticed that all filter options, when I clicked Apply without any additional filter criteria, still allow me to click Reset. I believe it should be addressed to prevent confusion when using filter options.

**Comment by wotnak** [comment]
When clicking `Apply` on view filters without changing any filter values, the default values are explicitly applied, which activates the `Reset` button. The applied default values can be seen in the page url. For example, on the assets listing page (`/assets`) applying default filters will add to the url following filters `?name=&is_location=All&is_fixed=All&status=active&items_per_page=50`. Clicking then the `Reset` button will remove explicit filters and will use in most cases still the same default filter values but without explicitly enforcing them.

I don't think it is a bug, but rather an intentional feature that just currently might have not the best ui.

Perhaps the ux of this interaction could be improved by displaying a list of currently applied filters above the results, as it is often done on ecommerce product listings. But this would be probably better suited to be implemented as a contrib Drupal module than directly in the farmOS core.

**Comment by mstenta** [comment]
I agree with @wotnak. And the code for this functionality is not actually part of farmOS. It is part of Drupal. So if there are improvements to be made then they should be proposed in the Drupal issue queue instead of this one. https://www.drupal.org/project/issues/drupal

We (as the farmOS maintainers) try to keep farmOS as a "thin layer" of decisions on top of Drupal and other community maintained Drupal modules (aka contrib modules). This keeps our maintenance burden sustainable and helps to encourage improvements to the upstream dependencies that we are using as building blocks.

Closing this as "not planned" but please feel free to pursue improvements to this functionality upstream @LunarDerrick!
