### ISSUE TITLE
Quick Form website error

### ISSUE THREAD

**Issue by LunarDerrick** [farmOS/farmOS#694]
Hi, I noticed that Birth and Movement sections in Quick Form are unusable. Whenever I tried to open them, it just prompted "The website encountered an unexpected error. Please try again.". I hope this will help in making farmOS better.

**Comment by wotnak** [comment]
Could you check and paste here the specific error that should be saved in the Drupal logs?
To find it, you can:
- go to the problematic quick form (to generate the error),
- go to Administration > Reports > Recent log messages (/admin/reports/dblog),
- the specific error log should be displayed on top of the list (it will probably will have `php` type),
- after clicking on the `Message` value of the log full error message will be displayed.

The full error message would help us to determine what is going wrong, the generic `The website encountered an unexpected error. Please try again.` doesn't give any context about the error and as far as I'm aware the mentioned quick forms work for most users (including me) without any problems. So this might be some issue with your environment (especially since you mentioned in https://github.com/farmOS/farmOS/issues/696 that there is some error reported for your installation) or maybe there is some edge case that no one yet encountered. Anyway, without a more detailed error message, it's hard to tell what might be going on.
