### ISSUE TITLE
Birth log quick form apostrophe becomes &#039;

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS#698]
**Describe the bug**
When creating a birth log using the quick form if the childs name has an `'` in it the log title replicases the `'` with `&#039;`.

**To Reproduce**
1. go to birth quick form
2. enter childs name with an apostrophe like `suzies's1-1`
3. select any mother asset
4. save the log

**Expected behavior**
log title: `Birth: suzie's1-1`

**Actual Results**
log title: `Birth: suzie&#039;s1-1`

![image](https://github.com/farmOS/farmOS/assets/54162154/b6596066-7ba6-4b0e-aca6-9921b28697e9)

farmOS version 2.1.0
tested on windows chrome and android chrome

**Comment by mstenta** [comment]
Thanks for reporting this @botlfarm! I'll take a look at this soon.

**Comment by mstenta** [comment]
I confirmed that this is happening when I test locally.

I traced it to the fact that the child asset names are being passed through the `t()` function with a `@children` placeholder:

https://github.com/farmOS/farmOS/blob/42f4b5fac6700fd63e7a783764faf1727b407579/modules/quick/birth/src/Plugin/QuickForm/Birth.php#L476

This causes their names to be passed through Drupal's `Html::escape()` function: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Html.php/function/Html%3A%3Aescape/9

> This method escapes HTML for sanitization purposes by replacing the following special characters with their HTML entity equivalents:
> - `& (ampersand) becomes &amp;`
> - `" (double quote) becomes &quot;`
> - `' (single quote) becomes &#039;`
> - `< (less than) becomes &lt;`
> - `> (greater than) becomes &gt;`

We shouldn't be filtering these names before they get saved to the log name, because filtering of asset and log names already happens when they are printed to the page (or should be in all cases).

An easy solution would be to change this line from:

`$birth_log_values['name'] = $this->t('Birth: @children', ['@children' => $this->trimString(implode(', ', $child_names), 180)]);`

to:

`$birth_log_values['name'] = $this->t('Birth') . ': ' . $this->trimString(implode(', ', $child_names), 180);`

The only consideration here is that it might make translations less specific. Instead of translating "Birth: @children" (which is specifically for birth log names), it will be translating "Birth" (which applies in many other contexts). The benefit is we reuse the "Birth" translation, and remove the need for this extra one. The disadvantage is that it make end up negatively affecting the translation in certain languages, if the "Birth" + colon + "names" format is not natural. That's just a hypothetical, though, so I don't know if we need to worry about it right now. And maybe a better solution would be to make the Birth quick form "configurable" (see https://www.drupal.org/project/farm/issues/3354935) and provide a user-editable option for the log naming pattern.

**Comment by mstenta** [comment]
> `$birth_log_values['name'] = $this->t('Birth') . ': ' . $this->trimString(implode(', ', $child_names), 180);`

This also makes me think that using the `prioritizedString()` and `entityLabelsSummary()` methods, like we do in the Planting quick form, would be better than `trimString()` here.

I'll prepare a PR that makes these changes in separate commits for review.

**Comment by mstenta** [comment]
Ah... in testing this I discovered the same issue occurs on the weight observation log that can be optionally created from this quick form. I'll fix that in the same PR.

**Comment by wotnak** [comment]
To prevent escaping placeholder values passed to `t()` function, they can be wrapped in an object implementing MarkupInterface. https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Component/Render/FormattableMarkup.php#L265
So in this case something like this should prevent escaping and not limit translation possiblities:
```diff
diff --git a/modules/quick/birth/src/Plugin/QuickForm/Birth.php b/modules/quick/birth/src/Plugin/QuickForm/Birth.php
index a5b456cf..e8c584b3 100644
--- a/modules/quick/birth/src/Plugin/QuickForm/Birth.php
+++ b/modules/quick/birth/src/Plugin/QuickForm/Birth.php
@@ -8,6 +8,7 @@ use Drupal\Core\Entity\EntityTypeManagerInterface;
 use Drupal\Core\Extension\ModuleHandlerInterface;
 use Drupal\Core\Form\FormStateInterface;
 use Drupal\Core\Messenger\MessengerInterface;
+use Drupal\Core\Render\Markup;
 use Drupal\Core\Session\AccountInterface;
 use Drupal\farm_group\GroupMembershipInterface;
 use Drupal\farm_location\AssetLocationInterface;
@@ -473,7 +474,12 @@ class Birth extends QuickFormBase {
     foreach ($children as $child) {
       $child_names[] = $child->label();
     }
-    $birth_log_values['name'] = $this->t('Birth: @children', ['@children' => $this->trimString(implode(', ', $child_names), 180)]);
+    $birth_log_values['name'] = $this->t(
+      'Birth: @children',
+      [
+        '@children' => Markup::create($this->trimString(implode(', ', $child_names), 180)),
+      ],
+    );
 
     // If the birth mother has a location (at the time of birth), use the birth
     // log to set the location of the children.

```

**Comment by mstenta** [comment]
Thanks @wotnak! I was just about to say... the weight observation log string is more complicated, so I decided to fix that one using `Markup::create()` (which I just learned about from https://agaric.coop/blog/pass-variables-without-escaping-nor-sanitizing-t-drupal-8).

**Comment by mstenta** [comment]
I'm searching through other quick forms and seeing a few other places where we should use `Markup::create()` as well. I'll open a general PR for all of them.

**Comment by mstenta** [comment]
Opened a pull request that fixes this, as well as similarly affected log names in other core quick forms and bulk actions (including updates to automated tests to catch future regressions): https://github.com/farmOS/farmOS/pull/705
