### ISSUE TITLE
map-based task list for workers

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#72]
say a bunch of farm workers are gathering "observations" of weeds or damaged fence posts, etc. they log these from their phones with a photo and a location point, which as far as i can tell is a multi-click process involving taking photo, adding geometry, creating a point, naming, adding a "group" for the category of weed or damage, etc. i think this needs to be massively streamlined but let's just accept that process... how does one export the locations of all "thistle patches" or "broken fence posts" in a useful way such that a cell phone could get a set of locations for a map app or task list that they can simply use to navigate, remedy and then mark as done?

**Comment by mstenta** [comment]
> how does one export the locations of all "thistle patches" or "broken fence posts" in a useful way such that a cell phone could get a set of locations for a map app or task list that they can simply use to navigate, remedy and then mark as done?

Every log in farmOS can have geometry attached to it, so you can create activity logs that point to a specific location and assign them to people.

You might also consider tracking your fences and thistle patches as assets themselves, so that you can keep multiple logs attached to them over time (for ongoing maintenance, for example).

> as far as i can tell is a multi-click process involving taking photo, adding geometry, creating a point, naming, adding a "group" for the category of weed or damage, etc. i think this needs to be massively streamlined but let's just accept that process...

Ideas and contributions are welcome!  :-)

I will also mention that there is currently work happening on a simplified UI for a farmOS native app, which would ease a lot of what you described.  There will always be a need for the more full-features UI that farmOS itself provides, also, we're always looking for ways to streamline that as well.

> map-based task list for workers

The idea of a map-based task list for workers is neat.  If you'd like to put together a detailed description of how you envision that working, that would be great!

**Comment by bobombolo** [comment]
how does one create new asset types? i am using farmier hosting. can inventory be used with custom asset types?

**Comment by bobombolo** [comment]
i guess it could be that a worker could download all tasks assigned to them and not yet done as a KML file that opens into google maps and lists all tasks as pins. within the description of each pin (task) would be a link back to the farmos site and specifically to that task in edit more to mark as "done" or make notes. 
there are issues with loading kml files into android/ios version of Maps by google, but some such similar solution could be very effective.
there is also an android GIS tool called nextGIS (available from F-Droid) for which you could export layers in a similar fashion. and a mobile GIS logging tool like that might be the answer to the first part of my question about streamlining the scouting workflow for say marking weed patches with far less clicks. this would require a module that can take the GIS layer from nextGIS and turn it into either a list of assets, logs or as you say just a layer in Openlayers (see #75 )...

**Comment by mstenta** [comment]
> how does one create new asset types? i am using farmier hosting. can inventory be used with custom asset types?

New asset types can only be added via a new module, so it does require some programming. It is not possible to install custom modules on Farmier, so you would have to host it yourself.

**Comment by bobombolo** [comment]
nextgis mobile seems to be a very decent free software GIS app for android but it has limited data format support and exporting limitations. a tight integration with this app could create a great end-to-end mobile solution for farmOS without any need to develop a standalone app. nextGIS is a big supporter of QGIS, the de-facto open-source GIS package.
for example, if there was a synching feature between the two that would allow for each area, asset type and some types of logs to be created from the handheld, or to sync from farmOS to the handheld, you would have an almost transperent interface. this would require farmOS to support the default formats nextGIS uses. special text fields could be added to a nextGIS layer that correspond to area/asset/log fields, including attachments (photos).
it would be nice to be able to sync without a live data connection, ie, when you return to a wifi connection you can synch, of course in large farms this would require conflict resolution between edits where they occur (rare). nextGIS supports the creation of webGIS endpoints which could provide the point of connection for this interoperability possibly via the farmOS sensor capabilities which I know nothing about.

**Comment by mstenta** [comment]
I'm cleaning up old issues, so I'm going to close this - but if you want to start a forum topic to discuss these ideas in the context of farmOS 2.x @bobombolo that would be most welcome! We're starting to use the forum for these kinds of discussions instead of the issue queue to keep things more centralized/organized.

https://farmOS.discourse.group
