### ISSUE TITLE
equivalent of usgs soils survey for canada, or adding other GIS layers

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#75]
how hard would it be to add custom layers to the area object.

**Comment by mstenta** [comment]
There is a feature request for canadian soil survey already, along with some implementation details: https://www.drupal.org/project/farm/issues/2930617

Adding GIS layers in general is just a process of setting them up in Openlayers.  Part of the decision process in farmOS is what module to put it in, so that people can choose which ones they want to enable.  As an example, there are two modules that provide map layers for Norway and Finland:

https://github.com/farmOS/farm_map_no

https://github.com/rkioski/farm_map_fi

**Comment by bobombolo** [comment]
what about gps-enabled tractor track files, is there an established way to add these to farmOS other than just attaching them as "files" for "planting" or "harvesting" logs?

**Comment by mstenta** [comment]
Yea you can start by uploading them to the Files field - and if it is a KML file (which some tractor GPSs can export), then you can pull that into the geometry field, so that it's visualized on the map.  See http://farmos.org/guide/areas/#importing-a-kml-file
