### ISSUE TITLE
Can't parse KML file get (Could not denormalize object of type "geometry_wrapper", no supporting normalizer found)

### ISSUE THREAD

**Issue by Pynee** [farmOS/farmOS#750]
**Describe the bug**
I'm trying to upload Kml file using KML Importer but when I try to parse it I get this error 
`Symfony\Component\Serializer\Exception\NotNormalizableValueException: Could not denormalize object of type "geometry_wrapper", no supporting normalizer found. in Symfony\Component\Serializer\Serializer->denormalize() (line 219 of /opt/drupal/vendor/symfony/serializer/Serializer.php).
`
My FarmOS instance is running in docker

**To Reproduce**
1. Run fresh FarmOS container and setup
2. Go to KML Import
3. press parse

**Desktop (please complete the following information):**
 - OS:Ubuntu 20.04
 - Docker: 24.0.7
 - Postgres:13.13-bullseye
 - Version 3.0.0-beta2

[pltunnus_9330065339.zip](https://github.com/farmOS/farmOS/files/13364559/pltunnus_9330065339.zip)
[docker-compose.zip](https://github.com/farmOS/farmOS/files/13364577/docker-compose.zip)

**Comment by mstenta** [comment]
Hi @Pynee is this on farmOS 3.0.0-beta1? Or farmOS 2.2.2?

**Comment by mstenta** [comment]
I was able to replicate this in farmOS 3.x.

I was able to fix it by adding `self::TYPE => TRUE,` to `KmlNormalizer::getSupportedTypes()`:

```
  /**
   * {@inheritdoc}
   */
  public function getSupportedTypes(?string $format): array {
    return [
      GeometryWrapper::class => TRUE,
      self::TYPE => TRUE,
    ];
  }
```

https://github.com/farmOS/farmOS/blob/97cf31b5bdaf4b8fa83d4f375be2201c86deb62c/modules/core/kml/src/Normalizer/KmlNormalizer.php#L169

However, @Pynee the KML file you provided as an example still didn't work. It shows a warning after clicking Parse: "No placemarks could be parsed from the uploaded file."

This appears to be because your KML has a `<Document>` tag nested within an outer `<Document>` tag:

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document id="root_doc">
    ...
    <Document id="pltunnus_9330065339">
      ...
```

Currently the farmOS KML encoder/decoder only handles a single level `<Document>` tag:

https://github.com/farmOS/farmOS/blob/97cf31b5bdaf4b8fa83d4f375be2201c86deb62c/modules/core/kml/src/Encoder/Kml.php#L67

I'm curious: how did you produce this KML file? Was it created/exported from another program?

**Comment by Pynee** [comment]
Original file was a shapefile from Finnish Food Authority [https://www.ruokavirasto.fi/en/about-us/open-information/inspire/](https://www.ruokavirasto.fi/en/about-us/open-information/inspire/) and I converted one field to KML file with QGIS software.
I also exported a file containing several fields and that file I can import now because It uses Folder tag instead of Document tag.
[fields.zip](https://github.com/farmOS/farmOS/files/13367053/fields.zip)

**Comment by mstenta** [comment]
OK interesting. Thanks for the info. I'm always curious about the KML standard, and why it seems like every software treats it a little differently. Makes it very tricky to support!

Well we'll get this bug you identified fixed ASAP and put out a new release soon. I also found a bug with the KML export which may be related, so we'll try to get all of those fixed and maybe add some more automated tests for future issues like this.

**Comment by paul121** [comment]
Thanks for reporting @Pynee !

> I was able to fix it by adding self::TYPE => TRUE, to KmlNormalizer::getSupportedTypes():

It makes sense that this fixes things. That `self:TYPE` is a string `geometry_wrapper` which we use in the `KmlImporter` form that initiates the denormalization from KML to geometry objects: https://github.com/farmOS/farmOS/blob/97cf31b5bdaf4b8fa83d4f375be2201c86deb62c/modules/core/import/modules/kml/src/Form/KmlImporter.php#L151

This got me thinking, maybe we should be using `GeometryWrapper::class` instead (like @mstenta added with the `getSupportedTypes()` method for 3.x). But now I remember some of the complexity and why I used `geometry_wrapper` instead of the class... we're really denormalizing an array of `GeometryWrapper` objects. I did not know the best way to specify this.

Not sure if this is new, but I now see the Symfony serializer documentation has a section on [Handling Arrays](https://symfony.com/doc/current/components/serializer.html#handling-arrays). Basically, Symfony provides an [`ArrayDenormalizer`](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php) that simply looks for `str_ends_with($type, '[]')` & a supporting denormalizer for the singular type ([source](https://github.com/symfony/symfony/blob/bb03b99987388865fe3a8150b5069cfed99e53d0/src/Symfony/Component/Serializer/Normalizer/ArrayDenormalizer.php#L83-L84)) ... unfortunately I do not think the default Drupal `serializer` service includes this `ArrayDenormalizer` itself, but I think we could do a simple version of this ourselves, by simply checking for `Drupal\farm_geo\GeometryWrapper[]` as the expected/supported type.

This would technically be a breaking change but I think it is something we could still do in 3.x? It's a general improvement and something that I don't think it used much externally. But fwiw it would be easy to continue supporting `geometry_wrapper` as well.

**Comment by paul121** [comment]
> unfortunately I do not think the default Drupal serializer service includes this ArrayDenormalizer itself, but I think we could do a simple version of this ourselves, by simply checking for Drupal\farm_geo\GeometryWrapper[] as the expected/supported type.

Well somewhere the Drupal serialization system does support handling arrays. I changed the supported types to be just `GeometryWrapper::class` and see that the normalizer method is run once for each `GeometryWrapper` object. I've opened a PR with these changes
