### ISSUE TITLE
Group field not visible on Asset Form

### ISSUE THREAD

**Issue by Fosten** [farmOS/farmOS#811]
The Group Asset module adds a “group” field to Assets.
The Group Asset module also adds “group” and “is_group_assignment” fields to Logs.

Both fields are visible and editable in the Log Form.
<img width="732" alt="Screen Shot 2024-03-26 at 9 48 35 PM" src="https://github.com/farmOS/farmOS/assets/1520484/8669424d-6bbd-4d87-a166-9fc10fa264a9">

However the “group” field is not visible or editable in the Asset Form.
<img width="734" alt="Screen Shot 2024-03-26 at 9 45 30 PM" src="https://github.com/farmOS/farmOS/assets/1520484/681fa9fa-4008-48b1-ba9a-2ea6a6b63ea3">

Even though the "group" field shows up in the asset view.
<img width="830" alt="Screen Shot 2024-03-26 at 9 45 12 PM" src="https://github.com/farmOS/farmOS/assets/1520484/3a73d97f-3429-48b4-8cac-941c1ebe559c">

And the “group” field shows up in the Filter List.
<img width="1073" alt="Screen Shot 2024-03-26 at 9 24 35 PM" src="https://github.com/farmOS/farmOS/assets/1520484/8820a399-a5d1-484b-93a1-39796d9ed044">

**Comment by Fosten** [comment]
Perhaps hidden here? https://github.com/farmOS/farmOS/blob/0156283a6361e9c59aa357008fde8b478b3ab09b/modules/asset/group/farm_group.base_fields.inc#L25

**Comment by paul121** [comment]
Hey @Fosten, this is actually by design. There is a subtle but important difference for the `group` field on assets: it is computed!

https://github.com/farmOS/farmOS/blob/0156283a6361e9c59aa357008fde8b478b3ab09b/modules/asset/group/farm_group.base_fields.inc#L24

This means that there is actually no storage/database table for the `group` field on assets and there is no need for a traditional form field*. Instead the field value is computed when the entity/asset is loaded. The logic we have implemented for this computed field uses group membership logs to update the asset's group over time. https://farmos.org/model/logic/group/#group-membership-logic

> there is no need for a traditional form field*. 

This said, a nice feature _could be_ to expose a `group` field on asset forms that actually creates a new group membership log behind the scenes. We've considered doing this but IMO it is better that people use the group membership action/quick form. We added a similar helper for the asset "Current location" computed field so there is a quick link to change the location (using quick form) from the asset view page... perhaps we could do something similar for asset group membership.

**Comment by mstenta** [comment]
> a nice feature could be to expose a `group` field on asset forms that actually creates a new group membership log behind the scenes.

We had something like this in farmOS v1 for the computed `location` field - allowing users to easily change the location of an asset from the asset edit form. But, in the v2 development process I decided not to replicate it. It was a nice shortcut, but it was also confusing to users because they didn't understand that a log was being created behind the scenes to change the location, and I saw a lot of cases where there were lots of weird logs in the system that would have been better off combined or done differently. So it was causing/encouraging messy data, and creating confusion. This was a case where what seemed to be good short-term UX turned out to be a source of bad long term UX.

> We've considered doing this but IMO it is better that people use the group membership action/quick form.

Agreed. By encouraging users to use the action/quick form they understand what they're doing.

That said, to @paul121's point, we can always add more shortcuts to get the user to those forms!

> We added a similar helper for the asset "Current location" computed field so there is a quick link to change the location (using quick form) from the asset view page... perhaps we could do something similar for asset group membership.

**Comment by Fosten** [comment]
Ah, makes sense.

I was expecting that group would work like parent, and you could just add the reference directly.
But see that is_group_assigment is similar to is_movement, where it needs to be tied to a log.

Seems like an extra layer of complexity when Group Membership is set once and isn’t going to change...
- "Add 'Chicken Plucker' to 'Chicken Equipment'"

But there are benefits to flexible Group Memberships too….
- “Add 'Harvest Log: Egg harvest’ referencing 'Asset: Chicken 1' and assign to 'Group: Chickens Currently Laying Eggs’"
- “Add ‘Observation Log: Egg production stopped’ referencing ‘Asset: Chicken 1’ and assign to ‘Group: Chickens Too Old to Lay Eggs’"

Thanks!

**Comment by mstenta** [comment]
> Group Membership is set once and isn’t going to change

Actually group membership can change! That's why it works the way it does, and isn't just a simple reference field. :-)

The Group module was originally added for grazing management, where animals are organized into herds. The composition of these herds may change over time, and it is necessary to capture those "membership changes" and see them in the form of logs. Your examples illustrate some of those cases. Similar ones have come up with cows/sheep moving to groups based on whether or not they are birthing/lactating/etc.

> "Add 'Chicken Plucker' to 'Chicken Equipment'"

We designed Group in a general way, so all these other use-cases (eg: groups of equipment) weren't actually imagined originally. They just bubbled up naturally as people started using it.

In many cases it may only be set once, though, it's true. The same is true of the `location` of `plant` assets. Most of the time they are moved once (to the ground) and that's it. But in other cases they are transplanted, live their lives in pots, etc etc, so multiple movements are necessary.
