### ISSUE TITLE
Failing to create taxonomy_term configurable field of non-configurable field storage image

### ISSUE THREAD

**Issue by Fosten** [farmOS/farmOS#826]
Tried to drush updb after updating latest 3.x-dev, but it hangs on updating...

Thinking it is caused by https://github.com/farmOS/farmOS/pull/807

Various error messages...

A non-existent config entity name returned by FieldStorageConfigInterface::getBundles(): entity type: taxonomy_term, bundle: unit, field name: image

...

Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "taxonomy_term__file" does not exist LINE 3: "taxonomy_term__file" "t" ^: SELECT "t".* FROM "taxonomy_term__file" "t" WHERE ("entity_id" IN (:db_condition_placeholder_0)) AND ("deleted" = :db_condition_placeholder_1) AND ("langcode" IN (:db_condition_placeholder_2, :db_condition_placeholder_3, :db_condition_placeholder_4)) ORDER BY "delta" ASC NULLS FIRST; Array ( [:db_condition_placeholder_0] => 6 [:db_condition_placeholder_1] => 0 [:db_condition_placeholder_2] => en [:db_condition_placeholder_3] => und [:db_condition_placeholder_4] => zxx ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->loadFromDedicatedTables() (line 1242 of /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

...

Drupal\Core\Field\FieldException: Attempted to create a configurable field of non-configurable field storage image. in Drupal\field\Entity\FieldConfig->getFieldStorageDefinition() (line 319 of core/modules/field/src/Entity/FieldConfig.php).

Drupal\jsonapi\ResourceType\ResourceTypeRepository->getFields(Array, Object, 'plant_type') (Line: 160)
Drupal\jsonapi\ResourceType\ResourceTypeRepository->createResourceType(Object, 'plant_type') (Line: 129)
Drupal\jsonapi_extras\ResourceType\ConfigurableResourceTypeRepository->createResourceType(Object, 'plant_type') (Line: 130)
Drupal\jsonapi\ResourceType\ResourceTypeRepository->Drupal\jsonapi\ResourceType\{closure}(Array, 'plant_type')
array_reduce(Array, Object, Array) (Line: 129)
Drupal\jsonapi\ResourceType\ResourceTypeRepository->all() (Line: 115)
Drupal\jsonapi\Routing\Routes->routes()
call_user_func(Array) (Line: 146)
Drupal\Core\Routing\RouteBuilder->rebuild() (Line: 83)
Drupal\Core\ProxyClass\Routing\RouteBuilder->rebuild() (Line: 485)
drupal_flush_all_caches() (Line: 45)
Drupal\system\Form\ClearCacheForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 129)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 67)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 597)
Drupal\Core\Form\FormBuilder->processForm('system_clear_cache', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm('Drupal\system\Form\ClearCacheForm', Object) (Line: 224)
Drupal\Core\Form\FormBuilder->getForm('Drupal\system\Form\ClearCacheForm') (Line: 23)
Drupal\system\Controller\PerformanceController->build()
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 54)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by mstenta** [comment]
@Fosten Hmm I'm unable to replicate this... :thinking: 

I just tested updating from 3.1.2 to 3.2.0 (the latest release), and the update hooks worked to create the new file fields on all taxonomy terms properly.

I tested by checking out 3.1.2 in my local environment, installing farmOS, then checking out 3.2.0 and running `drush updb` and `drush cr`.

Granted, my test doesn't change any dependency module versions, so it's a bit simplistic, but it does test the farmOS update hooks.

What was your process? What version were updating from? It sounds like you were attempting to update to a specific commit of the 3.x branch, and not a tagged release, correct? (Because you opened this issue while I was in the process of merging features for 3.2.0). Can you tell me exactly what commit hash you were updating to?

Hopefully you have a backup of your code and database and were able to rollback easily?

**Comment by mstenta** [comment]
Also, where exactly are you seeing these error messages? Originally I assumed they happened during `drush updb`, but re-reading your description above I'm not sure... because some seem to be coming from `jsonapi`? Can you include some more details about what pages/paths/actions are triggering the errors for you?

**Comment by Fosten** [comment]
This occurred as I was updating a 3.x-dev instance from a db state a few weeks ago before #807 

I received error 3 when using the update.php gui.  "Updating" would spin for a few minutes, so I reloaded the page to break the process and it churned out the exception.  Running clear cache through gui also didn't help.

This seemed to indicate the problem originated with plant_type field image.

Afterwards, error 1 showed in recent log messages and error 2 showed when I navigated the Taxonomy Terms (likely because the rest of the fields weren't created after it broke).

This seemed to indicate Error 1 and 2 were symptoms of error 3.

However today, when running through drush updb and drush cr through command line, everything went through successfully.  Odd.

Discussed this on the dev call and Mike mentioned that he wrote a hook to get around the plant_type image field replacement, so perhaps the gui update was having issues with the old image field.

Also entirely possible I borked something on my end during the update.

This ticket can probably be closed since it works through the command line
or Mike suggested he may do a test via the gui update.
or I could test again when I update my 3.x and 3.2.0 instances.

**Comment by mstenta** [comment]
I was able to replicate this by running `update.php` through the browser. This is the error I saw in my Docker logs (same as what @Fosten posted above) when I started the update procedure. In the browser, the update progress bar hangs and never proceeds.

`[Thu Apr 11 19:37:03.215800 2024] [php:notice] [pid 53] [client 172.31.0.1:53872] Drupal\\Core\\Field\\FieldException: Attempted to create a configurable field of non-configurable field storage image. in /opt/drupal/web/core/modules/field/src/Entity/FieldConfig.php on line 319 #0 /opt/drupal/web/core/modules/jsonapi/src/ResourceType/ResourceTypeRepository.php(279): Drupal\\field\\Entity\\FieldConfig->getFieldStorageDefinition()\n#1 /opt/drupal/web/core/modules/jsonapi/src/ResourceType/ResourceTypeRepository.php(160): Drupal\\jsonapi\\ResourceType\\ResourceTypeRepository->getFields(Array, Object(Drupal\\Core\\Entity\\ContentEntityType), 'plant_type')\n#2 /opt/drupal/web/modules/jsonapi_extras/src/ResourceType/ConfigurableResourceTypeRepository.php(129): Drupal\\jsonapi\\ResourceType\\ResourceTypeRepository->createResourceType(Object(Drupal\\Core\\Entity\\ContentEntityType), 'plant_type')\n#3 /opt/drupal/web/core/modules/jsonapi/src/ResourceType/ResourceTypeRepository.php(130): Drupal\\jsonapi_extras\\ResourceType\\ConfigurableResourceTypeRepository->createResourceType(Object(Drupal\\Core\\Entity\\ContentEntityType), 'plant_type')\n#4 [internal function]: Drupal\\jsonapi\\ResourceType\\ResourceTypeRepository->Drupal\\jsonapi\\ResourceType\\{closure}(Array, 'plant_type')\n#5 /opt/drupal/web/core/modules/jsonapi/src/ResourceType/ResourceTypeRepository.php(129): array_reduce(Array, Object(Closure), Array)\n#6 /opt/drupal/web/core/modules/jsonapi/src/Routing/Routes.php(115): Drupal\\jsonapi\\ResourceType\\ResourceTypeRepository->all()\n#7 [internal function]: Drupal\\jsonapi\\Routing\\Routes->routes()\n#8 /opt/drupal/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(146): call_user_func(Array)\n#9 /opt/drupal/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\\Core\\Routing\\RouteBuilder->rebuild()\n#10 /opt/drupal/web/core/includes/common.inc(485): Drupal\\Core\\ProxyClass\\Routing\\RouteBuilder->rebuild()\n#11 /opt/drupal/web/core/includes/batch.inc(296): drupal_flush_all_caches(Object(Drupal\\Core\\Update\\UpdateKernel))\n#12 /opt/drupal/web/core/includes/batch.inc(138): _batch_process()\n#13 /opt/drupal/web/core/includes/batch.inc(94): _batch_do()\n#14 /opt/drupal/web/core/modules/system/src/Controller/DbUpdateController.php(195): _batch_page(Object(Symfony\\Component\\HttpFoundation\\Request))\n#15 [internal function]: Drupal\\system\\Controller\\DbUpdateController->handle('start', Object(Symfony\\Component\\HttpFoundation\\Request))\n#16 /opt/drupal/web/core/lib/Drupal/Core/Update/UpdateKernel.php(115): call_user_func_array(Array, Array)\n#17 /opt/drupal/web/core/lib/Drupal/Core/Update/UpdateKernel.php(76): Drupal\\Core\\Update\\UpdateKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request))\n#18 /opt/drupal/web/update.php(27): Drupal\\Core\\Update\\UpdateKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#19 {main}, referer: http://localhost/update.php/start?id=1&op=start`

**Comment by mstenta** [comment]
I did some digging on this and discovered the root cause: Drupal runs `drupal_clear_all_caches()` in between running `hook_update_N()` and `hook_post_update_NAME()` update hooks.

The update hook for installing the `image` and `file` fields (and deleting the old `image` field config, which is causing this issue), is currently a `hook_post_update_NAME()` hook. So the cache is being cleared before it runs. During the cache clear, the JSON:API module rebuilds a whole bunch of routes, and in the process it loads the old `image` field config but sees that it's invalid because the `image` field is now being declared as a base field, not a config field. So it chokes.

The reason it works when you run the updates via `drush updb` is because Drush doesn't clear caches between those update hooks.

So, a quick fix for us would be to just change our `hook_post_update_NAME()` to a `hook_update_N()`. I tested this locally and it seems to fix the issue!

However, it makes me wonder about this extra cache clear that is happening in Drupal core during updates... and whether or not we need to rethink our general practice of always using `hook_post_update_NAME()`. :thinking:

**Comment by mstenta** [comment]
FWIW it looks like the cache clear has been there from the very beginning, when `hook_post_update_NAME()` was introduced 8 years ago during the Drupal 8 development cycle, so it isn't new. Introduced here:

https://git.drupalcode.org/project/drupal/-/commit/7d16f1c6e655ed77bddf3e9f61e60b5ea10816e3

https://www.drupal.org/node/2538108

**Comment by mstenta** [comment]
I opened a PR to fix this: https://github.com/farmOS/farmOS/pull/828

**Comment by mstenta** [comment]
PR merged. This is fixed in farmOS 3.2.1 (packaging now).
