### ISSUE TITLE
difference between adding area and adding term 

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#83]
from the change hierarchy menu you can hit "add term" which seems like add area but it is a different form which validates differently in that at least, it requires geometry. adding an area does not require geometry. i think terms and the menu i am seeing are some vestigial drupal thing. 
![screenshot from 2018-04-19 20-49-27](https://user-images.githubusercontent.com/25610408/39025144-5257eb1a-4413-11e8-9b1f-0242d1c5ceb4.png)

**Comment by mstenta** [comment]
> i think terms and the menu i am seeing are some vestigial drupal thing.

Yup, you're right. The "areas" in farmOS were built using Drupal's taxonomy system, so its still intertwined with some of that more general UI.

Ultimately, this will go away in the future, because I plan to change areas so that they are no longer taxonomy terms, and are instead just additional types of assets.  https://www.drupal.org/project/farm/issues/2363393
