### ISSUE TITLE
photo attachment should show by default

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#84]
any entity with a photo attached should show the photo at a reasonable size even above the map. it could also show as a tiny thumbnail in any kind of list.

**Comment by bobombolo** [comment]
photo attachments should also be "rotatable" under "operations".

**Comment by bobombolo** [comment]
For example when you click "all logs" then thumbnails don't show up but when you click "observations" they do.
Areas don't show thumbnails, maybe that's ok. I don't want to use my 5 file uploads testing the rest of the assets. maybe equipment and animals show up as thumbnails and you can ignore this post.
however the rotate option would be nice since NO system seems to be able to get exif rotations done properly and usually you have to re-rotate photos from phones.

**Comment by mstenta** [comment]
> any entity with a photo attached should show the photo at a reasonable size even above the map. it could also show as a tiny thumbnail in any kind of list.

Areas, assets, and logs all allow photos to be uploaded to them, and they are displayed in a Colorbox gallery (https://www.drupal.org/project/colorbox) when you view the area, asset, or log record.  So this already exists.

Asset lists show a thumbnail of the first uploaded photo (although looking now the "All assets" does not, so I'll add that...).  Log lists don't currently, so that might be worth adding as well.  I'm not going to do areas right now because they are shown in a tree hierarchy, which would get cluttered with a thumbnail also, I think.

Regarding rotation - yea it's an issue I've experienced as well.  farmOS include the EXIF Orientation module (https://www.drupal.org/project/exif_orientation) which tries to detect orientation from EXIF data on the image and will auto-rotate if it detects a mismatch... but it doesn't always work.  I don't think there are any modules available that provide the ability to rotate manually (there's this one, but I'm only adding new modules that have Drupal 8 versions at this point, to avoid blocking our upgrade path: https://www.drupal.org/project/simple_image_rotate)

**Comment by mstenta** [comment]
> Log lists don't currently, so that might be worth adding as well.

Actually, the "Observations" list does include a thumbnail, now that I look at it. So perhaps we should consider adding it to the others as well.

**Comment by bobombolo** [comment]
There should be a module for rotating and and flipping cropping. isn't imagecache still the thing?
anyway i have to pay for the hosting and then i'll upload zillions of photos. does importing csv files count towards the five file uploads on the demo?

**Comment by mstenta** [comment]
> isn't imagecache still the thing?

Yep, but that only allows setting image manipulation rules that always happen automatically - it doesn't provide manual controls on a per-image basis.

> does importing csv files count towards the five file uploads on the demo?

Yes it does.
