### ISSUE TITLE
how to use inputs correctly

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#86]
so inputs define what feed is available for different assets or groups of assets. however, how would you actually define the recipe or mixture of inputs. also, regarding the issue of adding feed as an asset with inventory and adding harvests as inputs with inventory, what should i be using to list both what I have in storage and what I am feeding various classes of animals?

**Comment by mstenta** [comment]
> so inputs define what feed is available for different assets or groups of assets. however, how would you actually define the recipe or mixture of inputs.

Input and harvest logs both allow you to add unlimited "Quantity measurements" to them.  See http://farmos.org/guide/quantity/

>  also, regarding the issue of adding feed as an asset with inventory and adding harvests as inputs with inventory, what should i be using to list both what I have in storage and what I am feeding various classes of animals?

Because there isn't an asset type in farmOS for "Feed" or "Materials" yet, there isn't a place to record what you currently have in inventory.  You can only record what you use in your input logs, or what you harvest in your harvest logs - but it doesn't keep track of inventory yet.  That's coming soon...

**Comment by bobombolo** [comment]
but how do i take a combination of inputs to make a feed mix that is tied to a certain group of animals

**Comment by mstenta** [comment]
You can reference the animal assets (or group asset) in the Input log's "Assets" field, and use the Quantity fields to record the various quantities that were given them. You can be as granular as you'd like using multiple quantity measurements - or you can be broad and just say "X kilograms of Y mix" (for example).

In the future, you'll also be able to have feed represented as an asset itself, and then deduct from its inventory when you feed your animals.
