### ISSUE TITLE
adding standard drupal types like blogs or other documents

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#88]
is it possible to add some regular document types? say you add a worker, can they access things like manuals and SOP documents? it would be nice to have this all in one place. And even use farmos as the public portal for the presentation of the farm with a contact form and "about us" and blogs and slideshows. given that this is all built into Drupal it should be easy to do...

**Comment by bobombolo** [comment]
also on farmier hosting what would be the bandwidth / cost consequences of exposing some documents to the wild web?

**Comment by mstenta** [comment]
> is it possible to add some regular document types? say you add a worker, can they access things like manuals and SOP documents? it would be nice to have this all in one place.

This will probably come about in the near future within farmOS itself.  I already built a simple "Document Center" concept within the Produce Safety module (https://github.com/farmOS/farm_produce_safety) for storing FSMA SOPs, training material, etc.  I've given some thought to generalizing that into farmOS itself, and expanding it to be more flexible.  This will be more and more necessary, especially as more folks use farmOS for various certification plans and records.

> And even use farmos as the public portal for the presentation of the farm with a contact form and "about us" and blogs and slideshows. given that this is all built into Drupal it should be easy to do...

Sure that would certainly be possible since it is all in Drupal. I have taken care to make sure that the farmOS-specific features are namespaced to avoid any potential conflicts with other modules. There would need to be some care taken with the theme (farm_theme) if you chose to use a different theme for the site.  The farmOS theme adds a number of UI improvements to the Bootstrap theme that are specific to farmOS, so there may be some teasing-apart necessary there.

That said, I do not have any plans to do build those features into the farmOS repository itself. If you want to experiment with it, you are more than welcome to.

> also on farmier hosting what would be the bandwidth / cost consequences of exposing some documents to the wild web?

Farmier only offers hosting of standard farmOS instances currently. Any customization or experimentation would need to be done in an instance that you host yourself. That said, the bandwidth / cost consequences would be the same for any other public-facing website - it would mainly depend on how much public web traffic you would expect.

**Comment by mstenta** [comment]
Added a farmOS core feature request for "Document Center": https://www.drupal.org/project/farm/issues/2965987
