### ISSUE TITLE
map window always square

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#93]
an issue with data entry is that if a form has a map on it and you are scrolling down with the mouse wheel then the scroll stops over the map and you start to zoom out over the map view. i think a simple solution would be that the map window could be always square so that there is a way to move the mouse to the side where there is white space while you scroll down the form.

**Comment by bobombolo** [comment]
also when editing and you have a form field that is either a "relation" or group selection the selection is 4 lines deep but the entire window wide.

**Comment by bobombolo** [comment]
thinking of eliminating paper and doing data entry via laptop... with dirty farmer hands.

**Comment by bobombolo** [comment]
can form fields with many entries be organized into columns and made at least 10 lines deep?

**Comment by mstenta** [comment]
> an issue with data entry is that if a form has a map on it and you are scrolling down with the mouse wheel then the scroll stops over the map and you start to zoom out over the map view.

See this related issue upstream in the Openlayers module: https://www.drupal.org/project/openlayers/issues/2953078

It boils down to similar issues in two contexts: keyboard+mouse interactions and mobile/touch interactions, so a solution would be needed that works for both (or two separate solutions that don't conflict).

> i think a simple solution would be that the map window could be always square so that there is a way to move the mouse to the side where there is white space while you scroll down the form.

I have done this already in some of the farmOS pages (eg: Areas, individual log/asset records), but on mobile devices it automatically stacks (otherwise the content is too small to be readable). It is full-width on listing pages (eg: asset cluster maps) because there isn't any sensible way to arrange things (either the list would be crammed to one side, or there would be a blank area to the left/right of the map).

So I think the best solution would be what's described in that Openlayers issue. I'd also be curious to see how other maps/services have solved this problem.

**Comment by mstenta** [comment]
> also when editing and you have a form field that is either a "relation" or group selection the selection is 4 lines deep but the entire window wide.

> can form fields with many entries be organized into columns and made at least 10 lines deep?

Could you attach a screenshot? Not sure exactly what you mean. Would help to see I think.

**Comment by bobombolo** [comment]
![screenshot from 2018-05-03 07-54-45](https://user-images.githubusercontent.com/25610408/39575116-64b34e32-4ea7-11e8-935f-698b9fe016a1.png)
i guess it is just an issue when there are many selectable items, scrolling through them and only seeing 4 or 5 at a time is difficult.

**Comment by mstenta** [comment]
Ah gotcha! Thanks.

Yea agreed - I've been frustrated by that too.  I actually took a different approach recently, but ran into another bug that forced me to revert.  But I think that has been resolved upstream so I could try it again: https://www.drupal.org/project/farm/issues/2893550 - I actually have this on my current roadmap, so there's a chance it will happen soon.

Caveat: this will change it in some places but not all. It won't actually change the "Relations" example you pointed to above, because that comes from Drupal's core taxonomy module. But... that "Relations" field is really just a shortcut for arranging the areas hierarchically, which can also be done via drag and drop from a link on the "Areas" page.  It's mainly an issue elsewhere (in logs) when you're trying to reference an area and have to scroll through a long list.
